package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * AngazmanId generated by hbm2java
 */
public class AngazmanId implements java.io.Serializable {

	private int predmet;
	private int akademskaGodina;
	private int osoba;

	public AngazmanId() {
	}

	public AngazmanId(int predmet, int akademskaGodina, int osoba) {
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.osoba = osoba;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

}
