package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * Angazman generated by hbm2java
 */
public class Angazman implements java.io.Serializable {

	private AngazmanId id;
	private Osoba osoba;
	private Predmet predmet;
	private AkademskaGodina akademskaGodina;
	private AngazmanStatus angazmanStatus;

	public Angazman() {
	}

	public Angazman(AngazmanId id, Osoba osoba, Predmet predmet,
			AkademskaGodina akademskaGodina, AngazmanStatus angazmanStatus) {
		this.id = id;
		this.osoba = osoba;
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.angazmanStatus = angazmanStatus;
	}

	public AngazmanId getId() {
		return this.id;
	}

	public void setId(AngazmanId id) {
		this.id = id;
	}

	public Osoba getOsoba() {
		return this.osoba;
	}

	public void setOsoba(Osoba osoba) {
		this.osoba = osoba;
	}

	public Predmet getPredmet() {
		return this.predmet;
	}

	public void setPredmet(Predmet predmet) {
		this.predmet = predmet;
	}

	public AkademskaGodina getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(AkademskaGodina akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public AngazmanStatus getAngazmanStatus() {
		return this.angazmanStatus;
	}

	public void setAngazmanStatus(AngazmanStatus angazmanStatus) {
		this.angazmanStatus = angazmanStatus;
	}

}
