package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * AnketaIzboriPitanja generated by hbm2java
 */
public class AnketaIzboriPitanja implements java.io.Serializable {

	private Integer id;
	private AnketaPitanje anketaPitanje;
	private String izbor;
	private byte dopisaniOdgovor;

	public AnketaIzboriPitanja() {
	}

	public AnketaIzboriPitanja(AnketaPitanje anketaPitanje, String izbor,
			byte dopisaniOdgovor) {
		this.anketaPitanje = anketaPitanje;
		this.izbor = izbor;
		this.dopisaniOdgovor = dopisaniOdgovor;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public AnketaPitanje getAnketaPitanje() {
		return this.anketaPitanje;
	}

	public void setAnketaPitanje(AnketaPitanje anketaPitanje) {
		this.anketaPitanje = anketaPitanje;
	}

	public String getIzbor() {
		return this.izbor;
	}

	public void setIzbor(String izbor) {
		this.izbor = izbor;
	}

	public byte getDopisaniOdgovor() {
		return this.dopisaniOdgovor;
	}

	public void setDopisaniOdgovor(byte dopisaniOdgovor) {
		this.dopisaniOdgovor = dopisaniOdgovor;
	}

}
