package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AnketaAnketa generated by hbm2java
 */
public class AnketaAnketa implements java.io.Serializable {

	private Integer id;
	private Predmet predmet;
	private AkademskaGodina akademskaGodina;
	private Date datumOtvaranja;
	private Date datumZatvaranja;
	private String naziv;
	private String opis;
	private Boolean aktivna;
	private Boolean editable;
	private Set<AnketaPitanje> anketaPitanjes = new HashSet<AnketaPitanje>(0);
	private Set<AnketaPredmet> anketaPredmets = new HashSet<AnketaPredmet>(0);

	public AnketaAnketa() {
	}

	public AnketaAnketa(String naziv) {
		this.naziv = naziv;
	}

	public AnketaAnketa(Predmet predmet, AkademskaGodina akademskaGodina,
			Date datumOtvaranja, Date datumZatvaranja, String naziv,
			String opis, Boolean aktivna, Boolean editable,
			Set<AnketaPitanje> anketaPitanjes, Set<AnketaPredmet> anketaPredmets) {
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.datumOtvaranja = datumOtvaranja;
		this.datumZatvaranja = datumZatvaranja;
		this.naziv = naziv;
		this.opis = opis;
		this.aktivna = aktivna;
		this.editable = editable;
		this.anketaPitanjes = anketaPitanjes;
		this.anketaPredmets = anketaPredmets;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Predmet getPredmet() {
		return this.predmet;
	}

	public void setPredmet(Predmet predmet) {
		this.predmet = predmet;
	}

	public AkademskaGodina getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(AkademskaGodina akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public Date getDatumOtvaranja() {
		return this.datumOtvaranja;
	}

	public void setDatumOtvaranja(Date datumOtvaranja) {
		this.datumOtvaranja = datumOtvaranja;
	}

	public Date getDatumZatvaranja() {
		return this.datumZatvaranja;
	}

	public void setDatumZatvaranja(Date datumZatvaranja) {
		this.datumZatvaranja = datumZatvaranja;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	public Boolean getAktivna() {
		return this.aktivna;
	}

	public void setAktivna(Boolean aktivna) {
		this.aktivna = aktivna;
	}

	public Boolean getEditable() {
		return this.editable;
	}

	public void setEditable(Boolean editable) {
		this.editable = editable;
	}

	public Set<AnketaPitanje> getAnketaPitanjes() {
		return this.anketaPitanjes;
	}

	public void setAnketaPitanjes(Set<AnketaPitanje> anketaPitanjes) {
		this.anketaPitanjes = anketaPitanjes;
	}

	public Set<AnketaPredmet> getAnketaPredmets() {
		return this.anketaPredmets;
	}

	public void setAnketaPredmets(Set<AnketaPredmet> anketaPredmets) {
		this.anketaPredmets = anketaPredmets;
	}

}
