package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AnketaTipPitanja generated by hbm2java
 */
public class AnketaTipPitanja implements java.io.Serializable {

	private Integer id;
	private String tip;
	private String postojiIzbor;
	private String tabelaOdgovora;
	private Set<AnketaPitanje> anketaPitanjes = new HashSet<AnketaPitanje>(0);

	public AnketaTipPitanja() {
	}

	public AnketaTipPitanja(String tip, String postojiIzbor,
			String tabelaOdgovora) {
		this.tip = tip;
		this.postojiIzbor = postojiIzbor;
		this.tabelaOdgovora = tabelaOdgovora;
	}

	public AnketaTipPitanja(String tip, String postojiIzbor,
			String tabelaOdgovora, Set<AnketaPitanje> anketaPitanjes) {
		this.tip = tip;
		this.postojiIzbor = postojiIzbor;
		this.tabelaOdgovora = tabelaOdgovora;
		this.anketaPitanjes = anketaPitanjes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTip() {
		return this.tip;
	}

	public void setTip(String tip) {
		this.tip = tip;
	}

	public String getPostojiIzbor() {
		return this.postojiIzbor;
	}

	public void setPostojiIzbor(String postojiIzbor) {
		this.postojiIzbor = postojiIzbor;
	}

	public String getTabelaOdgovora() {
		return this.tabelaOdgovora;
	}

	public void setTabelaOdgovora(String tabelaOdgovora) {
		this.tabelaOdgovora = tabelaOdgovora;
	}

	public Set<AnketaPitanje> getAnketaPitanjes() {
		return this.anketaPitanjes;
	}

	public void setAnketaPitanjes(Set<AnketaPitanje> anketaPitanjes) {
		this.anketaPitanjes = anketaPitanjes;
	}

}
