package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * AnketaPredmetId generated by hbm2java
 */
public class AnketaPredmetId implements java.io.Serializable {

	private int anketa;
	private Integer predmet;
	private int akademskaGodina;
	private int semestar;
	private boolean aktivna;

	public AnketaPredmetId() {
	}

	public AnketaPredmetId(int anketa, Integer predmet, int akademskaGodina,
			int semestar, boolean aktivna) {
		this.anketa = anketa;
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.semestar = semestar;
		this.aktivna = aktivna;
	}

	public int getAnketa() {
		return this.anketa;
	}

	public void setAnketa(int anketa) {
		this.anketa = anketa;
	}

	public Integer getPredmet() {
		return this.predmet;
	}

	public void setPredmet(Integer predmet) {
		this.predmet = predmet;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public int getSemestar() {
		return this.semestar;
	}

	public void setSemestar(int semestar) {
		this.semestar = semestar;
	}

	public boolean isAktivna() {
		return this.aktivna;
	}

	public void setAktivna(boolean aktivna) {
		this.aktivna = aktivna;
	}

}
