package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AnketaRezultat generated by hbm2java
 */
public class AnketaRezultat implements java.io.Serializable {

	private Integer id;
	private int anketa;
	private String zavrsena;
	private Integer predmet;
	private String uniqueId;
	private int akademskaGodina;
	private Integer studij;
	private int semestar;
	private Integer student;
	private int labgrupa;
	private Set<AnketaOdgovorRank> anketaOdgovorRanks = new HashSet<AnketaOdgovorRank>(
			0);
	private Set<AnketaOdgovorText> anketaOdgovorTexts = new HashSet<AnketaOdgovorText>(
			0);
	private Set<AnketaOdgovorDopisani> anketaOdgovorDopisanis = new HashSet<AnketaOdgovorDopisani>(
			0);

	public AnketaRezultat() {
	}

	public AnketaRezultat(int anketa, int akademskaGodina, int semestar,
			int labgrupa) {
		this.anketa = anketa;
		this.akademskaGodina = akademskaGodina;
		this.semestar = semestar;
		this.labgrupa = labgrupa;
	}

	public AnketaRezultat(int anketa, String zavrsena, Integer predmet,
			String uniqueId, int akademskaGodina, Integer studij, int semestar,
			Integer student, int labgrupa,
			Set<AnketaOdgovorRank> anketaOdgovorRanks,
			Set<AnketaOdgovorText> anketaOdgovorTexts,
			Set<AnketaOdgovorDopisani> anketaOdgovorDopisanis) {
		this.anketa = anketa;
		this.zavrsena = zavrsena;
		this.predmet = predmet;
		this.uniqueId = uniqueId;
		this.akademskaGodina = akademskaGodina;
		this.studij = studij;
		this.semestar = semestar;
		this.student = student;
		this.labgrupa = labgrupa;
		this.anketaOdgovorRanks = anketaOdgovorRanks;
		this.anketaOdgovorTexts = anketaOdgovorTexts;
		this.anketaOdgovorDopisanis = anketaOdgovorDopisanis;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getAnketa() {
		return this.anketa;
	}

	public void setAnketa(int anketa) {
		this.anketa = anketa;
	}

	public String getZavrsena() {
		return this.zavrsena;
	}

	public void setZavrsena(String zavrsena) {
		this.zavrsena = zavrsena;
	}

	public Integer getPredmet() {
		return this.predmet;
	}

	public void setPredmet(Integer predmet) {
		this.predmet = predmet;
	}

	public String getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public Integer getStudij() {
		return this.studij;
	}

	public void setStudij(Integer studij) {
		this.studij = studij;
	}

	public int getSemestar() {
		return this.semestar;
	}

	public void setSemestar(int semestar) {
		this.semestar = semestar;
	}

	public Integer getStudent() {
		return this.student;
	}

	public void setStudent(Integer student) {
		this.student = student;
	}

	public int getLabgrupa() {
		return this.labgrupa;
	}

	public void setLabgrupa(int labgrupa) {
		this.labgrupa = labgrupa;
	}

	public Set<AnketaOdgovorRank> getAnketaOdgovorRanks() {
		return this.anketaOdgovorRanks;
	}

	public void setAnketaOdgovorRanks(Set<AnketaOdgovorRank> anketaOdgovorRanks) {
		this.anketaOdgovorRanks = anketaOdgovorRanks;
	}

	public Set<AnketaOdgovorText> getAnketaOdgovorTexts() {
		return this.anketaOdgovorTexts;
	}

	public void setAnketaOdgovorTexts(Set<AnketaOdgovorText> anketaOdgovorTexts) {
		this.anketaOdgovorTexts = anketaOdgovorTexts;
	}

	public Set<AnketaOdgovorDopisani> getAnketaOdgovorDopisanis() {
		return this.anketaOdgovorDopisanis;
	}

	public void setAnketaOdgovorDopisanis(
			Set<AnketaOdgovorDopisani> anketaOdgovorDopisanis) {
		this.anketaOdgovorDopisanis = anketaOdgovorDopisanis;
	}

}
