package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * AnketaOdgovorIzboriId generated by hbm2java
 */
public class AnketaOdgovorIzboriId implements java.io.Serializable {

	private int rezultat;
	private int pitanje;
	private int izborId;

	public AnketaOdgovorIzboriId() {
	}

	public AnketaOdgovorIzboriId(int rezultat, int pitanje, int izborId) {
		this.rezultat = rezultat;
		this.pitanje = pitanje;
		this.izborId = izborId;
	}

	public int getRezultat() {
		return this.rezultat;
	}

	public void setRezultat(int rezultat) {
		this.rezultat = rezultat;
	}

	public int getPitanje() {
		return this.pitanje;
	}

	public void setPitanje(int pitanje) {
		this.pitanje = pitanje;
	}

	public int getIzborId() {
		return this.izborId;
	}

	public void setIzborId(int izborId) {
		this.izborId = izborId;
	}

}
