package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * AnketaOdgovorDopisani generated by hbm2java
 */
public class AnketaOdgovorDopisani implements java.io.Serializable {

	private AnketaOdgovorDopisaniId id;
	private AnketaPitanje anketaPitanje;
	private AnketaRezultat anketaRezultat;
	private String odgovor;

	public AnketaOdgovorDopisani() {
	}

	public AnketaOdgovorDopisani(AnketaOdgovorDopisaniId id,
			AnketaPitanje anketaPitanje, AnketaRezultat anketaRezultat,
			String odgovor) {
		this.id = id;
		this.anketaPitanje = anketaPitanje;
		this.anketaRezultat = anketaRezultat;
		this.odgovor = odgovor;
	}

	public AnketaOdgovorDopisaniId getId() {
		return this.id;
	}

	public void setId(AnketaOdgovorDopisaniId id) {
		this.id = id;
	}

	public AnketaPitanje getAnketaPitanje() {
		return this.anketaPitanje;
	}

	public void setAnketaPitanje(AnketaPitanje anketaPitanje) {
		this.anketaPitanje = anketaPitanje;
	}

	public AnketaRezultat getAnketaRezultat() {
		return this.anketaRezultat;
	}

	public void setAnketaRezultat(AnketaRezultat anketaRezultat) {
		this.anketaRezultat = anketaRezultat;
	}

	public String getOdgovor() {
		return this.odgovor;
	}

	public void setOdgovor(String odgovor) {
		this.odgovor = odgovor;
	}

}
