package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * AnketaOdgovorRank generated by hbm2java
 */
public class AnketaOdgovorRank implements java.io.Serializable {

	private AnketaOdgovorRankId id;
	private AnketaPitanje anketaPitanje;
	private AnketaRezultat anketaRezultat;
	private int izborId;

	public AnketaOdgovorRank() {
	}

	public AnketaOdgovorRank(AnketaOdgovorRankId id,
			AnketaPitanje anketaPitanje, AnketaRezultat anketaRezultat,
			int izborId) {
		this.id = id;
		this.anketaPitanje = anketaPitanje;
		this.anketaRezultat = anketaRezultat;
		this.izborId = izborId;
	}

	public AnketaOdgovorRankId getId() {
		return this.id;
	}

	public void setId(AnketaOdgovorRankId id) {
		this.id = id;
	}

	public AnketaPitanje getAnketaPitanje() {
		return this.anketaPitanje;
	}

	public void setAnketaPitanje(AnketaPitanje anketaPitanje) {
		this.anketaPitanje = anketaPitanje;
	}

	public AnketaRezultat getAnketaRezultat() {
		return this.anketaRezultat;
	}

	public void setAnketaRezultat(AnketaRezultat anketaRezultat) {
		this.anketaRezultat = anketaRezultat;
	}

	public int getIzborId() {
		return this.izborId;
	}

	public void setIzborId(int izborId) {
		this.izborId = izborId;
	}

}
