package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * AnketaOdgovorIzbori generated by hbm2java
 */
public class AnketaOdgovorIzbori implements java.io.Serializable {

	private AnketaOdgovorIzboriId id;
	private AnketaPitanje anketaPitanje;

	public AnketaOdgovorIzbori() {
	}

	public AnketaOdgovorIzbori(AnketaOdgovorIzboriId id,
			AnketaPitanje anketaPitanje) {
		this.id = id;
		this.anketaPitanje = anketaPitanje;
	}

	public AnketaOdgovorIzboriId getId() {
		return this.id;
	}

	public void setId(AnketaOdgovorIzboriId id) {
		this.id = id;
	}

	public AnketaPitanje getAnketaPitanje() {
		return this.anketaPitanje;
	}

	public void setAnketaPitanje(AnketaPitanje anketaPitanje) {
		this.anketaPitanje = anketaPitanje;
	}

}
