package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * AuthId generated by hbm2java
 */
public class AuthId implements java.io.Serializable {

	private int id;
	private String login;

	public AuthId() {
	}

	public AuthId(int id, String login) {
		this.id = id;
		this.login = login;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

}
