package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AutotestRezultat generated by hbm2java
 */
public class AutotestRezultat implements java.io.Serializable {

	private AutotestRezultatId id;
	private Osoba osoba;
	private String izlazPrograma;
	private String status;
	private String nalaz;
	private Date vrijeme;
	private int trajanje;
	private String testniSistem;

	public AutotestRezultat() {
	}

	public AutotestRezultat(AutotestRezultatId id, Osoba osoba,
			String izlazPrograma, String status, String nalaz, Date vrijeme,
			int trajanje, String testniSistem) {
		this.id = id;
		this.osoba = osoba;
		this.izlazPrograma = izlazPrograma;
		this.status = status;
		this.nalaz = nalaz;
		this.vrijeme = vrijeme;
		this.trajanje = trajanje;
		this.testniSistem = testniSistem;
	}

	public AutotestRezultatId getId() {
		return this.id;
	}

	public void setId(AutotestRezultatId id) {
		this.id = id;
	}

	public Osoba getOsoba() {
		return this.osoba;
	}

	public void setOsoba(Osoba osoba) {
		this.osoba = osoba;
	}

	public String getIzlazPrograma() {
		return this.izlazPrograma;
	}

	public void setIzlazPrograma(String izlazPrograma) {
		this.izlazPrograma = izlazPrograma;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getNalaz() {
		return this.nalaz;
	}

	public void setNalaz(String nalaz) {
		this.nalaz = nalaz;
	}

	public Date getVrijeme() {
		return this.vrijeme;
	}

	public void setVrijeme(Date vrijeme) {
		this.vrijeme = vrijeme;
	}

	public int getTrajanje() {
		return this.trajanje;
	}

	public void setTrajanje(int trajanje) {
		this.trajanje = trajanje;
	}

	public String getTestniSistem() {
		return this.testniSistem;
	}

	public void setTestniSistem(String testniSistem) {
		this.testniSistem = testniSistem;
	}

}
