package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Cas generated by hbm2java
 */
public class Cas implements java.io.Serializable {

	private Integer id;
	private Labgrupa labgrupa;
	private Komponenta komponenta;
	private Osoba osoba;
	private Date datum;
	private Date vrijeme;
	private Integer kviz;

	public Cas() {
	}

	public Cas(Labgrupa labgrupa, Komponenta komponenta, Osoba osoba,
			Date datum, Date vrijeme) {
		this.labgrupa = labgrupa;
		this.komponenta = komponenta;
		this.osoba = osoba;
		this.datum = datum;
		this.vrijeme = vrijeme;
	}

	public Cas(Labgrupa labgrupa, Komponenta komponenta, Osoba osoba,
			Date datum, Date vrijeme, Integer kviz) {
		this.labgrupa = labgrupa;
		this.komponenta = komponenta;
		this.osoba = osoba;
		this.datum = datum;
		this.vrijeme = vrijeme;
		this.kviz = kviz;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Labgrupa getLabgrupa() {
		return this.labgrupa;
	}

	public void setLabgrupa(Labgrupa labgrupa) {
		this.labgrupa = labgrupa;
	}

	public Komponenta getKomponenta() {
		return this.komponenta;
	}

	public void setKomponenta(Komponenta komponenta) {
		this.komponenta = komponenta;
	}

	public Osoba getOsoba() {
		return this.osoba;
	}

	public void setOsoba(Osoba osoba) {
		this.osoba = osoba;
	}

	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	public Date getVrijeme() {
		return this.vrijeme;
	}

	public void setVrijeme(Date vrijeme) {
		this.vrijeme = vrijeme;
	}

	public Integer getKviz() {
		return this.kviz;
	}

	public void setKviz(Integer kviz) {
		this.kviz = kviz;
	}

}
