package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * Email generated by hbm2java
 */
public class Email implements java.io.Serializable {

	private Integer id;
	private Osoba osoba;
	private String adresa;
	private boolean sistemska;

	public Email() {
	}

	public Email(Osoba osoba, String adresa, boolean sistemska) {
		this.osoba = osoba;
		this.adresa = adresa;
		this.sistemska = sistemska;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Osoba getOsoba() {
		return this.osoba;
	}

	public void setOsoba(Osoba osoba) {
		this.osoba = osoba;
	}

	public String getAdresa() {
		return this.adresa;
	}

	public void setAdresa(String adresa) {
		this.adresa = adresa;
	}

	public boolean isSistemska() {
		return this.sistemska;
	}

	public void setSistemska(boolean sistemska) {
		this.sistemska = sistemska;
	}

}
