package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * GgPredmet generated by hbm2java
 */
public class GgPredmet implements java.io.Serializable {

	private GgPredmetId id;
	private Predmet predmet;
	private AkademskaGodina akademskaGodina;
	private String url;

	public GgPredmet() {
	}

	public GgPredmet(GgPredmetId id, Predmet predmet,
			AkademskaGodina akademskaGodina, String url) {
		this.id = id;
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.url = url;
	}

	public GgPredmetId getId() {
		return this.id;
	}

	public void setId(GgPredmetId id) {
		this.id = id;
	}

	public Predmet getPredmet() {
		return this.predmet;
	}

	public void setPredmet(Predmet predmet) {
		this.predmet = predmet;
	}

	public AkademskaGodina getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(AkademskaGodina akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
