package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * IspitocjeneId generated by hbm2java
 */
public class IspitocjeneId implements java.io.Serializable {

	private int ispit;
	private int student;

	public IspitocjeneId() {
	}

	public IspitocjeneId(int ispit, int student) {
		this.ispit = ispit;
		this.student = student;
	}

	public int getIspit() {
		return this.ispit;
	}

	public void setIspit(int ispit) {
		this.ispit = ispit;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

}
