package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ispit generated by hbm2java
 */
public class Ispit implements java.io.Serializable {

	private Integer id;
	private Predmet predmet;
	private AkademskaGodina akademskaGodina;
	private Komponenta komponenta;
	private Date datum;
	private Date vrijemeobjave;
	private Set<IspitTermin> ispitTermins = new HashSet<IspitTermin>(0);
	private Set<Ispitocjene> ispitocjenes = new HashSet<Ispitocjene>(0);

	public Ispit() {
	}

	public Ispit(Predmet predmet, AkademskaGodina akademskaGodina,
			Komponenta komponenta, Date datum, Date vrijemeobjave) {
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.komponenta = komponenta;
		this.datum = datum;
		this.vrijemeobjave = vrijemeobjave;
	}

	public Ispit(Predmet predmet, AkademskaGodina akademskaGodina,
			Komponenta komponenta, Date datum, Date vrijemeobjave,
			Set<IspitTermin> ispitTermins, Set<Ispitocjene> ispitocjenes) {
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.komponenta = komponenta;
		this.datum = datum;
		this.vrijemeobjave = vrijemeobjave;
		this.ispitTermins = ispitTermins;
		this.ispitocjenes = ispitocjenes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Predmet getPredmet() {
		return this.predmet;
	}

	public void setPredmet(Predmet predmet) {
		this.predmet = predmet;
	}

	public AkademskaGodina getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(AkademskaGodina akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public Komponenta getKomponenta() {
		return this.komponenta;
	}

	public void setKomponenta(Komponenta komponenta) {
		this.komponenta = komponenta;
	}

	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	public Date getVrijemeobjave() {
		return this.vrijemeobjave;
	}

	public void setVrijemeobjave(Date vrijemeobjave) {
		this.vrijemeobjave = vrijemeobjave;
	}

	public Set<IspitTermin> getIspitTermins() {
		return this.ispitTermins;
	}

	public void setIspitTermins(Set<IspitTermin> ispitTermins) {
		this.ispitTermins = ispitTermins;
	}

	public Set<Ispitocjene> getIspitocjenes() {
		return this.ispitocjenes;
	}

	public void setIspitocjenes(Set<Ispitocjene> ispitocjenes) {
		this.ispitocjenes = ispitocjenes;
	}

}
