package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * IspitTermin generated by hbm2java
 */
public class IspitTermin implements java.io.Serializable {

	private Integer id;
	private Ispit ispit;
	private Date datumvrijeme;
	private int komponenta;
	private int maxstudenata;
	private Date deadline;

	public IspitTermin() {
	}

	public IspitTermin(Ispit ispit, Date datumvrijeme, int komponenta,
			int maxstudenata, Date deadline) {
		this.ispit = ispit;
		this.datumvrijeme = datumvrijeme;
		this.komponenta = komponenta;
		this.maxstudenata = maxstudenata;
		this.deadline = deadline;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Ispit getIspit() {
		return this.ispit;
	}

	public void setIspit(Ispit ispit) {
		this.ispit = ispit;
	}

	public Date getDatumvrijeme() {
		return this.datumvrijeme;
	}

	public void setDatumvrijeme(Date datumvrijeme) {
		this.datumvrijeme = datumvrijeme;
	}

	public int getKomponenta() {
		return this.komponenta;
	}

	public void setKomponenta(int komponenta) {
		this.komponenta = komponenta;
	}

	public int getMaxstudenata() {
		return this.maxstudenata;
	}

	public void setMaxstudenata(int maxstudenata) {
		this.maxstudenata = maxstudenata;
	}

	public Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}

}
