package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * Komponentebodovi generated by hbm2java
 */
public class Komponentebodovi implements java.io.Serializable {

	private KomponentebodoviId id;
	private Ponudakursa ponudakursa;
	private Komponenta komponenta;
	private Osoba osoba;
	private double bodovi;

	public Komponentebodovi() {
	}

	public Komponentebodovi(KomponentebodoviId id, Ponudakursa ponudakursa,
			Komponenta komponenta, Osoba osoba, double bodovi) {
		this.id = id;
		this.ponudakursa = ponudakursa;
		this.komponenta = komponenta;
		this.osoba = osoba;
		this.bodovi = bodovi;
	}

	public KomponentebodoviId getId() {
		return this.id;
	}

	public void setId(KomponentebodoviId id) {
		this.id = id;
	}

	public Ponudakursa getPonudakursa() {
		return this.ponudakursa;
	}

	public void setPonudakursa(Ponudakursa ponudakursa) {
		this.ponudakursa = ponudakursa;
	}

	public Komponenta getKomponenta() {
		return this.komponenta;
	}

	public void setKomponenta(Komponenta komponenta) {
		this.komponenta = komponenta;
	}

	public Osoba getOsoba() {
		return this.osoba;
	}

	public void setOsoba(Osoba osoba) {
		this.osoba = osoba;
	}

	public double getBodovi() {
		return this.bodovi;
	}

	public void setBodovi(double bodovi) {
		this.bodovi = bodovi;
	}

}
