package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * KomponentebodoviId generated by hbm2java
 */
public class KomponentebodoviId implements java.io.Serializable {

	private int student;
	private int predmet;
	private int komponenta;

	public KomponentebodoviId() {
	}

	public KomponentebodoviId(int student, int predmet, int komponenta) {
		this.student = student;
		this.predmet = predmet;
		this.komponenta = komponenta;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public int getKomponenta() {
		return this.komponenta;
	}

	public void setKomponenta(int komponenta) {
		this.komponenta = komponenta;
	}

}
