package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Labgrupa generated by hbm2java
 */
public class Labgrupa implements java.io.Serializable {

	private Integer id;
	private Predmet predmet;
	private AkademskaGodina akademskaGodina;
	private String naziv;
	private String tip;
	private boolean virtualna;
	private Set<Cas> cases = new HashSet<Cas>(0);
	private Set<Kviz> kvizs = new HashSet<Kviz>(0);
	private Set<Osoba> osobas = new HashSet<Osoba>(0);
	private Set<Komentar> komentars = new HashSet<Komentar>(0);

	public Labgrupa() {
	}

	public Labgrupa(Predmet predmet, AkademskaGodina akademskaGodina,
			String naziv, String tip, boolean virtualna) {
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.naziv = naziv;
		this.tip = tip;
		this.virtualna = virtualna;
	}

	public Labgrupa(Predmet predmet, AkademskaGodina akademskaGodina,
			String naziv, String tip, boolean virtualna, Set<Cas> cases,
			Set<Kviz> kvizs, Set<Osoba> osobas, Set<Komentar> komentars) {
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.naziv = naziv;
		this.tip = tip;
		this.virtualna = virtualna;
		this.cases = cases;
		this.kvizs = kvizs;
		this.osobas = osobas;
		this.komentars = komentars;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Predmet getPredmet() {
		return this.predmet;
	}

	public void setPredmet(Predmet predmet) {
		this.predmet = predmet;
	}

	public AkademskaGodina getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(AkademskaGodina akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public String getTip() {
		return this.tip;
	}

	public void setTip(String tip) {
		this.tip = tip;
	}

	public boolean isVirtualna() {
		return this.virtualna;
	}

	public void setVirtualna(boolean virtualna) {
		this.virtualna = virtualna;
	}

	public Set<Cas> getCases() {
		return this.cases;
	}

	public void setCases(Set<Cas> cases) {
		this.cases = cases;
	}

	public Set<Kviz> getKvizs() {
		return this.kvizs;
	}

	public void setKvizs(Set<Kviz> kvizs) {
		this.kvizs = kvizs;
	}

	public Set<Osoba> getOsobas() {
		return this.osobas;
	}

	public void setOsobas(Set<Osoba> osobas) {
		this.osobas = osobas;
	}

	public Set<Komentar> getKomentars() {
		return this.komentars;
	}

	public void setKomentars(Set<Komentar> komentars) {
		this.komentars = komentars;
	}

}
