package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Mjesto generated by hbm2java
 */
public class Mjesto implements java.io.Serializable {

	private Integer id;
	private Drzava drzava;
	private String naziv;
	private int opcina;
	private String opcinaVanBih;
	private Set<Osoba> osobasForMjestoRodjenja = new HashSet<Osoba>(0);
	private Set<Osoba> osobasForAdresaMjesto = new HashSet<Osoba>(0);

	public Mjesto() {
	}

	public Mjesto(Drzava drzava, String naziv, int opcina, String opcinaVanBih) {
		this.drzava = drzava;
		this.naziv = naziv;
		this.opcina = opcina;
		this.opcinaVanBih = opcinaVanBih;
	}

	public Mjesto(Drzava drzava, String naziv, int opcina, String opcinaVanBih,
			Set<Osoba> osobasForMjestoRodjenja, Set<Osoba> osobasForAdresaMjesto) {
		this.drzava = drzava;
		this.naziv = naziv;
		this.opcina = opcina;
		this.opcinaVanBih = opcinaVanBih;
		this.osobasForMjestoRodjenja = osobasForMjestoRodjenja;
		this.osobasForAdresaMjesto = osobasForAdresaMjesto;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Drzava getDrzava() {
		return this.drzava;
	}

	public void setDrzava(Drzava drzava) {
		this.drzava = drzava;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public int getOpcina() {
		return this.opcina;
	}

	public void setOpcina(int opcina) {
		this.opcina = opcina;
	}

	public String getOpcinaVanBih() {
		return this.opcinaVanBih;
	}

	public void setOpcinaVanBih(String opcinaVanBih) {
		this.opcinaVanBih = opcinaVanBih;
	}

	public Set<Osoba> getOsobasForMjestoRodjenja() {
		return this.osobasForMjestoRodjenja;
	}

	public void setOsobasForMjestoRodjenja(Set<Osoba> osobasForMjestoRodjenja) {
		this.osobasForMjestoRodjenja = osobasForMjestoRodjenja;
	}

	public Set<Osoba> getOsobasForAdresaMjesto() {
		return this.osobasForAdresaMjesto;
	}

	public void setOsobasForAdresaMjesto(Set<Osoba> osobasForAdresaMjesto) {
		this.osobasForAdresaMjesto = osobasForAdresaMjesto;
	}

}
