package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * NastavnikPredmet generated by hbm2java
 */
public class NastavnikPredmet implements java.io.Serializable {

	private NastavnikPredmetId id;
	private Predmet predmet;
	private AkademskaGodina akademskaGodina;
	private Osoba osoba;
	private boolean admin;
	private String nivoPristupa;

	public NastavnikPredmet() {
	}

	public NastavnikPredmet(NastavnikPredmetId id, Predmet predmet,
			AkademskaGodina akademskaGodina, Osoba osoba, boolean admin,
			String nivoPristupa) {
		this.id = id;
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.osoba = osoba;
		this.admin = admin;
		this.nivoPristupa = nivoPristupa;
	}

	public NastavnikPredmetId getId() {
		return this.id;
	}

	public void setId(NastavnikPredmetId id) {
		this.id = id;
	}

	public Predmet getPredmet() {
		return this.predmet;
	}

	public void setPredmet(Predmet predmet) {
		this.predmet = predmet;
	}

	public AkademskaGodina getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(AkademskaGodina akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public Osoba getOsoba() {
		return this.osoba;
	}

	public void setOsoba(Osoba osoba) {
		this.osoba = osoba;
	}

	public boolean isAdmin() {
		return this.admin;
	}

	public void setAdmin(boolean admin) {
		this.admin = admin;
	}

	public String getNivoPristupa() {
		return this.nivoPristupa;
	}

	public void setNivoPristupa(String nivoPristupa) {
		this.nivoPristupa = nivoPristupa;
	}

}
