package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * NastavnikPredmetId generated by hbm2java
 */
public class NastavnikPredmetId implements java.io.Serializable {

	private int nastavnik;
	private int akademskaGodina;
	private int predmet;

	public NastavnikPredmetId() {
	}

	public NastavnikPredmetId(int nastavnik, int akademskaGodina, int predmet) {
		this.nastavnik = nastavnik;
		this.akademskaGodina = akademskaGodina;
		this.predmet = predmet;
	}

	public int getNastavnik() {
		return this.nastavnik;
	}

	public void setNastavnik(int nastavnik) {
		this.nastavnik = nastavnik;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

}
