package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * NaucniStepen generated by hbm2java
 */
public class NaucniStepen implements java.io.Serializable {

	private Integer id;
	private String naziv;
	private String titula;
	private Set<Osoba> osobas = new HashSet<Osoba>(0);

	public NaucniStepen() {
	}

	public NaucniStepen(String naziv, String titula) {
		this.naziv = naziv;
		this.titula = titula;
	}

	public NaucniStepen(String naziv, String titula, Set<Osoba> osobas) {
		this.naziv = naziv;
		this.titula = titula;
		this.osobas = osobas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public String getTitula() {
		return this.titula;
	}

	public void setTitula(String titula) {
		this.titula = titula;
	}

	public Set<Osoba> getOsobas() {
		return this.osobas;
	}

	public void setOsobas(Set<Osoba> osobas) {
		this.osobas = osobas;
	}

}
