package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Odluka generated by hbm2java
 */
public class Odluka implements java.io.Serializable {

	private Integer id;
	private Osoba osoba;
	private Date datum;
	private String brojProtokola;
	private Set<KonacnaOcjena> konacnaOcjenas = new HashSet<KonacnaOcjena>(0);

	public Odluka() {
	}

	public Odluka(Osoba osoba, Date datum, String brojProtokola) {
		this.osoba = osoba;
		this.datum = datum;
		this.brojProtokola = brojProtokola;
	}

	public Odluka(Osoba osoba, Date datum, String brojProtokola,
			Set<KonacnaOcjena> konacnaOcjenas) {
		this.osoba = osoba;
		this.datum = datum;
		this.brojProtokola = brojProtokola;
		this.konacnaOcjenas = konacnaOcjenas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Osoba getOsoba() {
		return this.osoba;
	}

	public void setOsoba(Osoba osoba) {
		this.osoba = osoba;
	}

	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	public String getBrojProtokola() {
		return this.brojProtokola;
	}

	public void setBrojProtokola(String brojProtokola) {
		this.brojProtokola = brojProtokola;
	}

	public Set<KonacnaOcjena> getKonacnaOcjenas() {
		return this.konacnaOcjenas;
	}

	public void setKonacnaOcjenas(Set<KonacnaOcjena> konacnaOcjenas) {
		this.konacnaOcjenas = konacnaOcjenas;
	}

}
