package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Osoba generated by hbm2java
 */
public class Osoba implements java.io.Serializable {

	private int id;
	private Mjesto mjestoByMjestoRodjenja;
	private StrucniStepen strucniStepen;
	private Mjesto mjestoByAdresaMjesto;
	private NaucniStepen naucniStepen;
	private String ime;
	private String prezime;
	private String imeoca;
	private String prezimeoca;
	private String imemajke;
	private String prezimemajke;
	private String spol;
	private String email;
	private String brindexa;
	private Date datumRodjenja;
	private Integer nacionalnost;
	private Integer drzavljanstvo;
	private boolean borackeKategorije;
	private String jmbg;
	private String adresa;
	private String telefon;
	private Integer kanton;
	private boolean trebaBrisati;
	private String slika;
	private boolean dijeteSehidaPoginulogBorca;
	private Set<Auth> auths = new HashSet<Auth>(0);
	private Set<Odluka> odlukas = new HashSet<Odluka>(0);
	private Set<BbPost> bbPosts = new HashSet<BbPost>(0);
	private Set<Ispitocjene> ispitocjenes = new HashSet<Ispitocjene>(0);
	private Set<Komentar> komentarsForStudent = new HashSet<Komentar>(0);
	private Set<Komponentebodovi> komponentebodovis = new HashSet<Komponentebodovi>(
			0);
	private Set<Cas> cases = new HashSet<Cas>(0);
	private Set<KonacnaOcjena> konacnaOcjenas = new HashSet<KonacnaOcjena>(0);
	private Set<Komentar> komentarsForNastavnik = new HashSet<Komentar>(0);
	private Set<BbTema> bbTemas = new HashSet<BbTema>(0);
	private Set<Kolizija> kolizijas = new HashSet<Kolizija>(0);
	private Set<Angazman> angazmans = new HashSet<Angazman>(0);
	private Set<NastavnikPredmet> nastavnikPredmets = new HashSet<NastavnikPredmet>(
			0);
	private Set<AutotestRezultat> autotestRezultats = new HashSet<AutotestRezultat>(
			0);
	private Set<BlClanak> blClanaks = new HashSet<BlClanak>(0);
	private Set<Labgrupa> labgrupas = new HashSet<Labgrupa>(0);
	private Set<Email> emails = new HashSet<Email>(0);

	public Osoba() {
	}

	public Osoba(int id, StrucniStepen strucniStepen,
			NaucniStepen naucniStepen, String ime, String prezime,
			String imeoca, String prezimeoca, String imemajke,
			String prezimemajke, String spol, String email, String brindexa,
			Date datumRodjenja, boolean borackeKategorije, String jmbg,
			String adresa, String telefon, boolean trebaBrisati, String slika,
			boolean dijeteSehidaPoginulogBorca) {
		this.id = id;
		this.strucniStepen = strucniStepen;
		this.naucniStepen = naucniStepen;
		this.ime = ime;
		this.prezime = prezime;
		this.imeoca = imeoca;
		this.prezimeoca = prezimeoca;
		this.imemajke = imemajke;
		this.prezimemajke = prezimemajke;
		this.spol = spol;
		this.email = email;
		this.brindexa = brindexa;
		this.datumRodjenja = datumRodjenja;
		this.borackeKategorije = borackeKategorije;
		this.jmbg = jmbg;
		this.adresa = adresa;
		this.telefon = telefon;
		this.trebaBrisati = trebaBrisati;
		this.slika = slika;
		this.dijeteSehidaPoginulogBorca = dijeteSehidaPoginulogBorca;
	}

	public Osoba(int id, Mjesto mjestoByMjestoRodjenja,
			StrucniStepen strucniStepen, Mjesto mjestoByAdresaMjesto,
			NaucniStepen naucniStepen, String ime, String prezime,
			String imeoca, String prezimeoca, String imemajke,
			String prezimemajke, String spol, String email, String brindexa,
			Date datumRodjenja, Integer nacionalnost, Integer drzavljanstvo,
			boolean borackeKategorije, String jmbg, String adresa,
			String telefon, Integer kanton, boolean trebaBrisati, String slika,
			boolean dijeteSehidaPoginulogBorca, Set<Auth> auths,
			Set<Odluka> odlukas, Set<BbPost> bbPosts,
			Set<Ispitocjene> ispitocjenes, Set<Komentar> komentarsForStudent,
			Set<Komponentebodovi> komponentebodovis, Set<Cas> cases,
			Set<KonacnaOcjena> konacnaOcjenas,
			Set<Komentar> komentarsForNastavnik, Set<BbTema> bbTemas,
			Set<Kolizija> kolizijas, Set<Angazman> angazmans,
			Set<NastavnikPredmet> nastavnikPredmets,
			Set<AutotestRezultat> autotestRezultats, Set<BlClanak> blClanaks,
			Set<Labgrupa> labgrupas, Set<Email> emails) {
		this.id = id;
		this.mjestoByMjestoRodjenja = mjestoByMjestoRodjenja;
		this.strucniStepen = strucniStepen;
		this.mjestoByAdresaMjesto = mjestoByAdresaMjesto;
		this.naucniStepen = naucniStepen;
		this.ime = ime;
		this.prezime = prezime;
		this.imeoca = imeoca;
		this.prezimeoca = prezimeoca;
		this.imemajke = imemajke;
		this.prezimemajke = prezimemajke;
		this.spol = spol;
		this.email = email;
		this.brindexa = brindexa;
		this.datumRodjenja = datumRodjenja;
		this.nacionalnost = nacionalnost;
		this.drzavljanstvo = drzavljanstvo;
		this.borackeKategorije = borackeKategorije;
		this.jmbg = jmbg;
		this.adresa = adresa;
		this.telefon = telefon;
		this.kanton = kanton;
		this.trebaBrisati = trebaBrisati;
		this.slika = slika;
		this.dijeteSehidaPoginulogBorca = dijeteSehidaPoginulogBorca;
		this.auths = auths;
		this.odlukas = odlukas;
		this.bbPosts = bbPosts;
		this.ispitocjenes = ispitocjenes;
		this.komentarsForStudent = komentarsForStudent;
		this.komponentebodovis = komponentebodovis;
		this.cases = cases;
		this.konacnaOcjenas = konacnaOcjenas;
		this.komentarsForNastavnik = komentarsForNastavnik;
		this.bbTemas = bbTemas;
		this.kolizijas = kolizijas;
		this.angazmans = angazmans;
		this.nastavnikPredmets = nastavnikPredmets;
		this.autotestRezultats = autotestRezultats;
		this.blClanaks = blClanaks;
		this.labgrupas = labgrupas;
		this.emails = emails;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Mjesto getMjestoByMjestoRodjenja() {
		return this.mjestoByMjestoRodjenja;
	}

	public void setMjestoByMjestoRodjenja(Mjesto mjestoByMjestoRodjenja) {
		this.mjestoByMjestoRodjenja = mjestoByMjestoRodjenja;
	}

	public StrucniStepen getStrucniStepen() {
		return this.strucniStepen;
	}

	public void setStrucniStepen(StrucniStepen strucniStepen) {
		this.strucniStepen = strucniStepen;
	}

	public Mjesto getMjestoByAdresaMjesto() {
		return this.mjestoByAdresaMjesto;
	}

	public void setMjestoByAdresaMjesto(Mjesto mjestoByAdresaMjesto) {
		this.mjestoByAdresaMjesto = mjestoByAdresaMjesto;
	}

	public NaucniStepen getNaucniStepen() {
		return this.naucniStepen;
	}

	public void setNaucniStepen(NaucniStepen naucniStepen) {
		this.naucniStepen = naucniStepen;
	}

	public String getIme() {
		return this.ime;
	}

	public void setIme(String ime) {
		this.ime = ime;
	}

	public String getPrezime() {
		return this.prezime;
	}

	public void setPrezime(String prezime) {
		this.prezime = prezime;
	}

	public String getImeoca() {
		return this.imeoca;
	}

	public void setImeoca(String imeoca) {
		this.imeoca = imeoca;
	}

	public String getPrezimeoca() {
		return this.prezimeoca;
	}

	public void setPrezimeoca(String prezimeoca) {
		this.prezimeoca = prezimeoca;
	}

	public String getImemajke() {
		return this.imemajke;
	}

	public void setImemajke(String imemajke) {
		this.imemajke = imemajke;
	}

	public String getPrezimemajke() {
		return this.prezimemajke;
	}

	public void setPrezimemajke(String prezimemajke) {
		this.prezimemajke = prezimemajke;
	}

	public String getSpol() {
		return this.spol;
	}

	public void setSpol(String spol) {
		this.spol = spol;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getBrindexa() {
		return this.brindexa;
	}

	public void setBrindexa(String brindexa) {
		this.brindexa = brindexa;
	}

	public Date getDatumRodjenja() {
		return this.datumRodjenja;
	}

	public void setDatumRodjenja(Date datumRodjenja) {
		this.datumRodjenja = datumRodjenja;
	}

	public Integer getNacionalnost() {
		return this.nacionalnost;
	}

	public void setNacionalnost(Integer nacionalnost) {
		this.nacionalnost = nacionalnost;
	}

	public Integer getDrzavljanstvo() {
		return this.drzavljanstvo;
	}

	public void setDrzavljanstvo(Integer drzavljanstvo) {
		this.drzavljanstvo = drzavljanstvo;
	}

	public boolean isBorackeKategorije() {
		return this.borackeKategorije;
	}

	public void setBorackeKategorije(boolean borackeKategorije) {
		this.borackeKategorije = borackeKategorije;
	}

	public String getJmbg() {
		return this.jmbg;
	}

	public void setJmbg(String jmbg) {
		this.jmbg = jmbg;
	}

	public String getAdresa() {
		return this.adresa;
	}

	public void setAdresa(String adresa) {
		this.adresa = adresa;
	}

	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	public Integer getKanton() {
		return this.kanton;
	}

	public void setKanton(Integer kanton) {
		this.kanton = kanton;
	}

	public boolean isTrebaBrisati() {
		return this.trebaBrisati;
	}

	public void setTrebaBrisati(boolean trebaBrisati) {
		this.trebaBrisati = trebaBrisati;
	}

	public String getSlika() {
		return this.slika;
	}

	public void setSlika(String slika) {
		this.slika = slika;
	}

	public boolean isDijeteSehidaPoginulogBorca() {
		return this.dijeteSehidaPoginulogBorca;
	}

	public void setDijeteSehidaPoginulogBorca(boolean dijeteSehidaPoginulogBorca) {
		this.dijeteSehidaPoginulogBorca = dijeteSehidaPoginulogBorca;
	}

	public Set<Auth> getAuths() {
		return this.auths;
	}

	public void setAuths(Set<Auth> auths) {
		this.auths = auths;
	}

	public Set<Odluka> getOdlukas() {
		return this.odlukas;
	}

	public void setOdlukas(Set<Odluka> odlukas) {
		this.odlukas = odlukas;
	}

	public Set<BbPost> getBbPosts() {
		return this.bbPosts;
	}

	public void setBbPosts(Set<BbPost> bbPosts) {
		this.bbPosts = bbPosts;
	}

	public Set<Ispitocjene> getIspitocjenes() {
		return this.ispitocjenes;
	}

	public void setIspitocjenes(Set<Ispitocjene> ispitocjenes) {
		this.ispitocjenes = ispitocjenes;
	}

	public Set<Komentar> getKomentarsForStudent() {
		return this.komentarsForStudent;
	}

	public void setKomentarsForStudent(Set<Komentar> komentarsForStudent) {
		this.komentarsForStudent = komentarsForStudent;
	}

	public Set<Komponentebodovi> getKomponentebodovis() {
		return this.komponentebodovis;
	}

	public void setKomponentebodovis(Set<Komponentebodovi> komponentebodovis) {
		this.komponentebodovis = komponentebodovis;
	}

	public Set<Cas> getCases() {
		return this.cases;
	}

	public void setCases(Set<Cas> cases) {
		this.cases = cases;
	}

	public Set<KonacnaOcjena> getKonacnaOcjenas() {
		return this.konacnaOcjenas;
	}

	public void setKonacnaOcjenas(Set<KonacnaOcjena> konacnaOcjenas) {
		this.konacnaOcjenas = konacnaOcjenas;
	}

	public Set<Komentar> getKomentarsForNastavnik() {
		return this.komentarsForNastavnik;
	}

	public void setKomentarsForNastavnik(Set<Komentar> komentarsForNastavnik) {
		this.komentarsForNastavnik = komentarsForNastavnik;
	}

	public Set<BbTema> getBbTemas() {
		return this.bbTemas;
	}

	public void setBbTemas(Set<BbTema> bbTemas) {
		this.bbTemas = bbTemas;
	}

	public Set<Kolizija> getKolizijas() {
		return this.kolizijas;
	}

	public void setKolizijas(Set<Kolizija> kolizijas) {
		this.kolizijas = kolizijas;
	}

	public Set<Angazman> getAngazmans() {
		return this.angazmans;
	}

	public void setAngazmans(Set<Angazman> angazmans) {
		this.angazmans = angazmans;
	}

	public Set<NastavnikPredmet> getNastavnikPredmets() {
		return this.nastavnikPredmets;
	}

	public void setNastavnikPredmets(Set<NastavnikPredmet> nastavnikPredmets) {
		this.nastavnikPredmets = nastavnikPredmets;
	}

	public Set<AutotestRezultat> getAutotestRezultats() {
		return this.autotestRezultats;
	}

	public void setAutotestRezultats(Set<AutotestRezultat> autotestRezultats) {
		this.autotestRezultats = autotestRezultats;
	}

	public Set<BlClanak> getBlClanaks() {
		return this.blClanaks;
	}

	public void setBlClanaks(Set<BlClanak> blClanaks) {
		this.blClanaks = blClanaks;
	}

	public Set<Labgrupa> getLabgrupas() {
		return this.labgrupas;
	}

	public void setLabgrupas(Set<Labgrupa> labgrupas) {
		this.labgrupas = labgrupas;
	}

	public Set<Email> getEmails() {
		return this.emails;
	}

	public void setEmails(Set<Email> emails) {
		this.emails = emails;
	}

}
