package ba.unsa.etf.zamger.beans;

// Generated May 26, 2015 12:09:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Studij generated by hbm2java
 */
public class Studij implements java.io.Serializable {

	private Integer id;
	private String naziv;
	private String nazivEn;
	private int zavrsniSemestar;
	private int institucija;
	private String kratkinaziv;
	private boolean mogucUpis;
	private int tipstudija;
	private int preduslov;
	private Set<Ponudakursa> ponudakursas = new HashSet<Ponudakursa>(0);

	public Studij() {
	}

	public Studij(String naziv, String nazivEn, int zavrsniSemestar,
			int institucija, String kratkinaziv, boolean mogucUpis,
			int tipstudija, int preduslov) {
		this.naziv = naziv;
		this.nazivEn = nazivEn;
		this.zavrsniSemestar = zavrsniSemestar;
		this.institucija = institucija;
		this.kratkinaziv = kratkinaziv;
		this.mogucUpis = mogucUpis;
		this.tipstudija = tipstudija;
		this.preduslov = preduslov;
	}

	public Studij(String naziv, String nazivEn, int zavrsniSemestar,
			int institucija, String kratkinaziv, boolean mogucUpis,
			int tipstudija, int preduslov, Set<Ponudakursa> ponudakursas) {
		this.naziv = naziv;
		this.nazivEn = nazivEn;
		this.zavrsniSemestar = zavrsniSemestar;
		this.institucija = institucija;
		this.kratkinaziv = kratkinaziv;
		this.mogucUpis = mogucUpis;
		this.tipstudija = tipstudija;
		this.preduslov = preduslov;
		this.ponudakursas = ponudakursas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public String getNazivEn() {
		return this.nazivEn;
	}

	public void setNazivEn(String nazivEn) {
		this.nazivEn = nazivEn;
	}

	public int getZavrsniSemestar() {
		return this.zavrsniSemestar;
	}

	public void setZavrsniSemestar(int zavrsniSemestar) {
		this.zavrsniSemestar = zavrsniSemestar;
	}

	public int getInstitucija() {
		return this.institucija;
	}

	public void setInstitucija(int institucija) {
		this.institucija = institucija;
	}

	public String getKratkinaziv() {
		return this.kratkinaziv;
	}

	public void setKratkinaziv(String kratkinaziv) {
		this.kratkinaziv = kratkinaziv;
	}

	public boolean isMogucUpis() {
		return this.mogucUpis;
	}

	public void setMogucUpis(boolean mogucUpis) {
		this.mogucUpis = mogucUpis;
	}

	public int getTipstudija() {
		return this.tipstudija;
	}

	public void setTipstudija(int tipstudija) {
		this.tipstudija = tipstudija;
	}

	public int getPreduslov() {
		return this.preduslov;
	}

	public void setPreduslov(int preduslov) {
		this.preduslov = preduslov;
	}

	public Set<Ponudakursa> getPonudakursas() {
		return this.ponudakursas;
	}

	public void setPonudakursas(Set<Ponudakursa> ponudakursas) {
		this.ponudakursas = ponudakursas;
	}

}
