language: php
php:
    - 5.5

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo apt-get autoremove
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'short_open_tag = On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo service apache2 restart
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  #- mysql -e 'create database yourcashflowtest;'
  #- mysql -e "source ~/build/zamger/test/_data/dump.sql;" -uroot
  - mysql -u root -e  'show databases;'
  # mysql -u root -e "GRANT ALL PRIVILEGES ON zamger.* to zamger@localhost identified by '1A2s3D4f';
  # mysql FLUSH PRVILEGES;"
  - 
  #- mysql -u root yourcashflowtest < ./build/setup/schema.sql
  #- mysql -u root yourcashflowtest < ./build/setup/category.sql
  #- mysql -u root yourcashflowtest < ./build/setup/account.sql
  #- cp -f build/global.php ./config/autoload/global.php
  #- cp -f build/test.php ./config/autoload/test.php
  #- cp -f build/local.php ./config/autoload/local.php
  #- composer install
  - mkdir /home/zamger
  - mkdir /home/zamger/tmp
  - mkdir /home/zamger/zadace
  - mkdir /home/zamger/projekti
  - mkdir /home/zamger/slike

before_install:
  - ls
  - cat zamger-dump.sql
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON zamger.* to zamger@localhost identified by '1A2s3D4f';FLUSH PRIVILEGES;"
  - mysql -e "create database IF NOT EXISTS zamger DEFAULT CHARSET=utf8 COLLATE=utf8_slovenian_ci;"
  # mysql -u root -e "GRANT ALL PRIVILEGES ON zamger.* to zamger@localhost identified by '1A2s3D4f';
  # mysql -e "use zamger;source zamger-dump.sql;" -uroot
  - mysql zamger -u zamger -p1A2s3D4f --default_character_set utf8 <zamger-dump.sql
  # cat ~/build/zamger/tests/_data/dump.sql
  - cat tests/_data/dump.sql
  # cat zamger/tests/_data/dump.sql
   
addons:
  sauce_connect: true

script:
  - php codecept.phar run --steps --html  #testovi
  
env:
  global: #sauce connect auth details
   # secure: kc0Uu+ClHekIZeGh55aN96aan6HtXh4XmvwhM1vkaaZCYuEp6+hcG6El5vdRUB5GxbosV3xznOlc/rL0JdjYxASzoppg5z9QmEsq2oKvdDgn06R2jAmQvXQxfXgZFjTjr/vUCoERROOziWyR2xsOweOlTtZ2oGE8gkDIpHVEmKE=
    #- secure: CZSrP4WhQ48DtgkrN+NIt1ig4+pOGNvDgFSSl8ILT+VbUUQrbw6UswI9djTOiIF9OA4xuWLqUEKlqPSOOrRA3cOUUxWIFVyNDoygBvwWIPHICqrTiN4vDB3ZNj02VvwIOfNALeUTREV155sUdx0WC3c3FVjVsioktgOp1dMaTVM=  

after_script: