language: php
php:
    - 5.5
#    - 5.6

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi sendemail
  - sudo apt-get autoremove
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'short_open_tag = On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'display_errors = Off'>> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo service apache2 restart
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  - mysql -u root -e  'show databases;'
  
  - sudo mkdir /home/zamger
  - sudo mkdir /home/zamger/tmp
  - sudo mkdir /home/zamger/zadace
  - sudo mkdir /home/zamger/projekti
  - sudo mkdir /home/zamger/slike
  - ls 
  - composer update
  - sudo ps aux | grep apache

before_install:
  - ls
  - cat zamger-dump.sql
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "create database IF NOT EXISTS zamger DEFAULT CHARSET=utf8 COLLATE=utf8_slovenian_ci;"
  - mysql -e "GRANT ALL PRIVILEGES ON zamger.* to zamger@localhost identified by '1A2s3D4f';FLUSH PRIVILEGES;" -uroot
  
  - mysql zamger -u zamger -p1A2s3D4f --default_character_set utf8 <zamger-dump.sql
  # cat ~/build/zamger/tests/_data/dump.sql
  - cat tests/_data/dump.sql
  # cat zamger/tests/_data/dump.sql
   
addons:
  sauce_connect: true

script:
#  - vendor/bin/codecept run  --env $BW --steps --debug # svi testovi
#    - vendor/bin/codecept run --group student  --env $BW --steps --debug # grupa student
    - vendor/bin/codecept run --group bugs  --env $BW --steps --debug #stari bugovi
    
  
env:
  global:
    - secure: b9MCGuVXwObx0n8bg7urCYBmQGiYYTKxf+PGDdSR2ydF5uxjxikujrI8wKdG3VrkyvUL/3NOwfVCHLtJ2mYTIcCYK895Kiy+QQb6RjaOGc2C3e0td0RcgO4RSbskrtf7qVi5g9/jwU/2+MdwQZNM2028iQvd3QGcYyk8vc3NssA=
    - secure: oskOJptPiXUw2VyeFSa7f3niYt25qOTi/uJBGWmjfyJDgnGUU2v183hb4aIXNDWJVj5+ylXnaLgrjP6y3nXSFxPDJn6U4umVlReXs39gDN8jdWVOJYgUoGEMCTh7ZIfx/LMfPs44+fXwOxYLugdkFRWqtt2Q+9GSq4cnbQo/vtU=
    - SELENIUM_HOST: $SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com
    - sauceTunel: $TRAVIS_JOB_NUMBER
    - projekat: 'zamger'
    - buildTags: $projekat
    - buildName: $TRAVIS_JOB_NUMBER-$TRAVIS_REPO_SLUG[$TRAVIS_BRANCH]:$TRAVIS_COMMIT
  matrix:
      # dostupne platforme https://docs.saucelabs.com/reference/platforms-configurator/#/ 
      # dodati u acceptance.suite.yml postavke za novi browser

      - OS=linux BW=firefox 
      - OS=linux BW=chrome
      - OS='Windows 8' BW=IE
      - OS='OS X 10.10' BW=safari  # 
  allow_failures:
      - OS='OS X 10.10' BW=safari
      - OS='Windows 8' BW=IE
        
     
     
notifications:
    email:
        recipients:
            - huma.milisic@gmail.com
        on_success: always
        on_failure: always
        
branches:
    only:
        - master
        
#before_install:
#    
#install:
#    
#before_script:
#    
#script:
#    
#after_success:
#
#after_failure:
#    
after_script:
    - cat tests/_output/report.html
#    - sendemail -t huma.milisic@gmail.com -m "Output" -a file1.jpg file2.zip
    
#before_deploy:
#
#deploy:
#    
#after_deploy:


