language: php
php:
    - 5.5
#env:
#    - OS : 'Linux'
#    - OS : 'Windows 8'
#    - OS : 'Windows XP'

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo apt-get autoremove
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'short_open_tag = On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'display_errors = Off'>> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo service apache2 restart
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  #- mysql -e 'create database yourcashflowtest;'
  #- mysql -e "source ~/build/zamger/test/_data/dump.sql;" -uroot
  - mysql -u root -e  'show databases;'
  # mysql -u root -e "GRANT ALL PRIVILEGES ON zamger.* to zamger@localhost identified by '1A2s3D4f';
  # mysql FLUSH PRVILEGES;"
  - 
  #- mysql -u root yourcashflowtest < ./build/setup/schema.sql
  #- mysql -u root yourcashflowtest < ./build/setup/category.sql
  #- mysql -u root yourcashflowtest < ./build/setup/account.sql
  #- cp -f build/global.php ./config/autoload/global.php
  #- cp -f build/test.php ./config/autoload/test.php
  #- cp -f build/local.php ./config/autoload/local.php
  #- composer install
  - sudo mkdir /home/zamger
  - sudo mkdir /home/zamger/tmp
  - sudo mkdir /home/zamger/zadace
  - sudo mkdir /home/zamger/projekti
  - sudo mkdir /home/zamger/slike
  - ls 
#  - composer update
  - sudo ps aux | grep apache

before_install:
  #- export SELENIUM_HOST=$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com
  - ls
  - cat zamger-dump.sql
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "create database IF NOT EXISTS zamger DEFAULT CHARSET=utf8 COLLATE=utf8_slovenian_ci;"
  - mysql -e "GRANT ALL PRIVILEGES ON zamger.* to zamger@localhost identified by '1A2s3D4f';FLUSH PRIVILEGES;" -uroot
  
  - mysql zamger -u zamger -p1A2s3D4f --default_character_set utf8 <zamger-dump.sql
  # cat ~/build/zamger/tests/_data/dump.sql
  - cat tests/_data/dump.sql
  # cat zamger/tests/_data/dump.sql
   
addons:
  sauce_connect: true

script:
  - php codecept.phar run --steps --html --debug  #testovi
  
env:
  global:    
    - secure: knJ4vH4be2RRq+u3V3QWZKw8yVzkP3WQT4RqRxL/z0qKMoB9hILzMv3r5tEOjANBEa+wfx6Oyw/I5gt2L33gF+XWyv1IE1VjbxMdYl8bSHSg+fyRP7go4ErbrXbWrlIddvt7Egx55GVp8ulveY49kzytq4YJ1UdCpOKe7rPyKtk=
    - secure: DUfZFO0FZzP2TUOOTijbKAIOTnzM6yWsGPv90CikBOHNNmEwhlvxjxG6T1EFr5AywrStIzKUym5GdSZPnvxcECFRXWsXG1RTt5rXTNPJbpsPg7Pdapeie1vS1ylPlYYhEGrwjhjeancA/raAey63Q2qnS1HhQmEbSo8wF9izC34=
    - SELENIUM_HOST: $SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com
    - sauceTunel: $TRAVIS_JOB_NUMBER
    - projekat: 'zamger'
    - buildTags: $projekat
    - buildName: $projekat:$TRAVIS_JOB_NUMBER
  matrix:
    include:
        env: OS = linux,
        env: OS = windows