language: php
php:
  - 5.4
  
install:
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar  

before_script:
  - echo "before script"
  
script:
  - php codecept run --steps # self tests
