package ba.unsa.etf.zamger.beans;

// Generated May 30, 2015 7:27:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * AclId generated by hbm2java
 */
public class AclId implements java.io.Serializable {

	private int osoba;
	private String aclTip;
	private int predikat1;
	private int predikat2;
	private int predikat3;

	public AclId() {
	}

	public AclId(int osoba, String aclTip, int predikat1, int predikat2,
			int predikat3) {
		this.osoba = osoba;
		this.aclTip = aclTip;
		this.predikat1 = predikat1;
		this.predikat2 = predikat2;
		this.predikat3 = predikat3;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public String getAclTip() {
		return this.aclTip;
	}

	public void setAclTip(String aclTip) {
		this.aclTip = aclTip;
	}

	public int getPredikat1() {
		return this.predikat1;
	}

	public void setPredikat1(int predikat1) {
		this.predikat1 = predikat1;
	}

	public int getPredikat2() {
		return this.predikat2;
	}

	public void setPredikat2(int predikat2) {
		this.predikat2 = predikat2;
	}

	public int getPredikat3() {
		return this.predikat3;
	}

	public void setPredikat3(int predikat3) {
		this.predikat3 = predikat3;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AclId))
			return false;
		AclId castOther = (AclId) other;

		return (this.getOsoba() == castOther.getOsoba())
				&& ((this.getAclTip() == castOther.getAclTip()) || (this
						.getAclTip() != null && castOther.getAclTip() != null && this
						.getAclTip().equals(castOther.getAclTip())))
				&& (this.getPredikat1() == castOther.getPredikat1())
				&& (this.getPredikat2() == castOther.getPredikat2())
				&& (this.getPredikat3() == castOther.getPredikat3());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOsoba();
		result = 37 * result
				+ (getAclTip() == null ? 0 : this.getAclTip().hashCode());
		result = 37 * result + this.getPredikat1();
		result = 37 * result + this.getPredikat2();
		result = 37 * result + this.getPredikat3();
		return result;
	}

}
