package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * AclMembersId generated by hbm2java
 */
public class AclMembersId implements java.io.Serializable {

	private int acl;
	private int osoba;

	public AclMembersId() {
	}

	public AclMembersId(int acl, int osoba) {
		this.acl = acl;
		this.osoba = osoba;
	}

	public int getAcl() {
		return this.acl;
	}

	public void setAcl(int acl) {
		this.acl = acl;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AclMembersId))
			return false;
		AclMembersId castOther = (AclMembersId) other;

		return (this.getAcl() == castOther.getAcl())
				&& (this.getOsoba() == castOther.getOsoba());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAcl();
		result = 37 * result + this.getOsoba();
		return result;
	}

}
