package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * AclMembers generated by hbm2java
 */
public class AclMembers implements java.io.Serializable {

	private AclMembersId id;

	public AclMembers() {
	}

	public AclMembers(AclMembersId id) {
		this.id = id;
	}

	public AclMembersId getId() {
		return this.id;
	}

	public void setId(AclMembersId id) {
		this.id = id;
	}

}
