package ba.unsa.etf.zamger.beans;

// Generated May 30, 2015 7:27:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AclTip generated by hbm2java
 */
public class AclTip implements java.io.Serializable {

	private String naziv;
	private byte brPredikata;
	private String predikat1;
	private String predikat2;
	private String predikat3;
	private Set<Acl> acls = new HashSet<Acl>(0);

	public AclTip() {
	}

	public AclTip(String naziv, byte brPredikata, String predikat1,
			String predikat2, String predikat3) {
		this.naziv = naziv;
		this.brPredikata = brPredikata;
		this.predikat1 = predikat1;
		this.predikat2 = predikat2;
		this.predikat3 = predikat3;
	}

	public AclTip(String naziv, byte brPredikata, String predikat1,
			String predikat2, String predikat3, Set<Acl> acls) {
		this.naziv = naziv;
		this.brPredikata = brPredikata;
		this.predikat1 = predikat1;
		this.predikat2 = predikat2;
		this.predikat3 = predikat3;
		this.acls = acls;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public byte getBrPredikata() {
		return this.brPredikata;
	}

	public void setBrPredikata(byte brPredikata) {
		this.brPredikata = brPredikata;
	}

	public String getPredikat1() {
		return this.predikat1;
	}

	public void setPredikat1(String predikat1) {
		this.predikat1 = predikat1;
	}

	public String getPredikat2() {
		return this.predikat2;
	}

	public void setPredikat2(String predikat2) {
		this.predikat2 = predikat2;
	}

	public String getPredikat3() {
		return this.predikat3;
	}

	public void setPredikat3(String predikat3) {
		this.predikat3 = predikat3;
	}

	public Set<Acl> getAcls() {
		return this.acls;
	}

	public void setAcls(Set<Acl> acls) {
		this.acls = acls;
	}

}
