package ba.unsa.etf.zamger.beans;

// Generated May 30, 2015 7:27:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * AclUrl generated by hbm2java
 */
public class AclUrl implements java.io.Serializable {

	private AclUrlId id;

	public AclUrl() {
	}

	public AclUrl(AclUrlId id) {
		this.id = id;
	}

	public AclUrlId getId() {
		return this.id;
	}

	public void setId(AclUrlId id) {
		this.id = id;
	}

}
