package ba.unsa.etf.zamger.beans;

// Generated May 30, 2015 7:27:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * AclUrlId generated by hbm2java
 */
public class AclUrlId implements java.io.Serializable {

	private int osoba;
	private String url;

	public AclUrlId() {
	}

	public AclUrlId(int osoba, String url) {
		this.osoba = osoba;
		this.url = url;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AclUrlId))
			return false;
		AclUrlId castOther = (AclUrlId) other;

		return (this.getOsoba() == castOther.getOsoba())
				&& ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null
						&& castOther.getUrl() != null && this.getUrl().equals(
						castOther.getUrl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOsoba();
		result = 37 * result
				+ (getUrl() == null ? 0 : this.getUrl().hashCode());
		return result;
	}

}
