package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * AkademskaGodinaPredmet generated by hbm2java
 */
public class AkademskaGodinaPredmet implements java.io.Serializable {

	private AkademskaGodinaPredmetId id;
	private Predmet predmet;
	private AkademskaGodina akademskaGodina;
	private int tippredmeta;

	public AkademskaGodinaPredmet() {
	}

	public AkademskaGodinaPredmet(AkademskaGodinaPredmetId id, Predmet predmet,
			AkademskaGodina akademskaGodina, int tippredmeta) {
		this.id = id;
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.tippredmeta = tippredmeta;
	}

	public AkademskaGodinaPredmetId getId() {
		return this.id;
	}

	public void setId(AkademskaGodinaPredmetId id) {
		this.id = id;
	}

	public Predmet getPredmet() {
		return this.predmet;
	}

	public void setPredmet(Predmet predmet) {
		this.predmet = predmet;
	}

	public AkademskaGodina getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(AkademskaGodina akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public int getTippredmeta() {
		return this.tippredmeta;
	}

	public void setTippredmeta(int tippredmeta) {
		this.tippredmeta = tippredmeta;
	}

}
