package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * AkademskaGodinaPredmetId generated by hbm2java
 */
public class AkademskaGodinaPredmetId implements java.io.Serializable {

	private int akademskaGodina;
	private int predmet;

	public AkademskaGodinaPredmetId() {
	}

	public AkademskaGodinaPredmetId(int akademskaGodina, int predmet) {
		this.akademskaGodina = akademskaGodina;
		this.predmet = predmet;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AkademskaGodinaPredmetId))
			return false;
		AkademskaGodinaPredmetId castOther = (AkademskaGodinaPredmetId) other;

		return (this.getAkademskaGodina() == castOther.getAkademskaGodina())
				&& (this.getPredmet() == castOther.getPredmet());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAkademskaGodina();
		result = 37 * result + this.getPredmet();
		return result;
	}

}
