package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * AlumniAnketaDodatak generated by hbm2java
 */
public class AlumniAnketaDodatak implements java.io.Serializable {

	private Integer id;
	private int alumniAnketa;
	private String sta;
	private String naziv;
	private int vrijednost;

	public AlumniAnketaDodatak() {
	}

	public AlumniAnketaDodatak(int alumniAnketa, String sta, String naziv,
			int vrijednost) {
		this.alumniAnketa = alumniAnketa;
		this.sta = sta;
		this.naziv = naziv;
		this.vrijednost = vrijednost;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getAlumniAnketa() {
		return this.alumniAnketa;
	}

	public void setAlumniAnketa(int alumniAnketa) {
		this.alumniAnketa = alumniAnketa;
	}

	public String getSta() {
		return this.sta;
	}

	public void setSta(String sta) {
		this.sta = sta;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public int getVrijednost() {
		return this.vrijednost;
	}

	public void setVrijednost(int vrijednost) {
		this.vrijednost = vrijednost;
	}

}
