package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * AlumniAnketaMailovi generated by hbm2java
 */
public class AlumniAnketaMailovi implements java.io.Serializable {

	private int osoba;
	private String email;
	private String kod;

	public AlumniAnketaMailovi() {
	}

	public AlumniAnketaMailovi(int osoba, String email, String kod) {
		this.osoba = osoba;
		this.email = email;
		this.kod = kod;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getKod() {
		return this.kod;
	}

	public void setKod(String kod) {
		this.kod = kod;
	}

}
