package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AngazmanStatus generated by hbm2java
 */
public class AngazmanStatus implements java.io.Serializable {

	private Integer id;
	private String naziv;
	private Set<Angazman> angazmans = new HashSet<Angazman>(0);

	public AngazmanStatus() {
	}

	public AngazmanStatus(String naziv) {
		this.naziv = naziv;
	}

	public AngazmanStatus(String naziv, Set<Angazman> angazmans) {
		this.naziv = naziv;
		this.angazmans = angazmans;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public Set<Angazman> getAngazmans() {
		return this.angazmans;
	}

	public void setAngazmans(Set<Angazman> angazmans) {
		this.angazmans = angazmans;
	}

}
