package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * AngazmanId generated by hbm2java
 */
public class AngazmanId implements java.io.Serializable {

	private int predmet;
	private int akademskaGodina;
	private int osoba;

	public AngazmanId() {
	}

	public AngazmanId(int predmet, int akademskaGodina, int osoba) {
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.osoba = osoba;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AngazmanId))
			return false;
		AngazmanId castOther = (AngazmanId) other;

		return (this.getPredmet() == castOther.getPredmet())
				&& (this.getAkademskaGodina() == castOther.getAkademskaGodina())
				&& (this.getOsoba() == castOther.getOsoba());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPredmet();
		result = 37 * result + this.getAkademskaGodina();
		result = 37 * result + this.getOsoba();
		return result;
	}

}
