package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * AnketaStudentZavrsioId generated by hbm2java
 */
public class AnketaStudentZavrsioId implements java.io.Serializable {

	private int student;
	private int predmet;
	private int akademskaGodina;
	private int anketa;

	public AnketaStudentZavrsioId() {
	}

	public AnketaStudentZavrsioId(int student, int predmet,
			int akademskaGodina, int anketa) {
		this.student = student;
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.anketa = anketa;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public int getAnketa() {
		return this.anketa;
	}

	public void setAnketa(int anketa) {
		this.anketa = anketa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnketaStudentZavrsioId))
			return false;
		AnketaStudentZavrsioId castOther = (AnketaStudentZavrsioId) other;

		return (this.getStudent() == castOther.getStudent())
				&& (this.getPredmet() == castOther.getPredmet())
				&& (this.getAkademskaGodina() == castOther.getAkademskaGodina())
				&& (this.getAnketa() == castOther.getAnketa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudent();
		result = 37 * result + this.getPredmet();
		result = 37 * result + this.getAkademskaGodina();
		result = 37 * result + this.getAnketa();
		return result;
	}

}
