package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * AnketaOdgovorIzboriId generated by hbm2java
 */
public class AnketaOdgovorIzboriId implements java.io.Serializable {

	private int rezultat;
	private int pitanje;
	private int izborId;

	public AnketaOdgovorIzboriId() {
	}

	public AnketaOdgovorIzboriId(int rezultat, int pitanje, int izborId) {
		this.rezultat = rezultat;
		this.pitanje = pitanje;
		this.izborId = izborId;
	}

	public int getRezultat() {
		return this.rezultat;
	}

	public void setRezultat(int rezultat) {
		this.rezultat = rezultat;
	}

	public int getPitanje() {
		return this.pitanje;
	}

	public void setPitanje(int pitanje) {
		this.pitanje = pitanje;
	}

	public int getIzborId() {
		return this.izborId;
	}

	public void setIzborId(int izborId) {
		this.izborId = izborId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnketaOdgovorIzboriId))
			return false;
		AnketaOdgovorIzboriId castOther = (AnketaOdgovorIzboriId) other;

		return (this.getRezultat() == castOther.getRezultat())
				&& (this.getPitanje() == castOther.getPitanje())
				&& (this.getIzborId() == castOther.getIzborId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRezultat();
		result = 37 * result + this.getPitanje();
		result = 37 * result + this.getIzborId();
		return result;
	}

}
