package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * AnketaOdgovorText generated by hbm2java
 */
public class AnketaOdgovorText implements java.io.Serializable {

	private AnketaOdgovorTextId id;
	private AnketaPitanje anketaPitanje;
	private AnketaRezultat anketaRezultat;
	private String odgovor;

	public AnketaOdgovorText() {
	}

	public AnketaOdgovorText(AnketaOdgovorTextId id,
			AnketaPitanje anketaPitanje, AnketaRezultat anketaRezultat) {
		this.id = id;
		this.anketaPitanje = anketaPitanje;
		this.anketaRezultat = anketaRezultat;
	}

	public AnketaOdgovorText(AnketaOdgovorTextId id,
			AnketaPitanje anketaPitanje, AnketaRezultat anketaRezultat,
			String odgovor) {
		this.id = id;
		this.anketaPitanje = anketaPitanje;
		this.anketaRezultat = anketaRezultat;
		this.odgovor = odgovor;
	}

	public AnketaOdgovorTextId getId() {
		return this.id;
	}

	public void setId(AnketaOdgovorTextId id) {
		this.id = id;
	}

	public AnketaPitanje getAnketaPitanje() {
		return this.anketaPitanje;
	}

	public void setAnketaPitanje(AnketaPitanje anketaPitanje) {
		this.anketaPitanje = anketaPitanje;
	}

	public AnketaRezultat getAnketaRezultat() {
		return this.anketaRezultat;
	}

	public void setAnketaRezultat(AnketaRezultat anketaRezultat) {
		this.anketaRezultat = anketaRezultat;
	}

	public String getOdgovor() {
		return this.odgovor;
	}

	public void setOdgovor(String odgovor) {
		this.odgovor = odgovor;
	}

}
