package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * AnketaOdgovorDopisaniId generated by hbm2java
 */
public class AnketaOdgovorDopisaniId implements java.io.Serializable {

	private int rezultat;
	private int pitanje;

	public AnketaOdgovorDopisaniId() {
	}

	public AnketaOdgovorDopisaniId(int rezultat, int pitanje) {
		this.rezultat = rezultat;
		this.pitanje = pitanje;
	}

	public int getRezultat() {
		return this.rezultat;
	}

	public void setRezultat(int rezultat) {
		this.rezultat = rezultat;
	}

	public int getPitanje() {
		return this.pitanje;
	}

	public void setPitanje(int pitanje) {
		this.pitanje = pitanje;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnketaOdgovorDopisaniId))
			return false;
		AnketaOdgovorDopisaniId castOther = (AnketaOdgovorDopisaniId) other;

		return (this.getRezultat() == castOther.getRezultat())
				&& (this.getPitanje() == castOther.getPitanje());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRezultat();
		result = 37 * result + this.getPitanje();
		return result;
	}

}
