package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * AnketaPredmet generated by hbm2java
 */
public class AnketaPredmet implements java.io.Serializable {

	private AnketaPredmetId id;
	private Predmet predmet;
	private AkademskaGodina akademskaGodina;
	private AnketaAnketa anketaAnketa;

	public AnketaPredmet() {
	}

	public AnketaPredmet(AnketaPredmetId id, AkademskaGodina akademskaGodina,
			AnketaAnketa anketaAnketa) {
		this.id = id;
		this.akademskaGodina = akademskaGodina;
		this.anketaAnketa = anketaAnketa;
	}

	public AnketaPredmet(AnketaPredmetId id, Predmet predmet,
			AkademskaGodina akademskaGodina, AnketaAnketa anketaAnketa) {
		this.id = id;
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.anketaAnketa = anketaAnketa;
	}

	public AnketaPredmetId getId() {
		return this.id;
	}

	public void setId(AnketaPredmetId id) {
		this.id = id;
	}

	public Predmet getPredmet() {
		return this.predmet;
	}

	public void setPredmet(Predmet predmet) {
		this.predmet = predmet;
	}

	public AkademskaGodina getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(AkademskaGodina akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public AnketaAnketa getAnketaAnketa() {
		return this.anketaAnketa;
	}

	public void setAnketaAnketa(AnketaAnketa anketaAnketa) {
		this.anketaAnketa = anketaAnketa;
	}

}
