package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * AnketaStudentZavrsio generated by hbm2java
 */
public class AnketaStudentZavrsio implements java.io.Serializable {

	private AnketaStudentZavrsioId id;
	private String zavrsena;
	private int anketaRezultat;

	public AnketaStudentZavrsio() {
	}

	public AnketaStudentZavrsio(AnketaStudentZavrsioId id, String zavrsena,
			int anketaRezultat) {
		this.id = id;
		this.zavrsena = zavrsena;
		this.anketaRezultat = anketaRezultat;
	}

	public AnketaStudentZavrsioId getId() {
		return this.id;
	}

	public void setId(AnketaStudentZavrsioId id) {
		this.id = id;
	}

	public String getZavrsena() {
		return this.zavrsena;
	}

	public void setZavrsena(String zavrsena) {
		this.zavrsena = zavrsena;
	}

	public int getAnketaRezultat() {
		return this.anketaRezultat;
	}

	public void setAnketaRezultat(int anketaRezultat) {
		this.anketaRezultat = anketaRezultat;
	}

}
