package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import com.fasterxml.jackson.annotation.*;

/**
 * Auth generated by hbm2java
 */
public class Auth implements java.io.Serializable {

	private AuthId id;
	@JsonIgnore
	private Osoba osoba;
	private String password;
	private boolean admin;
	private String externalId;
	@JsonIgnore
	private String ime;
	@JsonIgnore
	private String prezime;
	@JsonIgnore
	private String email;
	@JsonIgnore
	private String brindexa;
	@JsonIgnore
	private boolean student;
	@JsonIgnore
	private boolean nastavnik;
	@JsonIgnore
	private boolean studentska;
	@JsonIgnore
	private boolean siteadmin;
	private boolean aktivan;
	private Date posljednjiPristup;

	public Auth() {
	}

	public Auth(AuthId id, Osoba osoba, String password, boolean admin,
			String externalId, String ime, String prezime, String email,
			String brindexa, boolean student, boolean nastavnik,
			boolean studentska, boolean siteadmin, boolean aktivan,
			Date posljednjiPristup) {
		this.id = id;
		this.osoba = osoba;
		this.password = password;
		this.admin = admin;
		this.externalId = externalId;
		this.ime = ime;
		this.prezime = prezime;
		this.email = email;
		this.brindexa = brindexa;
		this.student = student;
		this.nastavnik = nastavnik;
		this.studentska = studentska;
		this.siteadmin = siteadmin;
		this.aktivan = aktivan;
		this.posljednjiPristup = posljednjiPristup;
	}

	public AuthId getId() {
		return this.id;
	}

	public void setId(AuthId id) {
		this.id = id;
	}

	public Osoba getOsoba() {
		return this.osoba;
	}

	public void setOsoba(Osoba osoba) {
		this.osoba = osoba;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isAdmin() {
		return this.admin;
	}

	public void setAdmin(boolean admin) {
		this.admin = admin;
	}

	public String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	public String getIme() {
		return this.ime;
	}

	public void setIme(String ime) {
		this.ime = ime;
	}

	public String getPrezime() {
		return this.prezime;
	}

	public void setPrezime(String prezime) {
		this.prezime = prezime;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getBrindexa() {
		return this.brindexa;
	}

	public void setBrindexa(String brindexa) {
		this.brindexa = brindexa;
	}

	public boolean isStudent() {
		return this.student;
	}

	public void setStudent(boolean student) {
		this.student = student;
	}

	public boolean isNastavnik() {
		return this.nastavnik;
	}

	public void setNastavnik(boolean nastavnik) {
		this.nastavnik = nastavnik;
	}

	public boolean isStudentska() {
		return this.studentska;
	}

	public void setStudentska(boolean studentska) {
		this.studentska = studentska;
	}

	public boolean isSiteadmin() {
		return this.siteadmin;
	}

	public void setSiteadmin(boolean siteadmin) {
		this.siteadmin = siteadmin;
	}

	public boolean isAktivan() {
		return this.aktivan;
	}

	public void setAktivan(boolean aktivan) {
		this.aktivan = aktivan;
	}

	public Date getPosljednjiPristup() {
		return this.posljednjiPristup;
	}

	public void setPosljednjiPristup(Date posljednjiPristup) {
		this.posljednjiPristup = posljednjiPristup;
	}

}
