package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * AuthId generated by hbm2java
 */
public class AuthId implements java.io.Serializable {

	private int id;
	private String login;

	public AuthId() {
	}

	public AuthId(int id, String login) {
		this.id = id;
		this.login = login;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuthId))
			return false;
		AuthId castOther = (AuthId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getLogin() == castOther.getLogin()) || (this
						.getLogin() != null && castOther.getLogin() != null && this
						.getLogin().equals(castOther.getLogin())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getLogin() == null ? 0 : this.getLogin().hashCode());
		return result;
	}

}
