package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * AutotestReplace generated by hbm2java
 */
public class AutotestReplace implements java.io.Serializable {

	private Integer id;
	private Zadaca zadaca;
	private int zadatak;
	private String tip;
	private String specifikacija;
	private String zamijeni;

	public AutotestReplace() {
	}

	public AutotestReplace(Zadaca zadaca, int zadatak, String tip,
			String specifikacija, String zamijeni) {
		this.zadaca = zadaca;
		this.zadatak = zadatak;
		this.tip = tip;
		this.specifikacija = specifikacija;
		this.zamijeni = zamijeni;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Zadaca getZadaca() {
		return this.zadaca;
	}

	public void setZadaca(Zadaca zadaca) {
		this.zadaca = zadaca;
	}

	public int getZadatak() {
		return this.zadatak;
	}

	public void setZadatak(int zadatak) {
		this.zadatak = zadatak;
	}

	public String getTip() {
		return this.tip;
	}

	public void setTip(String tip) {
		this.tip = tip;
	}

	public String getSpecifikacija() {
		return this.specifikacija;
	}

	public void setSpecifikacija(String specifikacija) {
		this.specifikacija = specifikacija;
	}

	public String getZamijeni() {
		return this.zamijeni;
	}

	public void setZamijeni(String zamijeni) {
		this.zamijeni = zamijeni;
	}

}
