package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Autotest generated by hbm2java
 */
public class Autotest implements java.io.Serializable {

	private Integer id;
	private Zadaca zadaca;
	private int zadatak;
	private String kod;
	private String rezultat;
	private String altRezultat;
	private boolean fuzzy;
	private String globalScope;
	private String pozicijaGlobala;
	private String stdin;
	private byte partialMatch;
	private boolean aktivan;
	private boolean sakriven;

	public Autotest() {
	}

	public Autotest(Zadaca zadaca, int zadatak, String kod, String rezultat,
			String altRezultat, boolean fuzzy, String globalScope,
			String pozicijaGlobala, String stdin, byte partialMatch,
			boolean aktivan, boolean sakriven) {
		this.zadaca = zadaca;
		this.zadatak = zadatak;
		this.kod = kod;
		this.rezultat = rezultat;
		this.altRezultat = altRezultat;
		this.fuzzy = fuzzy;
		this.globalScope = globalScope;
		this.pozicijaGlobala = pozicijaGlobala;
		this.stdin = stdin;
		this.partialMatch = partialMatch;
		this.aktivan = aktivan;
		this.sakriven = sakriven;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Zadaca getZadaca() {
		return this.zadaca;
	}

	public void setZadaca(Zadaca zadaca) {
		this.zadaca = zadaca;
	}

	public int getZadatak() {
		return this.zadatak;
	}

	public void setZadatak(int zadatak) {
		this.zadatak = zadatak;
	}

	public String getKod() {
		return this.kod;
	}

	public void setKod(String kod) {
		this.kod = kod;
	}

	public String getRezultat() {
		return this.rezultat;
	}

	public void setRezultat(String rezultat) {
		this.rezultat = rezultat;
	}

	public String getAltRezultat() {
		return this.altRezultat;
	}

	public void setAltRezultat(String altRezultat) {
		this.altRezultat = altRezultat;
	}

	public boolean isFuzzy() {
		return this.fuzzy;
	}

	public void setFuzzy(boolean fuzzy) {
		this.fuzzy = fuzzy;
	}

	public String getGlobalScope() {
		return this.globalScope;
	}

	public void setGlobalScope(String globalScope) {
		this.globalScope = globalScope;
	}

	public String getPozicijaGlobala() {
		return this.pozicijaGlobala;
	}

	public void setPozicijaGlobala(String pozicijaGlobala) {
		this.pozicijaGlobala = pozicijaGlobala;
	}

	public String getStdin() {
		return this.stdin;
	}

	public void setStdin(String stdin) {
		this.stdin = stdin;
	}

	public byte getPartialMatch() {
		return this.partialMatch;
	}

	public void setPartialMatch(byte partialMatch) {
		this.partialMatch = partialMatch;
	}

	public boolean isAktivan() {
		return this.aktivan;
	}

	public void setAktivan(boolean aktivan) {
		this.aktivan = aktivan;
	}

	public boolean isSakriven() {
		return this.sakriven;
	}

	public void setSakriven(boolean sakriven) {
		this.sakriven = sakriven;
	}

}
