package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BbTema generated by hbm2java
 */
public class BbTema implements java.io.Serializable {

	private int id;
	private BbPost bbPostByPrviPost;
	private Osoba osoba;
	private BbPost bbPostByZadnjiPost;
	private Projekat projekat;
	private Date vrijeme;
	private int pregleda;
	private Set<BbPost> bbPosts = new HashSet<BbPost>(0);

	public BbTema() {
	}

	public BbTema(int id, BbPost bbPostByPrviPost, Osoba osoba,
			BbPost bbPostByZadnjiPost, Projekat projekat, Date vrijeme,
			int pregleda) {
		this.id = id;
		this.bbPostByPrviPost = bbPostByPrviPost;
		this.osoba = osoba;
		this.bbPostByZadnjiPost = bbPostByZadnjiPost;
		this.projekat = projekat;
		this.vrijeme = vrijeme;
		this.pregleda = pregleda;
	}

	public BbTema(int id, BbPost bbPostByPrviPost, Osoba osoba,
			BbPost bbPostByZadnjiPost, Projekat projekat, Date vrijeme,
			int pregleda, Set<BbPost> bbPosts) {
		this.id = id;
		this.bbPostByPrviPost = bbPostByPrviPost;
		this.osoba = osoba;
		this.bbPostByZadnjiPost = bbPostByZadnjiPost;
		this.projekat = projekat;
		this.vrijeme = vrijeme;
		this.pregleda = pregleda;
		this.bbPosts = bbPosts;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public BbPost getBbPostByPrviPost() {
		return this.bbPostByPrviPost;
	}

	public void setBbPostByPrviPost(BbPost bbPostByPrviPost) {
		this.bbPostByPrviPost = bbPostByPrviPost;
	}

	public Osoba getOsoba() {
		return this.osoba;
	}

	public void setOsoba(Osoba osoba) {
		this.osoba = osoba;
	}

	public BbPost getBbPostByZadnjiPost() {
		return this.bbPostByZadnjiPost;
	}

	public void setBbPostByZadnjiPost(BbPost bbPostByZadnjiPost) {
		this.bbPostByZadnjiPost = bbPostByZadnjiPost;
	}

	public Projekat getProjekat() {
		return this.projekat;
	}

	public void setProjekat(Projekat projekat) {
		this.projekat = projekat;
	}

	public Date getVrijeme() {
		return this.vrijeme;
	}

	public void setVrijeme(Date vrijeme) {
		this.vrijeme = vrijeme;
	}

	public int getPregleda() {
		return this.pregleda;
	}

	public void setPregleda(int pregleda) {
		this.pregleda = pregleda;
	}

	public Set<BbPost> getBbPosts() {
		return this.bbPosts;
	}

	public void setBbPosts(Set<BbPost> bbPosts) {
		this.bbPosts = bbPosts;
	}

}
