package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BlClanak generated by hbm2java
 */
public class BlClanak implements java.io.Serializable {

	private int id;
	private Osoba osoba;
	private Projekat projekat;
	private String naslov;
	private String tekst;
	private String slika;
	private Date vrijeme;

	public BlClanak() {
	}

	public BlClanak(int id, Osoba osoba, Projekat projekat, String naslov,
			String tekst, String slika, Date vrijeme) {
		this.id = id;
		this.osoba = osoba;
		this.projekat = projekat;
		this.naslov = naslov;
		this.tekst = tekst;
		this.slika = slika;
		this.vrijeme = vrijeme;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Osoba getOsoba() {
		return this.osoba;
	}

	public void setOsoba(Osoba osoba) {
		this.osoba = osoba;
	}

	public Projekat getProjekat() {
		return this.projekat;
	}

	public void setProjekat(Projekat projekat) {
		this.projekat = projekat;
	}

	public String getNaslov() {
		return this.naslov;
	}

	public void setNaslov(String naslov) {
		this.naslov = naslov;
	}

	public String getTekst() {
		return this.tekst;
	}

	public void setTekst(String tekst) {
		this.tekst = tekst;
	}

	public String getSlika() {
		return this.slika;
	}

	public void setSlika(String slika) {
		this.slika = slika;
	}

	public Date getVrijeme() {
		return this.vrijeme;
	}

	public void setVrijeme(Date vrijeme) {
		this.vrijeme = vrijeme;
	}

}
