package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BuildserviceTracking generated by hbm2java
 */
public class BuildserviceTracking implements java.io.Serializable {

	private int zadatak;
	private String buildhost;
	private Date vrijeme;

	public BuildserviceTracking() {
	}

	public BuildserviceTracking(int zadatak, String buildhost, Date vrijeme) {
		this.zadatak = zadatak;
		this.buildhost = buildhost;
		this.vrijeme = vrijeme;
	}

	public int getZadatak() {
		return this.zadatak;
	}

	public void setZadatak(int zadatak) {
		this.zadatak = zadatak;
	}

	public String getBuildhost() {
		return this.buildhost;
	}

	public void setBuildhost(String buildhost) {
		this.buildhost = buildhost;
	}

	public Date getVrijeme() {
		return this.vrijeme;
	}

	public void setVrijeme(Date vrijeme) {
		this.vrijeme = vrijeme;
	}

}
