package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CronRezultat generated by hbm2java
 */
public class CronRezultat implements java.io.Serializable {

	private Integer id;
	private Cron cron;
	private String izlaz;
	private int returnValue;
	private Date vrijeme;

	public CronRezultat() {
	}

	public CronRezultat(Cron cron, String izlaz, int returnValue, Date vrijeme) {
		this.cron = cron;
		this.izlaz = izlaz;
		this.returnValue = returnValue;
		this.vrijeme = vrijeme;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Cron getCron() {
		return this.cron;
	}

	public void setCron(Cron cron) {
		this.cron = cron;
	}

	public String getIzlaz() {
		return this.izlaz;
	}

	public void setIzlaz(String izlaz) {
		this.izlaz = izlaz;
	}

	public int getReturnValue() {
		return this.returnValue;
	}

	public void setReturnValue(int returnValue) {
		this.returnValue = returnValue;
	}

	public Date getVrijeme() {
		return this.vrijeme;
	}

	public void setVrijeme(Date vrijeme) {
		this.vrijeme = vrijeme;
	}

}
