package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cron generated by hbm2java
 */
public class Cron implements java.io.Serializable {

	private Integer id;
	private String path;
	private boolean aktivan;
	private String godina;
	private String mjesec;
	private String dan;
	private String sat;
	private String minuta;
	private String sekunda;
	private Date zadnjeIzvrsenje;
	private Date sljedeceIzvrsenje;
	private Set<CronRezultat> cronRezultats = new HashSet<CronRezultat>(0);

	public Cron() {
	}

	public Cron(String path, boolean aktivan, String godina, String mjesec,
			String dan, String sat, String minuta, String sekunda,
			Date zadnjeIzvrsenje, Date sljedeceIzvrsenje) {
		this.path = path;
		this.aktivan = aktivan;
		this.godina = godina;
		this.mjesec = mjesec;
		this.dan = dan;
		this.sat = sat;
		this.minuta = minuta;
		this.sekunda = sekunda;
		this.zadnjeIzvrsenje = zadnjeIzvrsenje;
		this.sljedeceIzvrsenje = sljedeceIzvrsenje;
	}

	public Cron(String path, boolean aktivan, String godina, String mjesec,
			String dan, String sat, String minuta, String sekunda,
			Date zadnjeIzvrsenje, Date sljedeceIzvrsenje,
			Set<CronRezultat> cronRezultats) {
		this.path = path;
		this.aktivan = aktivan;
		this.godina = godina;
		this.mjesec = mjesec;
		this.dan = dan;
		this.sat = sat;
		this.minuta = minuta;
		this.sekunda = sekunda;
		this.zadnjeIzvrsenje = zadnjeIzvrsenje;
		this.sljedeceIzvrsenje = sljedeceIzvrsenje;
		this.cronRezultats = cronRezultats;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public boolean isAktivan() {
		return this.aktivan;
	}

	public void setAktivan(boolean aktivan) {
		this.aktivan = aktivan;
	}

	public String getGodina() {
		return this.godina;
	}

	public void setGodina(String godina) {
		this.godina = godina;
	}

	public String getMjesec() {
		return this.mjesec;
	}

	public void setMjesec(String mjesec) {
		this.mjesec = mjesec;
	}

	public String getDan() {
		return this.dan;
	}

	public void setDan(String dan) {
		this.dan = dan;
	}

	public String getSat() {
		return this.sat;
	}

	public void setSat(String sat) {
		this.sat = sat;
	}

	public String getMinuta() {
		return this.minuta;
	}

	public void setMinuta(String minuta) {
		this.minuta = minuta;
	}

	public String getSekunda() {
		return this.sekunda;
	}

	public void setSekunda(String sekunda) {
		this.sekunda = sekunda;
	}

	public Date getZadnjeIzvrsenje() {
		return this.zadnjeIzvrsenje;
	}

	public void setZadnjeIzvrsenje(Date zadnjeIzvrsenje) {
		this.zadnjeIzvrsenje = zadnjeIzvrsenje;
	}

	public Date getSljedeceIzvrsenje() {
		return this.sljedeceIzvrsenje;
	}

	public void setSljedeceIzvrsenje(Date sljedeceIzvrsenje) {
		this.sljedeceIzvrsenje = sljedeceIzvrsenje;
	}

	public Set<CronRezultat> getCronRezultats() {
		return this.cronRezultats;
	}

	public void setCronRezultats(Set<CronRezultat> cronRezultats) {
		this.cronRezultats = cronRezultats;
	}

}
