package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * EtfMoodle generated by hbm2java
 */
public class EtfMoodle implements java.io.Serializable {

	private EtfMoodleId id;

	public EtfMoodle() {
	}

	public EtfMoodle(EtfMoodleId id) {
		this.id = id;
	}

	public EtfMoodleId getId() {
		return this.id;
	}

	public void setId(EtfMoodleId id) {
		this.id = id;
	}

}
