package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * EtfMoodleId generated by hbm2java
 */
public class EtfMoodleId implements java.io.Serializable {

	private int predmet;
	private int akademskaGodina;
	private int moodleId;

	public EtfMoodleId() {
	}

	public EtfMoodleId(int predmet, int akademskaGodina, int moodleId) {
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.moodleId = moodleId;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public int getMoodleId() {
		return this.moodleId;
	}

	public void setMoodleId(int moodleId) {
		this.moodleId = moodleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EtfMoodleId))
			return false;
		EtfMoodleId castOther = (EtfMoodleId) other;

		return (this.getPredmet() == castOther.getPredmet())
				&& (this.getAkademskaGodina() == castOther.getAkademskaGodina())
				&& (this.getMoodleId() == castOther.getMoodleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPredmet();
		result = 37 * result + this.getAkademskaGodina();
		result = 37 * result + this.getMoodleId();
		return result;
	}

}
