package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * FaktorUspjesnosti generated by hbm2java
 */
public class FaktorUspjesnosti implements java.io.Serializable {

	private int osoba;
	private float faktor;

	public FaktorUspjesnosti() {
	}

	public FaktorUspjesnosti(int osoba, float faktor) {
		this.osoba = osoba;
		this.faktor = faktor;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public float getFaktor() {
		return this.faktor;
	}

	public void setFaktor(float faktor) {
		this.faktor = faktor;
	}

}
