package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * GgPredmetId generated by hbm2java
 */
public class GgPredmetId implements java.io.Serializable {

	private int predmet;
	private int akademskaGodina;

	public GgPredmetId() {
	}

	public GgPredmetId(int predmet, int akademskaGodina) {
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GgPredmetId))
			return false;
		GgPredmetId castOther = (GgPredmetId) other;

		return (this.getPredmet() == castOther.getPredmet())
				&& (this.getAkademskaGodina() == castOther.getAkademskaGodina());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPredmet();
		result = 37 * result + this.getAkademskaGodina();
		return result;
	}

}
