package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Institucija generated by hbm2java
 */
public class Institucija implements java.io.Serializable {

	private Integer id;
	private String naziv;
	private int roditelj;
	private String kratkiNaziv;
	private int tipinstitucije;
	private int dekan;
	private String brojProtokola;
	private Set<Predmet> predmets = new HashSet<Predmet>(0);
	private Set<Oblast> oblasts = new HashSet<Oblast>(0);

	public Institucija() {
	}

	public Institucija(String naziv, int roditelj, String kratkiNaziv,
			int tipinstitucije, int dekan, String brojProtokola) {
		this.naziv = naziv;
		this.roditelj = roditelj;
		this.kratkiNaziv = kratkiNaziv;
		this.tipinstitucije = tipinstitucije;
		this.dekan = dekan;
		this.brojProtokola = brojProtokola;
	}

	public Institucija(String naziv, int roditelj, String kratkiNaziv,
			int tipinstitucije, int dekan, String brojProtokola,
			Set<Predmet> predmets, Set<Oblast> oblasts) {
		this.naziv = naziv;
		this.roditelj = roditelj;
		this.kratkiNaziv = kratkiNaziv;
		this.tipinstitucije = tipinstitucije;
		this.dekan = dekan;
		this.brojProtokola = brojProtokola;
		this.predmets = predmets;
		this.oblasts = oblasts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public int getRoditelj() {
		return this.roditelj;
	}

	public void setRoditelj(int roditelj) {
		this.roditelj = roditelj;
	}

	public String getKratkiNaziv() {
		return this.kratkiNaziv;
	}

	public void setKratkiNaziv(String kratkiNaziv) {
		this.kratkiNaziv = kratkiNaziv;
	}

	public int getTipinstitucije() {
		return this.tipinstitucije;
	}

	public void setTipinstitucije(int tipinstitucije) {
		this.tipinstitucije = tipinstitucije;
	}

	public int getDekan() {
		return this.dekan;
	}

	public void setDekan(int dekan) {
		this.dekan = dekan;
	}

	public String getBrojProtokola() {
		return this.brojProtokola;
	}

	public void setBrojProtokola(String brojProtokola) {
		this.brojProtokola = brojProtokola;
	}

	public Set<Predmet> getPredmets() {
		return this.predmets;
	}

	public void setPredmets(Set<Predmet> predmets) {
		this.predmets = predmets;
	}

	public Set<Oblast> getOblasts() {
		return this.oblasts;
	}

	public void setOblasts(Set<Oblast> oblasts) {
		this.oblasts = oblasts;
	}

}
