package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * IspitocjeneId generated by hbm2java
 */
public class IspitocjeneId implements java.io.Serializable {

	private int ispit;
	private int student;

	public IspitocjeneId() {
	}

	public IspitocjeneId(int ispit, int student) {
		this.ispit = ispit;
		this.student = student;
	}

	public int getIspit() {
		return this.ispit;
	}

	public void setIspit(int ispit) {
		this.ispit = ispit;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IspitocjeneId))
			return false;
		IspitocjeneId castOther = (IspitocjeneId) other;

		return (this.getIspit() == castOther.getIspit())
				&& (this.getStudent() == castOther.getStudent());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIspit();
		result = 37 * result + this.getStudent();
		return result;
	}

}
