package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Ispitocjene generated by hbm2java
 */
public class Ispitocjene implements java.io.Serializable {

	private IspitocjeneId id;
	private Ispit ispit;
	private Osoba osoba;
	private float ocjena;

	public Ispitocjene() {
	}

	public Ispitocjene(IspitocjeneId id, Ispit ispit, Osoba osoba, float ocjena) {
		this.id = id;
		this.ispit = ispit;
		this.osoba = osoba;
		this.ocjena = ocjena;
	}

	public IspitocjeneId getId() {
		return this.id;
	}

	public void setId(IspitocjeneId id) {
		this.id = id;
	}

	public Ispit getIspit() {
		return this.ispit;
	}

	public void setIspit(Ispit ispit) {
		this.ispit = ispit;
	}

	public Osoba getOsoba() {
		return this.osoba;
	}

	public void setOsoba(Osoba osoba) {
		this.osoba = osoba;
	}

	public float getOcjena() {
		return this.ocjena;
	}

	public void setOcjena(float ocjena) {
		this.ocjena = ocjena;
	}

}
