package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Izbor generated by hbm2java
 */
public class Izbor implements java.io.Serializable {

	private IzborId id;

	public Izbor() {
	}

	public Izbor(IzborId id) {
		this.id = id;
	}

	public IzborId getId() {
		return this.id;
	}

	public void setId(IzborId id) {
		this.id = id;
	}

}
