package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * IzborId generated by hbm2java
 */
public class IzborId implements java.io.Serializable {

	private int osoba;
	private int zvanje;
	private Date datumIzbora;
	private Date datumIsteka;
	private int oblast;
	private int podoblast;
	private boolean dopunski;
	private boolean drugaInstitucija;

	public IzborId() {
	}

	public IzborId(int osoba, int zvanje, Date datumIzbora, Date datumIsteka,
			int oblast, int podoblast, boolean dopunski,
			boolean drugaInstitucija) {
		this.osoba = osoba;
		this.zvanje = zvanje;
		this.datumIzbora = datumIzbora;
		this.datumIsteka = datumIsteka;
		this.oblast = oblast;
		this.podoblast = podoblast;
		this.dopunski = dopunski;
		this.drugaInstitucija = drugaInstitucija;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public int getZvanje() {
		return this.zvanje;
	}

	public void setZvanje(int zvanje) {
		this.zvanje = zvanje;
	}

	public Date getDatumIzbora() {
		return this.datumIzbora;
	}

	public void setDatumIzbora(Date datumIzbora) {
		this.datumIzbora = datumIzbora;
	}

	public Date getDatumIsteka() {
		return this.datumIsteka;
	}

	public void setDatumIsteka(Date datumIsteka) {
		this.datumIsteka = datumIsteka;
	}

	public int getOblast() {
		return this.oblast;
	}

	public void setOblast(int oblast) {
		this.oblast = oblast;
	}

	public int getPodoblast() {
		return this.podoblast;
	}

	public void setPodoblast(int podoblast) {
		this.podoblast = podoblast;
	}

	public boolean isDopunski() {
		return this.dopunski;
	}

	public void setDopunski(boolean dopunski) {
		this.dopunski = dopunski;
	}

	public boolean isDrugaInstitucija() {
		return this.drugaInstitucija;
	}

	public void setDrugaInstitucija(boolean drugaInstitucija) {
		this.drugaInstitucija = drugaInstitucija;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IzborId))
			return false;
		IzborId castOther = (IzborId) other;

		return (this.getOsoba() == castOther.getOsoba())
				&& (this.getZvanje() == castOther.getZvanje())
				&& ((this.getDatumIzbora() == castOther.getDatumIzbora()) || (this
						.getDatumIzbora() != null
						&& castOther.getDatumIzbora() != null && this
						.getDatumIzbora().equals(castOther.getDatumIzbora())))
				&& ((this.getDatumIsteka() == castOther.getDatumIsteka()) || (this
						.getDatumIsteka() != null
						&& castOther.getDatumIsteka() != null && this
						.getDatumIsteka().equals(castOther.getDatumIsteka())))
				&& (this.getOblast() == castOther.getOblast())
				&& (this.getPodoblast() == castOther.getPodoblast())
				&& (this.isDopunski() == castOther.isDopunski())
				&& (this.isDrugaInstitucija() == castOther.isDrugaInstitucija());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOsoba();
		result = 37 * result + this.getZvanje();
		result = 37
				* result
				+ (getDatumIzbora() == null ? 0 : this.getDatumIzbora()
						.hashCode());
		result = 37
				* result
				+ (getDatumIsteka() == null ? 0 : this.getDatumIsteka()
						.hashCode());
		result = 37 * result + this.getOblast();
		result = 37 * result + this.getPodoblast();
		result = 37 * result + (this.isDopunski() ? 1 : 0);
		result = 37 * result + (this.isDrugaInstitucija() ? 1 : 0);
		return result;
	}

}
