package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * IzborniSlotId generated by hbm2java
 */
public class IzborniSlotId implements java.io.Serializable {

	private int id;
	private int predmet;

	public IzborniSlotId() {
	}

	public IzborniSlotId(int id, int predmet) {
		this.id = id;
		this.predmet = predmet;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IzborniSlotId))
			return false;
		IzborniSlotId castOther = (IzborniSlotId) other;

		return (this.getId() == castOther.getId())
				&& (this.getPredmet() == castOther.getPredmet());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getPredmet();
		return result;
	}

}
