package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Kanton generated by hbm2java
 */
public class Kanton implements java.io.Serializable {

	private Integer id;
	private String naziv;
	private String kratkiNaziv;

	public Kanton() {
	}

	public Kanton(String naziv, String kratkiNaziv) {
		this.naziv = naziv;
		this.kratkiNaziv = kratkiNaziv;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public String getKratkiNaziv() {
		return this.kratkiNaziv;
	}

	public void setKratkiNaziv(String kratkiNaziv) {
		this.kratkiNaziv = kratkiNaziv;
	}

}
