package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Koeficijenti generated by hbm2java
 */
public class Koeficijenti implements java.io.Serializable {

	private KoeficijentiId id;

	public Koeficijenti() {
	}

	public Koeficijenti(KoeficijentiId id) {
		this.id = id;
	}

	public KoeficijentiId getId() {
		return this.id;
	}

	public void setId(KoeficijentiId id) {
		this.id = id;
	}

}
