package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * KoeficijentiId generated by hbm2java
 */
public class KoeficijentiId implements java.io.Serializable {

	private int osoba;
	private double koeficijent;
	private double prijemni;
	private byte prijemnicount;
	private double prosjek;
	private double ocekivanje;
	private byte prijemni2;

	public KoeficijentiId() {
	}

	public KoeficijentiId(int osoba, double koeficijent, double prijemni,
			byte prijemnicount, double prosjek, double ocekivanje,
			byte prijemni2) {
		this.osoba = osoba;
		this.koeficijent = koeficijent;
		this.prijemni = prijemni;
		this.prijemnicount = prijemnicount;
		this.prosjek = prosjek;
		this.ocekivanje = ocekivanje;
		this.prijemni2 = prijemni2;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public double getKoeficijent() {
		return this.koeficijent;
	}

	public void setKoeficijent(double koeficijent) {
		this.koeficijent = koeficijent;
	}

	public double getPrijemni() {
		return this.prijemni;
	}

	public void setPrijemni(double prijemni) {
		this.prijemni = prijemni;
	}

	public byte getPrijemnicount() {
		return this.prijemnicount;
	}

	public void setPrijemnicount(byte prijemnicount) {
		this.prijemnicount = prijemnicount;
	}

	public double getProsjek() {
		return this.prosjek;
	}

	public void setProsjek(double prosjek) {
		this.prosjek = prosjek;
	}

	public double getOcekivanje() {
		return this.ocekivanje;
	}

	public void setOcekivanje(double ocekivanje) {
		this.ocekivanje = ocekivanje;
	}

	public byte getPrijemni2() {
		return this.prijemni2;
	}

	public void setPrijemni2(byte prijemni2) {
		this.prijemni2 = prijemni2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KoeficijentiId))
			return false;
		KoeficijentiId castOther = (KoeficijentiId) other;

		return (this.getOsoba() == castOther.getOsoba())
				&& (this.getKoeficijent() == castOther.getKoeficijent())
				&& (this.getPrijemni() == castOther.getPrijemni())
				&& (this.getPrijemnicount() == castOther.getPrijemnicount())
				&& (this.getProsjek() == castOther.getProsjek())
				&& (this.getOcekivanje() == castOther.getOcekivanje())
				&& (this.getPrijemni2() == castOther.getPrijemni2());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOsoba();
		result = 37 * result + (int) this.getKoeficijent();
		result = 37 * result + (int) this.getPrijemni();
		result = 37 * result + this.getPrijemnicount();
		result = 37 * result + (int) this.getProsjek();
		result = 37 * result + (int) this.getOcekivanje();
		result = 37 * result + this.getPrijemni2();
		return result;
	}

}
