package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * KolizijaId generated by hbm2java
 */
public class KolizijaId implements java.io.Serializable {

	private int student;
	private int akademskaGodina;
	private int semestar;
	private int predmet;

	public KolizijaId() {
	}

	public KolizijaId(int student, int akademskaGodina, int semestar,
			int predmet) {
		this.student = student;
		this.akademskaGodina = akademskaGodina;
		this.semestar = semestar;
		this.predmet = predmet;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public int getSemestar() {
		return this.semestar;
	}

	public void setSemestar(int semestar) {
		this.semestar = semestar;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KolizijaId))
			return false;
		KolizijaId castOther = (KolizijaId) other;

		return (this.getStudent() == castOther.getStudent())
				&& (this.getAkademskaGodina() == castOther.getAkademskaGodina())
				&& (this.getSemestar() == castOther.getSemestar())
				&& (this.getPredmet() == castOther.getPredmet());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudent();
		result = 37 * result + this.getAkademskaGodina();
		result = 37 * result + this.getSemestar();
		result = 37 * result + this.getPredmet();
		return result;
	}

}
