package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Komentar generated by hbm2java
 */
public class Komentar implements java.io.Serializable {

	private Integer id;
	private Labgrupa labgrupa;
	private Osoba osobaByNastavnik;
	private Osoba osobaByStudent;
	private int predmet;
	private Date datum;
	private String komentar;

	public Komentar() {
	}

	public Komentar(Labgrupa labgrupa, Osoba osobaByNastavnik,
			Osoba osobaByStudent, int predmet, Date datum, String komentar) {
		this.labgrupa = labgrupa;
		this.osobaByNastavnik = osobaByNastavnik;
		this.osobaByStudent = osobaByStudent;
		this.predmet = predmet;
		this.datum = datum;
		this.komentar = komentar;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Labgrupa getLabgrupa() {
		return this.labgrupa;
	}

	public void setLabgrupa(Labgrupa labgrupa) {
		this.labgrupa = labgrupa;
	}

	public Osoba getOsobaByNastavnik() {
		return this.osobaByNastavnik;
	}

	public void setOsobaByNastavnik(Osoba osobaByNastavnik) {
		this.osobaByNastavnik = osobaByNastavnik;
	}

	public Osoba getOsobaByStudent() {
		return this.osobaByStudent;
	}

	public void setOsobaByStudent(Osoba osobaByStudent) {
		this.osobaByStudent = osobaByStudent;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	public String getKomentar() {
		return this.komentar;
	}

	public void setKomentar(String komentar) {
		this.komentar = komentar;
	}

}
