package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Komponenta generated by hbm2java
 */
public class Komponenta implements java.io.Serializable {

	private Integer id;
	private Tipkomponente tipkomponente;
	private String naziv;
	private String guiNaziv;
	private String kratkiGuiNaziv;
	private double maxbodova;
	private double prolaz;
	private String opcija;
	private boolean uslov;
	private Set<Ispit> ispits = new HashSet<Ispit>(0);
	private Set<Cas> cases = new HashSet<Cas>(0);
	private Set<Komponentebodovi> komponentebodovis = new HashSet<Komponentebodovi>(
			0);

	public Komponenta() {
	}

	public Komponenta(Tipkomponente tipkomponente, String naziv,
			String guiNaziv, String kratkiGuiNaziv, double maxbodova,
			double prolaz, String opcija, boolean uslov) {
		this.tipkomponente = tipkomponente;
		this.naziv = naziv;
		this.guiNaziv = guiNaziv;
		this.kratkiGuiNaziv = kratkiGuiNaziv;
		this.maxbodova = maxbodova;
		this.prolaz = prolaz;
		this.opcija = opcija;
		this.uslov = uslov;
	}

	public Komponenta(Tipkomponente tipkomponente, String naziv,
			String guiNaziv, String kratkiGuiNaziv, double maxbodova,
			double prolaz, String opcija, boolean uslov, Set<Ispit> ispits,
			Set<Cas> cases, Set<Komponentebodovi> komponentebodovis) {
		this.tipkomponente = tipkomponente;
		this.naziv = naziv;
		this.guiNaziv = guiNaziv;
		this.kratkiGuiNaziv = kratkiGuiNaziv;
		this.maxbodova = maxbodova;
		this.prolaz = prolaz;
		this.opcija = opcija;
		this.uslov = uslov;
		this.ispits = ispits;
		this.cases = cases;
		this.komponentebodovis = komponentebodovis;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Tipkomponente getTipkomponente() {
		return this.tipkomponente;
	}

	public void setTipkomponente(Tipkomponente tipkomponente) {
		this.tipkomponente = tipkomponente;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public String getGuiNaziv() {
		return this.guiNaziv;
	}

	public void setGuiNaziv(String guiNaziv) {
		this.guiNaziv = guiNaziv;
	}

	public String getKratkiGuiNaziv() {
		return this.kratkiGuiNaziv;
	}

	public void setKratkiGuiNaziv(String kratkiGuiNaziv) {
		this.kratkiGuiNaziv = kratkiGuiNaziv;
	}

	public double getMaxbodova() {
		return this.maxbodova;
	}

	public void setMaxbodova(double maxbodova) {
		this.maxbodova = maxbodova;
	}

	public double getProlaz() {
		return this.prolaz;
	}

	public void setProlaz(double prolaz) {
		this.prolaz = prolaz;
	}

	public String getOpcija() {
		return this.opcija;
	}

	public void setOpcija(String opcija) {
		this.opcija = opcija;
	}

	public boolean isUslov() {
		return this.uslov;
	}

	public void setUslov(boolean uslov) {
		this.uslov = uslov;
	}

	public Set<Ispit> getIspits() {
		return this.ispits;
	}

	public void setIspits(Set<Ispit> ispits) {
		this.ispits = ispits;
	}

	public Set<Cas> getCases() {
		return this.cases;
	}

	public void setCases(Set<Cas> cases) {
		this.cases = cases;
	}

	public Set<Komponentebodovi> getKomponentebodovis() {
		return this.komponentebodovis;
	}

	public void setKomponentebodovis(Set<Komponentebodovi> komponentebodovis) {
		this.komponentebodovis = komponentebodovis;
	}

}
