package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * KonacnaOcjena generated by hbm2java
 */
public class KonacnaOcjena implements java.io.Serializable {

	private KonacnaOcjenaId id;
	private Odluka odluka;
	private Predmet predmet;
	private AkademskaGodina akademskaGodina;
	private Osoba osoba;
	private int ocjena;
	private Date datum;
	private Date datumUIndeksu;
	private boolean izvezena;
	private boolean datumProvjeren;

	public KonacnaOcjena() {
	}

	public KonacnaOcjena(KonacnaOcjenaId id, Predmet predmet,
			AkademskaGodina akademskaGodina, Osoba osoba, int ocjena,
			Date datum, Date datumUIndeksu, boolean izvezena,
			boolean datumProvjeren) {
		this.id = id;
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.osoba = osoba;
		this.ocjena = ocjena;
		this.datum = datum;
		this.datumUIndeksu = datumUIndeksu;
		this.izvezena = izvezena;
		this.datumProvjeren = datumProvjeren;
	}

	public KonacnaOcjena(KonacnaOcjenaId id, Odluka odluka, Predmet predmet,
			AkademskaGodina akademskaGodina, Osoba osoba, int ocjena,
			Date datum, Date datumUIndeksu, boolean izvezena,
			boolean datumProvjeren) {
		this.id = id;
		this.odluka = odluka;
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.osoba = osoba;
		this.ocjena = ocjena;
		this.datum = datum;
		this.datumUIndeksu = datumUIndeksu;
		this.izvezena = izvezena;
		this.datumProvjeren = datumProvjeren;
	}

	public KonacnaOcjenaId getId() {
		return this.id;
	}

	public void setId(KonacnaOcjenaId id) {
		this.id = id;
	}

	public Odluka getOdluka() {
		return this.odluka;
	}

	public void setOdluka(Odluka odluka) {
		this.odluka = odluka;
	}

	public Predmet getPredmet() {
		return this.predmet;
	}

	public void setPredmet(Predmet predmet) {
		this.predmet = predmet;
	}

	public AkademskaGodina getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(AkademskaGodina akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public Osoba getOsoba() {
		return this.osoba;
	}

	public void setOsoba(Osoba osoba) {
		this.osoba = osoba;
	}

	public int getOcjena() {
		return this.ocjena;
	}

	public void setOcjena(int ocjena) {
		this.ocjena = ocjena;
	}

	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	public Date getDatumUIndeksu() {
		return this.datumUIndeksu;
	}

	public void setDatumUIndeksu(Date datumUIndeksu) {
		this.datumUIndeksu = datumUIndeksu;
	}

	public boolean isIzvezena() {
		return this.izvezena;
	}

	public void setIzvezena(boolean izvezena) {
		this.izvezena = izvezena;
	}

	public boolean isDatumProvjeren() {
		return this.datumProvjeren;
	}

	public void setDatumProvjeren(boolean datumProvjeren) {
		this.datumProvjeren = datumProvjeren;
	}

}
