package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * KonacnaOcjenaId generated by hbm2java
 */
public class KonacnaOcjenaId implements java.io.Serializable {

	private int student;
	private int predmet;

	public KonacnaOcjenaId() {
	}

	public KonacnaOcjenaId(int student, int predmet) {
		this.student = student;
		this.predmet = predmet;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KonacnaOcjenaId))
			return false;
		KonacnaOcjenaId castOther = (KonacnaOcjenaId) other;

		return (this.getStudent() == castOther.getStudent())
				&& (this.getPredmet() == castOther.getPredmet());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudent();
		result = 37 * result + this.getPredmet();
		return result;
	}

}
