package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * KvizOdgovor generated by hbm2java
 */
public class KvizOdgovor implements java.io.Serializable {

	private Integer id;
	private int kvizPitanje;
	private String tekst;
	private boolean tacan;
	private boolean vidljiv;

	public KvizOdgovor() {
	}

	public KvizOdgovor(int kvizPitanje, String tekst, boolean tacan,
			boolean vidljiv) {
		this.kvizPitanje = kvizPitanje;
		this.tekst = tekst;
		this.tacan = tacan;
		this.vidljiv = vidljiv;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getKvizPitanje() {
		return this.kvizPitanje;
	}

	public void setKvizPitanje(int kvizPitanje) {
		this.kvizPitanje = kvizPitanje;
	}

	public String getTekst() {
		return this.tekst;
	}

	public void setTekst(String tekst) {
		this.tekst = tekst;
	}

	public boolean isTacan() {
		return this.tacan;
	}

	public void setTacan(boolean tacan) {
		this.tacan = tacan;
	}

	public boolean isVidljiv() {
		return this.vidljiv;
	}

	public void setVidljiv(boolean vidljiv) {
		this.vidljiv = vidljiv;
	}

}
