package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * KvizStudentId generated by hbm2java
 */
public class KvizStudentId implements java.io.Serializable {

	private int student;
	private int kviz;

	public KvizStudentId() {
	}

	public KvizStudentId(int student, int kviz) {
		this.student = student;
		this.kviz = kviz;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public int getKviz() {
		return this.kviz;
	}

	public void setKviz(int kviz) {
		this.kviz = kviz;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KvizStudentId))
			return false;
		KvizStudentId castOther = (KvizStudentId) other;

		return (this.getStudent() == castOther.getStudent())
				&& (this.getKviz() == castOther.getKviz());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudent();
		result = 37 * result + this.getKviz();
		return result;
	}

}
