package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * KvizStudent generated by hbm2java
 */
public class KvizStudent implements java.io.Serializable {

	private KvizStudentId id;
	private boolean dovrsen;
	private float bodova;
	private Date vrijemeAktivacije;

	public KvizStudent() {
	}

	public KvizStudent(KvizStudentId id, boolean dovrsen, float bodova,
			Date vrijemeAktivacije) {
		this.id = id;
		this.dovrsen = dovrsen;
		this.bodova = bodova;
		this.vrijemeAktivacije = vrijemeAktivacije;
	}

	public KvizStudentId getId() {
		return this.id;
	}

	public void setId(KvizStudentId id) {
		this.id = id;
	}

	public boolean isDovrsen() {
		return this.dovrsen;
	}

	public void setDovrsen(boolean dovrsen) {
		this.dovrsen = dovrsen;
	}

	public float getBodova() {
		return this.bodova;
	}

	public void setBodova(float bodova) {
		this.bodova = bodova;
	}

	public Date getVrijemeAktivacije() {
		return this.vrijemeAktivacije;
	}

	public void setVrijemeAktivacije(Date vrijemeAktivacije) {
		this.vrijemeAktivacije = vrijemeAktivacije;
	}

}
