package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log implements java.io.Serializable {

	private Integer id;
	private Date vrijeme;
	private int userid;
	private String dogadjaj;
	private byte nivo;

	public Log() {
	}

	public Log(Date vrijeme, int userid, String dogadjaj, byte nivo) {
		this.vrijeme = vrijeme;
		this.userid = userid;
		this.dogadjaj = dogadjaj;
		this.nivo = nivo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getVrijeme() {
		return this.vrijeme;
	}

	public void setVrijeme(Date vrijeme) {
		this.vrijeme = vrijeme;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public String getDogadjaj() {
		return this.dogadjaj;
	}

	public void setDogadjaj(String dogadjaj) {
		this.dogadjaj = dogadjaj;
	}

	public byte getNivo() {
		return this.nivo;
	}

	public void setNivo(byte nivo) {
		this.nivo = nivo;
	}

}
