package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Log2Test generated by hbm2java
 */
public class Log2Test implements java.io.Serializable {

	private int id;
	private Date vrijeme;
	private int userid;
	private int modul;
	private int dogadjaj;
	private int objekat1;
	private int objekat2;
	private int objekat3;
	private String ipaddress;

	public Log2Test() {
	}

	public Log2Test(int id, Date vrijeme, int userid, int modul, int dogadjaj,
			int objekat1, int objekat2, int objekat3, String ipaddress) {
		this.id = id;
		this.vrijeme = vrijeme;
		this.userid = userid;
		this.modul = modul;
		this.dogadjaj = dogadjaj;
		this.objekat1 = objekat1;
		this.objekat2 = objekat2;
		this.objekat3 = objekat3;
		this.ipaddress = ipaddress;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getVrijeme() {
		return this.vrijeme;
	}

	public void setVrijeme(Date vrijeme) {
		this.vrijeme = vrijeme;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public int getModul() {
		return this.modul;
	}

	public void setModul(int modul) {
		this.modul = modul;
	}

	public int getDogadjaj() {
		return this.dogadjaj;
	}

	public void setDogadjaj(int dogadjaj) {
		this.dogadjaj = dogadjaj;
	}

	public int getObjekat1() {
		return this.objekat1;
	}

	public void setObjekat1(int objekat1) {
		this.objekat1 = objekat1;
	}

	public int getObjekat2() {
		return this.objekat2;
	}

	public void setObjekat2(int objekat2) {
		this.objekat2 = objekat2;
	}

	public int getObjekat3() {
		return this.objekat3;
	}

	public void setObjekat3(int objekat3) {
		this.objekat3 = objekat3;
	}

	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

}
