package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Log2Blob generated by hbm2java
 */
public class Log2Blob implements java.io.Serializable {

	private int log2;
	private String tekst;

	public Log2Blob() {
	}

	public Log2Blob(int log2, String tekst) {
		this.log2 = log2;
		this.tekst = tekst;
	}

	public int getLog2() {
		return this.log2;
	}

	public void setLog2(int log2) {
		this.log2 = log2;
	}

	public String getTekst() {
		return this.tekst;
	}

	public void setTekst(String tekst) {
		this.tekst = tekst;
	}

}
