package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * MoodlePredmetId generated by hbm2java
 */
public class MoodlePredmetId implements java.io.Serializable {

	private MoodlePredmetIdId id;

	public MoodlePredmetId() {
	}

	public MoodlePredmetId(MoodlePredmetIdId id) {
		this.id = id;
	}

	public MoodlePredmetIdId getId() {
		return this.id;
	}

	public void setId(MoodlePredmetIdId id) {
		this.id = id;
	}

}
