package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * MoodlePredmetRss generated by hbm2java
 */
public class MoodlePredmetRss implements java.io.Serializable {

	private Integer id;
	private int vrstanovosti;
	private int moodleId;
	private String sadrzaj;
	private long vrijemePromjene;

	public MoodlePredmetRss() {
	}

	public MoodlePredmetRss(int vrstanovosti, int moodleId, String sadrzaj,
			long vrijemePromjene) {
		this.vrstanovosti = vrstanovosti;
		this.moodleId = moodleId;
		this.sadrzaj = sadrzaj;
		this.vrijemePromjene = vrijemePromjene;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getVrstanovosti() {
		return this.vrstanovosti;
	}

	public void setVrstanovosti(int vrstanovosti) {
		this.vrstanovosti = vrstanovosti;
	}

	public int getMoodleId() {
		return this.moodleId;
	}

	public void setMoodleId(int moodleId) {
		this.moodleId = moodleId;
	}

	public String getSadrzaj() {
		return this.sadrzaj;
	}

	public void setSadrzaj(String sadrzaj) {
		this.sadrzaj = sadrzaj;
	}

	public long getVrijemePromjene() {
		return this.vrijemePromjene;
	}

	public void setVrijemePromjene(long vrijemePromjene) {
		this.vrijemePromjene = vrijemePromjene;
	}

}
