package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * NacinStudiranja generated by hbm2java
 */
public class NacinStudiranja implements java.io.Serializable {

	private Integer id;
	private String naziv;
	private boolean mogucUpis;

	public NacinStudiranja() {
	}

	public NacinStudiranja(String naziv, boolean mogucUpis) {
		this.naziv = naziv;
		this.mogucUpis = mogucUpis;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public boolean isMogucUpis() {
		return this.mogucUpis;
	}

	public void setMogucUpis(boolean mogucUpis) {
		this.mogucUpis = mogucUpis;
	}

}
