package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * NastavnikPredmetId generated by hbm2java
 */
public class NastavnikPredmetId implements java.io.Serializable {

	private int nastavnik;
	private int akademskaGodina;
	private int predmet;

	public NastavnikPredmetId() {
	}

	public NastavnikPredmetId(int nastavnik, int akademskaGodina, int predmet) {
		this.nastavnik = nastavnik;
		this.akademskaGodina = akademskaGodina;
		this.predmet = predmet;
	}

	public int getNastavnik() {
		return this.nastavnik;
	}

	public void setNastavnik(int nastavnik) {
		this.nastavnik = nastavnik;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NastavnikPredmetId))
			return false;
		NastavnikPredmetId castOther = (NastavnikPredmetId) other;

		return (this.getNastavnik() == castOther.getNastavnik())
				&& (this.getAkademskaGodina() == castOther.getAkademskaGodina())
				&& (this.getPredmet() == castOther.getPredmet());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNastavnik();
		result = 37 * result + this.getAkademskaGodina();
		result = 37 * result + this.getPredmet();
		return result;
	}

}
