package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * NotifikacijeGcm generated by hbm2java
 */
public class NotifikacijeGcm implements java.io.Serializable {

	private Integer id;
	private int auth;
	private String regKey;

	public NotifikacijeGcm() {
	}

	public NotifikacijeGcm(int auth, String regKey) {
		this.auth = auth;
		this.regKey = regKey;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getAuth() {
		return this.auth;
	}

	public void setAuth(int auth) {
		this.auth = auth;
	}

	public String getRegKey() {
		return this.regKey;
	}

	public void setRegKey(String regKey) {
		this.regKey = regKey;
	}

}
