package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * OsobaPosebneKategorijeId generated by hbm2java
 */
public class OsobaPosebneKategorijeId implements java.io.Serializable {

	private int osoba;
	private int posebneKategorije;

	public OsobaPosebneKategorijeId() {
	}

	public OsobaPosebneKategorijeId(int osoba, int posebneKategorije) {
		this.osoba = osoba;
		this.posebneKategorije = posebneKategorije;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public int getPosebneKategorije() {
		return this.posebneKategorije;
	}

	public void setPosebneKategorije(int posebneKategorije) {
		this.posebneKategorije = posebneKategorije;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OsobaPosebneKategorijeId))
			return false;
		OsobaPosebneKategorijeId castOther = (OsobaPosebneKategorijeId) other;

		return (this.getOsoba() == castOther.getOsoba())
				&& (this.getPosebneKategorije() == castOther
						.getPosebneKategorije());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOsoba();
		result = 37 * result + this.getPosebneKategorije();
		return result;
	}

}
