package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * OsobaPosebneKategorije generated by hbm2java
 */
public class OsobaPosebneKategorije implements java.io.Serializable {

	private OsobaPosebneKategorijeId id;

	public OsobaPosebneKategorije() {
	}

	public OsobaPosebneKategorije(OsobaPosebneKategorijeId id) {
		this.id = id;
	}

	public OsobaPosebneKategorijeId getId() {
		return this.id;
	}

	public void setId(OsobaPosebneKategorijeId id) {
		this.id = id;
	}

}
