package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * PlanStudija generated by hbm2java
 */
public class PlanStudija implements java.io.Serializable {

	private PlanStudijaId id;

	public PlanStudija() {
	}

	public PlanStudija(PlanStudijaId id) {
		this.id = id;
	}

	public PlanStudijaId getId() {
		return this.id;
	}

	public void setId(PlanStudijaId id) {
		this.id = id;
	}

}
