package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * PlanStudijaId generated by hbm2java
 */
public class PlanStudijaId implements java.io.Serializable {

	private int godinaVazenja;
	private int studij;
	private int semestar;
	private int predmet;
	private boolean obavezan;

	public PlanStudijaId() {
	}

	public PlanStudijaId(int godinaVazenja, int studij, int semestar,
			int predmet, boolean obavezan) {
		this.godinaVazenja = godinaVazenja;
		this.studij = studij;
		this.semestar = semestar;
		this.predmet = predmet;
		this.obavezan = obavezan;
	}

	public int getGodinaVazenja() {
		return this.godinaVazenja;
	}

	public void setGodinaVazenja(int godinaVazenja) {
		this.godinaVazenja = godinaVazenja;
	}

	public int getStudij() {
		return this.studij;
	}

	public void setStudij(int studij) {
		this.studij = studij;
	}

	public int getSemestar() {
		return this.semestar;
	}

	public void setSemestar(int semestar) {
		this.semestar = semestar;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public boolean isObavezan() {
		return this.obavezan;
	}

	public void setObavezan(boolean obavezan) {
		this.obavezan = obavezan;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlanStudijaId))
			return false;
		PlanStudijaId castOther = (PlanStudijaId) other;

		return (this.getGodinaVazenja() == castOther.getGodinaVazenja())
				&& (this.getStudij() == castOther.getStudij())
				&& (this.getSemestar() == castOther.getSemestar())
				&& (this.getPredmet() == castOther.getPredmet())
				&& (this.isObavezan() == castOther.isObavezan());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGodinaVazenja();
		result = 37 * result + this.getStudij();
		result = 37 * result + this.getSemestar();
		result = 37 * result + this.getPredmet();
		result = 37 * result + (this.isObavezan() ? 1 : 0);
		return result;
	}

}
