package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Podoblast generated by hbm2java
 */
public class Podoblast implements java.io.Serializable {

	private Integer id;
	private int oblast;
	private String naziv;

	public Podoblast() {
	}

	public Podoblast(int oblast, String naziv) {
		this.oblast = oblast;
		this.naziv = naziv;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getOblast() {
		return this.oblast;
	}

	public void setOblast(int oblast) {
		this.oblast = oblast;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

}
