package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Ponudakursa generated by hbm2java
 */
public class Ponudakursa implements java.io.Serializable {

	private Integer id;
	private Predmet predmet;
	private AkademskaGodina akademskaGodina;
	private Studij studij;
	private int semestar;
	private boolean obavezan;
	private Set<Komponentebodovi> komponentebodovis = new HashSet<Komponentebodovi>(
			0);

	public Ponudakursa() {
	}

	public Ponudakursa(Predmet predmet, AkademskaGodina akademskaGodina,
			Studij studij, int semestar, boolean obavezan) {
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.studij = studij;
		this.semestar = semestar;
		this.obavezan = obavezan;
	}

	public Ponudakursa(Predmet predmet, AkademskaGodina akademskaGodina,
			Studij studij, int semestar, boolean obavezan,
			Set<Komponentebodovi> komponentebodovis) {
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.studij = studij;
		this.semestar = semestar;
		this.obavezan = obavezan;
		this.komponentebodovis = komponentebodovis;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Predmet getPredmet() {
		return this.predmet;
	}

	public void setPredmet(Predmet predmet) {
		this.predmet = predmet;
	}

	public AkademskaGodina getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(AkademskaGodina akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public Studij getStudij() {
		return this.studij;
	}

	public void setStudij(Studij studij) {
		this.studij = studij;
	}

	public int getSemestar() {
		return this.semestar;
	}

	public void setSemestar(int semestar) {
		this.semestar = semestar;
	}

	public boolean isObavezan() {
		return this.obavezan;
	}

	public void setObavezan(boolean obavezan) {
		this.obavezan = obavezan;
	}

	public Set<Komponentebodovi> getKomponentebodovis() {
		return this.komponentebodovis;
	}

	public void setKomponentebodovis(Set<Komponentebodovi> komponentebodovis) {
		this.komponentebodovis = komponentebodovis;
	}

}
