package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Poruka generated by hbm2java
 */
public class Poruka implements java.io.Serializable {

	private Integer id;
	private byte tip;
	private byte opseg;
	private int primalac;
	private int posiljalac;
	private Date vrijeme;
	private int ref;
	private String naslov;
	private String tekst;

	public Poruka() {
	}

	public Poruka(byte tip, byte opseg, int primalac, int posiljalac,
			Date vrijeme, int ref, String naslov, String tekst) {
		this.tip = tip;
		this.opseg = opseg;
		this.primalac = primalac;
		this.posiljalac = posiljalac;
		this.vrijeme = vrijeme;
		this.ref = ref;
		this.naslov = naslov;
		this.tekst = tekst;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public byte getTip() {
		return this.tip;
	}

	public void setTip(byte tip) {
		this.tip = tip;
	}

	public byte getOpseg() {
		return this.opseg;
	}

	public void setOpseg(byte opseg) {
		this.opseg = opseg;
	}

	public int getPrimalac() {
		return this.primalac;
	}

	public void setPrimalac(int primalac) {
		this.primalac = primalac;
	}

	public int getPosiljalac() {
		return this.posiljalac;
	}

	public void setPosiljalac(int posiljalac) {
		this.posiljalac = posiljalac;
	}

	public Date getVrijeme() {
		return this.vrijeme;
	}

	public void setVrijeme(Date vrijeme) {
		this.vrijeme = vrijeme;
	}

	public int getRef() {
		return this.ref;
	}

	public void setRef(int ref) {
		this.ref = ref;
	}

	public String getNaslov() {
		return this.naslov;
	}

	public void setNaslov(String naslov) {
		this.naslov = naslov;
	}

	public String getTekst() {
		return this.tekst;
	}

	public void setTekst(String tekst) {
		this.tekst = tekst;
	}

}
