package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * PredmetProjektniParametri generated by hbm2java
 */
public class PredmetProjektniParametri implements java.io.Serializable {

	private PredmetProjektniParametriId id;
	private byte minTimova;
	private byte maxTimova;
	private byte minClanovaTima;
	private byte maxClanovaTima;
	private byte zakljucaniProjekti;

	public PredmetProjektniParametri() {
	}

	public PredmetProjektniParametri(PredmetProjektniParametriId id,
			byte minTimova, byte maxTimova, byte minClanovaTima,
			byte maxClanovaTima, byte zakljucaniProjekti) {
		this.id = id;
		this.minTimova = minTimova;
		this.maxTimova = maxTimova;
		this.minClanovaTima = minClanovaTima;
		this.maxClanovaTima = maxClanovaTima;
		this.zakljucaniProjekti = zakljucaniProjekti;
	}

	public PredmetProjektniParametriId getId() {
		return this.id;
	}

	public void setId(PredmetProjektniParametriId id) {
		this.id = id;
	}

	public byte getMinTimova() {
		return this.minTimova;
	}

	public void setMinTimova(byte minTimova) {
		this.minTimova = minTimova;
	}

	public byte getMaxTimova() {
		return this.maxTimova;
	}

	public void setMaxTimova(byte maxTimova) {
		this.maxTimova = maxTimova;
	}

	public byte getMinClanovaTima() {
		return this.minClanovaTima;
	}

	public void setMinClanovaTima(byte minClanovaTima) {
		this.minClanovaTima = minClanovaTima;
	}

	public byte getMaxClanovaTima() {
		return this.maxClanovaTima;
	}

	public void setMaxClanovaTima(byte maxClanovaTima) {
		this.maxClanovaTima = maxClanovaTima;
	}

	public byte getZakljucaniProjekti() {
		return this.zakljucaniProjekti;
	}

	public void setZakljucaniProjekti(byte zakljucaniProjekti) {
		this.zakljucaniProjekti = zakljucaniProjekti;
	}

}
