package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Preference generated by hbm2java
 */
public class Preference implements java.io.Serializable {

	private PreferenceId id;

	public Preference() {
	}

	public Preference(PreferenceId id) {
		this.id = id;
	}

	public PreferenceId getId() {
		return this.id;
	}

	public void setId(PreferenceId id) {
		this.id = id;
	}

}
