package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * PreferenceId generated by hbm2java
 */
public class PreferenceId implements java.io.Serializable {

	private int korisnik;
	private String preferenca;
	private String vrijednost;

	public PreferenceId() {
	}

	public PreferenceId(int korisnik, String preferenca, String vrijednost) {
		this.korisnik = korisnik;
		this.preferenca = preferenca;
		this.vrijednost = vrijednost;
	}

	public int getKorisnik() {
		return this.korisnik;
	}

	public void setKorisnik(int korisnik) {
		this.korisnik = korisnik;
	}

	public String getPreferenca() {
		return this.preferenca;
	}

	public void setPreferenca(String preferenca) {
		this.preferenca = preferenca;
	}

	public String getVrijednost() {
		return this.vrijednost;
	}

	public void setVrijednost(String vrijednost) {
		this.vrijednost = vrijednost;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PreferenceId))
			return false;
		PreferenceId castOther = (PreferenceId) other;

		return (this.getKorisnik() == castOther.getKorisnik())
				&& ((this.getPreferenca() == castOther.getPreferenca()) || (this
						.getPreferenca() != null
						&& castOther.getPreferenca() != null && this
						.getPreferenca().equals(castOther.getPreferenca())))
				&& ((this.getVrijednost() == castOther.getVrijednost()) || (this
						.getVrijednost() != null
						&& castOther.getVrijednost() != null && this
						.getVrijednost().equals(castOther.getVrijednost())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getKorisnik();
		result = 37
				* result
				+ (getPreferenca() == null ? 0 : this.getPreferenca()
						.hashCode());
		result = 37
				* result
				+ (getVrijednost() == null ? 0 : this.getVrijednost()
						.hashCode());
		return result;
	}

}
