package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * PrijemniObrazacId generated by hbm2java
 */
public class PrijemniObrazacId implements java.io.Serializable {

	private int prijemniTermin;
	private int osoba;
	private String sifra;
	private String jezik;

	public PrijemniObrazacId() {
	}

	public PrijemniObrazacId(int prijemniTermin, int osoba, String sifra,
			String jezik) {
		this.prijemniTermin = prijemniTermin;
		this.osoba = osoba;
		this.sifra = sifra;
		this.jezik = jezik;
	}

	public int getPrijemniTermin() {
		return this.prijemniTermin;
	}

	public void setPrijemniTermin(int prijemniTermin) {
		this.prijemniTermin = prijemniTermin;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public String getSifra() {
		return this.sifra;
	}

	public void setSifra(String sifra) {
		this.sifra = sifra;
	}

	public String getJezik() {
		return this.jezik;
	}

	public void setJezik(String jezik) {
		this.jezik = jezik;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrijemniObrazacId))
			return false;
		PrijemniObrazacId castOther = (PrijemniObrazacId) other;

		return (this.getPrijemniTermin() == castOther.getPrijemniTermin())
				&& (this.getOsoba() == castOther.getOsoba())
				&& ((this.getSifra() == castOther.getSifra()) || (this
						.getSifra() != null && castOther.getSifra() != null && this
						.getSifra().equals(castOther.getSifra())))
				&& ((this.getJezik() == castOther.getJezik()) || (this
						.getJezik() != null && castOther.getJezik() != null && this
						.getJezik().equals(castOther.getJezik())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPrijemniTermin();
		result = 37 * result + this.getOsoba();
		result = 37 * result
				+ (getSifra() == null ? 0 : this.getSifra().hashCode());
		result = 37 * result
				+ (getJezik() == null ? 0 : this.getJezik().hashCode());
		return result;
	}

}
