package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Prijemni generated by hbm2java
 */
public class Prijemni implements java.io.Serializable {

	private int id;
	private String ime;
	private String prezime;
	private Date datumRodjenja;
	private String mjestoRodjenja;
	private String drzavljanstvo;
	private String zavrsenaSkola;
	private String jmbg;
	private String adresa;
	private String telefon;
	private int kanton;
	private boolean redovni;
	private String odsjekPrvi;
	private String odsjekDrugi;
	private String odsjekTreci;
	private String odsjekCetvrti;
	private double opciUspjeh;
	private double kljucniPredmeti;
	private double dodatniBodovi;
	private double prijemniIspit;
	private boolean izasaoNaPrijemni;
	private boolean studentGeneracije;
	private double prijemniIspitDva;
	private boolean prijavioDrugi;

	public Prijemni() {
	}

	public Prijemni(int id, String ime, String prezime, Date datumRodjenja,
			String mjestoRodjenja, String drzavljanstvo, String zavrsenaSkola,
			String jmbg, String adresa, String telefon, int kanton,
			boolean redovni, String odsjekPrvi, String odsjekDrugi,
			String odsjekTreci, String odsjekCetvrti, double opciUspjeh,
			double kljucniPredmeti, double dodatniBodovi, double prijemniIspit,
			boolean izasaoNaPrijemni, boolean studentGeneracije,
			double prijemniIspitDva, boolean prijavioDrugi) {
		this.id = id;
		this.ime = ime;
		this.prezime = prezime;
		this.datumRodjenja = datumRodjenja;
		this.mjestoRodjenja = mjestoRodjenja;
		this.drzavljanstvo = drzavljanstvo;
		this.zavrsenaSkola = zavrsenaSkola;
		this.jmbg = jmbg;
		this.adresa = adresa;
		this.telefon = telefon;
		this.kanton = kanton;
		this.redovni = redovni;
		this.odsjekPrvi = odsjekPrvi;
		this.odsjekDrugi = odsjekDrugi;
		this.odsjekTreci = odsjekTreci;
		this.odsjekCetvrti = odsjekCetvrti;
		this.opciUspjeh = opciUspjeh;
		this.kljucniPredmeti = kljucniPredmeti;
		this.dodatniBodovi = dodatniBodovi;
		this.prijemniIspit = prijemniIspit;
		this.izasaoNaPrijemni = izasaoNaPrijemni;
		this.studentGeneracije = studentGeneracije;
		this.prijemniIspitDva = prijemniIspitDva;
		this.prijavioDrugi = prijavioDrugi;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getIme() {
		return this.ime;
	}

	public void setIme(String ime) {
		this.ime = ime;
	}

	public String getPrezime() {
		return this.prezime;
	}

	public void setPrezime(String prezime) {
		this.prezime = prezime;
	}

	public Date getDatumRodjenja() {
		return this.datumRodjenja;
	}

	public void setDatumRodjenja(Date datumRodjenja) {
		this.datumRodjenja = datumRodjenja;
	}

	public String getMjestoRodjenja() {
		return this.mjestoRodjenja;
	}

	public void setMjestoRodjenja(String mjestoRodjenja) {
		this.mjestoRodjenja = mjestoRodjenja;
	}

	public String getDrzavljanstvo() {
		return this.drzavljanstvo;
	}

	public void setDrzavljanstvo(String drzavljanstvo) {
		this.drzavljanstvo = drzavljanstvo;
	}

	public String getZavrsenaSkola() {
		return this.zavrsenaSkola;
	}

	public void setZavrsenaSkola(String zavrsenaSkola) {
		this.zavrsenaSkola = zavrsenaSkola;
	}

	public String getJmbg() {
		return this.jmbg;
	}

	public void setJmbg(String jmbg) {
		this.jmbg = jmbg;
	}

	public String getAdresa() {
		return this.adresa;
	}

	public void setAdresa(String adresa) {
		this.adresa = adresa;
	}

	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	public int getKanton() {
		return this.kanton;
	}

	public void setKanton(int kanton) {
		this.kanton = kanton;
	}

	public boolean isRedovni() {
		return this.redovni;
	}

	public void setRedovni(boolean redovni) {
		this.redovni = redovni;
	}

	public String getOdsjekPrvi() {
		return this.odsjekPrvi;
	}

	public void setOdsjekPrvi(String odsjekPrvi) {
		this.odsjekPrvi = odsjekPrvi;
	}

	public String getOdsjekDrugi() {
		return this.odsjekDrugi;
	}

	public void setOdsjekDrugi(String odsjekDrugi) {
		this.odsjekDrugi = odsjekDrugi;
	}

	public String getOdsjekTreci() {
		return this.odsjekTreci;
	}

	public void setOdsjekTreci(String odsjekTreci) {
		this.odsjekTreci = odsjekTreci;
	}

	public String getOdsjekCetvrti() {
		return this.odsjekCetvrti;
	}

	public void setOdsjekCetvrti(String odsjekCetvrti) {
		this.odsjekCetvrti = odsjekCetvrti;
	}

	public double getOpciUspjeh() {
		return this.opciUspjeh;
	}

	public void setOpciUspjeh(double opciUspjeh) {
		this.opciUspjeh = opciUspjeh;
	}

	public double getKljucniPredmeti() {
		return this.kljucniPredmeti;
	}

	public void setKljucniPredmeti(double kljucniPredmeti) {
		this.kljucniPredmeti = kljucniPredmeti;
	}

	public double getDodatniBodovi() {
		return this.dodatniBodovi;
	}

	public void setDodatniBodovi(double dodatniBodovi) {
		this.dodatniBodovi = dodatniBodovi;
	}

	public double getPrijemniIspit() {
		return this.prijemniIspit;
	}

	public void setPrijemniIspit(double prijemniIspit) {
		this.prijemniIspit = prijemniIspit;
	}

	public boolean isIzasaoNaPrijemni() {
		return this.izasaoNaPrijemni;
	}

	public void setIzasaoNaPrijemni(boolean izasaoNaPrijemni) {
		this.izasaoNaPrijemni = izasaoNaPrijemni;
	}

	public boolean isStudentGeneracije() {
		return this.studentGeneracije;
	}

	public void setStudentGeneracije(boolean studentGeneracije) {
		this.studentGeneracije = studentGeneracije;
	}

	public double getPrijemniIspitDva() {
		return this.prijemniIspitDva;
	}

	public void setPrijemniIspitDva(double prijemniIspitDva) {
		this.prijemniIspitDva = prijemniIspitDva;
	}

	public boolean isPrijavioDrugi() {
		return this.prijavioDrugi;
	}

	public void setPrijavioDrugi(boolean prijavioDrugi) {
		this.prijavioDrugi = prijavioDrugi;
	}

}
