package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * PrijemniPrijavaId generated by hbm2java
 */
public class PrijemniPrijavaId implements java.io.Serializable {

	private int prijemniTermin;
	private int osoba;

	public PrijemniPrijavaId() {
	}

	public PrijemniPrijavaId(int prijemniTermin, int osoba) {
		this.prijemniTermin = prijemniTermin;
		this.osoba = osoba;
	}

	public int getPrijemniTermin() {
		return this.prijemniTermin;
	}

	public void setPrijemniTermin(int prijemniTermin) {
		this.prijemniTermin = prijemniTermin;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrijemniPrijavaId))
			return false;
		PrijemniPrijavaId castOther = (PrijemniPrijavaId) other;

		return (this.getPrijemniTermin() == castOther.getPrijemniTermin())
				&& (this.getOsoba() == castOther.getOsoba());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPrijemniTermin();
		result = 37 * result + this.getOsoba();
		return result;
	}

}
