package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * PrijemniObrazac generated by hbm2java
 */
public class PrijemniObrazac implements java.io.Serializable {

	private PrijemniObrazacId id;

	public PrijemniObrazac() {
	}

	public PrijemniObrazac(PrijemniObrazacId id) {
		this.id = id;
	}

	public PrijemniObrazacId getId() {
		return this.id;
	}

	public void setId(PrijemniObrazacId id) {
		this.id = id;
	}

}
