package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Prijemniocjene generated by hbm2java
 */
public class Prijemniocjene implements java.io.Serializable {

	private PrijemniocjeneId id;

	public Prijemniocjene() {
	}

	public Prijemniocjene(PrijemniocjeneId id) {
		this.id = id;
	}

	public PrijemniocjeneId getId() {
		return this.id;
	}

	public void setId(PrijemniocjeneId id) {
		this.id = id;
	}

}
