package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * PrijemniTrenutnoEdituje generated by hbm2java
 */
public class PrijemniTrenutnoEdituje implements java.io.Serializable {

	private PrijemniTrenutnoEditujeId id;

	public PrijemniTrenutnoEdituje() {
	}

	public PrijemniTrenutnoEdituje(PrijemniTrenutnoEditujeId id) {
		this.id = id;
	}

	public PrijemniTrenutnoEditujeId getId() {
		return this.id;
	}

	public void setId(PrijemniTrenutnoEditujeId id) {
		this.id = id;
	}

}
