package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Prisustvo generated by hbm2java
 */
public class Prisustvo implements java.io.Serializable {

	private PrisustvoId id;
	private boolean prisutan;
	private byte plusMinus;

	public Prisustvo() {
	}

	public Prisustvo(PrisustvoId id, boolean prisutan, byte plusMinus) {
		this.id = id;
		this.prisutan = prisutan;
		this.plusMinus = plusMinus;
	}

	public PrisustvoId getId() {
		return this.id;
	}

	public void setId(PrisustvoId id) {
		this.id = id;
	}

	public boolean isPrisutan() {
		return this.prisutan;
	}

	public void setPrisutan(boolean prisutan) {
		this.prisutan = prisutan;
	}

	public byte getPlusMinus() {
		return this.plusMinus;
	}

	public void setPlusMinus(byte plusMinus) {
		this.plusMinus = plusMinus;
	}

}
