package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * PrisustvoId generated by hbm2java
 */
public class PrisustvoId implements java.io.Serializable {

	private int student;
	private int cas;

	public PrisustvoId() {
	}

	public PrisustvoId(int student, int cas) {
		this.student = student;
		this.cas = cas;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public int getCas() {
		return this.cas;
	}

	public void setCas(int cas) {
		this.cas = cas;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrisustvoId))
			return false;
		PrisustvoId castOther = (PrisustvoId) other;

		return (this.getStudent() == castOther.getStudent())
				&& (this.getCas() == castOther.getCas());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudent();
		result = 37 * result + this.getCas();
		return result;
	}

}
