package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * PrivilegijeId generated by hbm2java
 */
public class PrivilegijeId implements java.io.Serializable {

	private int osoba;
	private String privilegija;

	public PrivilegijeId() {
	}

	public PrivilegijeId(int osoba, String privilegija) {
		this.osoba = osoba;
		this.privilegija = privilegija;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public String getPrivilegija() {
		return this.privilegija;
	}

	public void setPrivilegija(String privilegija) {
		this.privilegija = privilegija;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrivilegijeId))
			return false;
		PrivilegijeId castOther = (PrivilegijeId) other;

		return (this.getOsoba() == castOther.getOsoba())
				&& ((this.getPrivilegija() == castOther.getPrivilegija()) || (this
						.getPrivilegija() != null
						&& castOther.getPrivilegija() != null && this
						.getPrivilegija().equals(castOther.getPrivilegija())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOsoba();
		result = 37
				* result
				+ (getPrivilegija() == null ? 0 : this.getPrivilegija()
						.hashCode());
		return result;
	}

}
