package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Privilegije generated by hbm2java
 */
public class Privilegije implements java.io.Serializable {

	private PrivilegijeId id;

	public Privilegije() {
	}

	public Privilegije(PrivilegijeId id) {
		this.id = id;
	}

	public PrivilegijeId getId() {
		return this.id;
	}

	public void setId(PrivilegijeId id) {
		this.id = id;
	}

}
