package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Priznavanje generated by hbm2java
 */
public class Priznavanje implements java.io.Serializable {

	private PriznavanjeId id;

	public Priznavanje() {
	}

	public Priznavanje(PriznavanjeId id) {
		this.id = id;
	}

	public PriznavanjeId getId() {
		return this.id;
	}

	public void setId(PriznavanjeId id) {
		this.id = id;
	}

}
