package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * PriznavanjeId generated by hbm2java
 */
public class PriznavanjeId implements java.io.Serializable {

	private int student;
	private int akademskaGodina;
	private int ciklus;
	private String nazivPredmeta;
	private String sifraPredmeta;
	private float ects;
	private int ocjena;
	private int odluka;
	private String stranaInstitucija;

	public PriznavanjeId() {
	}

	public PriznavanjeId(int student, int akademskaGodina, int ciklus,
			String nazivPredmeta, String sifraPredmeta, float ects, int ocjena,
			int odluka, String stranaInstitucija) {
		this.student = student;
		this.akademskaGodina = akademskaGodina;
		this.ciklus = ciklus;
		this.nazivPredmeta = nazivPredmeta;
		this.sifraPredmeta = sifraPredmeta;
		this.ects = ects;
		this.ocjena = ocjena;
		this.odluka = odluka;
		this.stranaInstitucija = stranaInstitucija;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public int getCiklus() {
		return this.ciklus;
	}

	public void setCiklus(int ciklus) {
		this.ciklus = ciklus;
	}

	public String getNazivPredmeta() {
		return this.nazivPredmeta;
	}

	public void setNazivPredmeta(String nazivPredmeta) {
		this.nazivPredmeta = nazivPredmeta;
	}

	public String getSifraPredmeta() {
		return this.sifraPredmeta;
	}

	public void setSifraPredmeta(String sifraPredmeta) {
		this.sifraPredmeta = sifraPredmeta;
	}

	public float getEcts() {
		return this.ects;
	}

	public void setEcts(float ects) {
		this.ects = ects;
	}

	public int getOcjena() {
		return this.ocjena;
	}

	public void setOcjena(int ocjena) {
		this.ocjena = ocjena;
	}

	public int getOdluka() {
		return this.odluka;
	}

	public void setOdluka(int odluka) {
		this.odluka = odluka;
	}

	public String getStranaInstitucija() {
		return this.stranaInstitucija;
	}

	public void setStranaInstitucija(String stranaInstitucija) {
		this.stranaInstitucija = stranaInstitucija;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PriznavanjeId))
			return false;
		PriznavanjeId castOther = (PriznavanjeId) other;

		return (this.getStudent() == castOther.getStudent())
				&& (this.getAkademskaGodina() == castOther.getAkademskaGodina())
				&& (this.getCiklus() == castOther.getCiklus())
				&& ((this.getNazivPredmeta() == castOther.getNazivPredmeta()) || (this
						.getNazivPredmeta() != null
						&& castOther.getNazivPredmeta() != null && this
						.getNazivPredmeta()
						.equals(castOther.getNazivPredmeta())))
				&& ((this.getSifraPredmeta() == castOther.getSifraPredmeta()) || (this
						.getSifraPredmeta() != null
						&& castOther.getSifraPredmeta() != null && this
						.getSifraPredmeta()
						.equals(castOther.getSifraPredmeta())))
				&& (this.getEcts() == castOther.getEcts())
				&& (this.getOcjena() == castOther.getOcjena())
				&& (this.getOdluka() == castOther.getOdluka())
				&& ((this.getStranaInstitucija() == castOther
						.getStranaInstitucija()) || (this
						.getStranaInstitucija() != null
						&& castOther.getStranaInstitucija() != null && this
						.getStranaInstitucija().equals(
								castOther.getStranaInstitucija())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudent();
		result = 37 * result + this.getAkademskaGodina();
		result = 37 * result + this.getCiklus();
		result = 37
				* result
				+ (getNazivPredmeta() == null ? 0 : this.getNazivPredmeta()
						.hashCode());
		result = 37
				* result
				+ (getSifraPredmeta() == null ? 0 : this.getSifraPredmeta()
						.hashCode());
		result = 37 * result + (int) this.getEcts();
		result = 37 * result + this.getOcjena();
		result = 37 * result + this.getOdluka();
		result = 37
				* result
				+ (getStranaInstitucija() == null ? 0 : this
						.getStranaInstitucija().hashCode());
		return result;
	}

}
