package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProjekatFileDiff generated by hbm2java
 */
public class ProjekatFileDiff implements java.io.Serializable {

	private int file;
	private String diff;

	public ProjekatFileDiff() {
	}

	public ProjekatFileDiff(int file, String diff) {
		this.file = file;
		this.diff = diff;
	}

	public int getFile() {
		return this.file;
	}

	public void setFile(int file) {
		this.file = file;
	}

	public String getDiff() {
		return this.diff;
	}

	public void setDiff(String diff) {
		this.diff = diff;
	}

}
