package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ProjekatFile generated by hbm2java
 */
public class ProjekatFile implements java.io.Serializable {

	private int id;
	private String filename;
	private Date vrijeme;
	private byte revizija;
	private int osoba;
	private int projekat;
	private int file;

	public ProjekatFile() {
	}

	public ProjekatFile(int id, String filename, Date vrijeme, byte revizija,
			int osoba, int projekat, int file) {
		this.id = id;
		this.filename = filename;
		this.vrijeme = vrijeme;
		this.revizija = revizija;
		this.osoba = osoba;
		this.projekat = projekat;
		this.file = file;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public Date getVrijeme() {
		return this.vrijeme;
	}

	public void setVrijeme(Date vrijeme) {
		this.vrijeme = vrijeme;
	}

	public byte getRevizija() {
		return this.revizija;
	}

	public void setRevizija(byte revizija) {
		this.revizija = revizija;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public int getProjekat() {
		return this.projekat;
	}

	public void setProjekat(int projekat) {
		this.projekat = projekat;
	}

	public int getFile() {
		return this.file;
	}

	public void setFile(int file) {
		this.file = file;
	}

}
