package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * PromjenaOdsjeka generated by hbm2java
 */
public class PromjenaOdsjeka implements java.io.Serializable {

	private Integer id;
	private int osoba;
	private int izOdsjeka;
	private int UOdsjek;
	private int akademskaGodina;

	public PromjenaOdsjeka() {
	}

	public PromjenaOdsjeka(int osoba, int izOdsjeka, int UOdsjek,
			int akademskaGodina) {
		this.osoba = osoba;
		this.izOdsjeka = izOdsjeka;
		this.UOdsjek = UOdsjek;
		this.akademskaGodina = akademskaGodina;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public int getIzOdsjeka() {
		return this.izOdsjeka;
	}

	public void setIzOdsjeka(int izOdsjeka) {
		this.izOdsjeka = izOdsjeka;
	}

	public int getUOdsjek() {
		return this.UOdsjek;
	}

	public void setUOdsjek(int UOdsjek) {
		this.UOdsjek = UOdsjek;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

}
