package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProsliciklusUspjeh generated by hbm2java
 */
public class ProsliciklusUspjeh implements java.io.Serializable {

	private ProsliciklusUspjehId id;

	public ProsliciklusUspjeh() {
	}

	public ProsliciklusUspjeh(ProsliciklusUspjehId id) {
		this.id = id;
	}

	public ProsliciklusUspjehId getId() {
		return this.id;
	}

	public void setId(ProsliciklusUspjehId id) {
		this.id = id;
	}

}
