package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProsliciklusOcjene generated by hbm2java
 */
public class ProsliciklusOcjene implements java.io.Serializable {

	private ProsliciklusOcjeneId id;
	private byte ocjena;
	private float ects;

	public ProsliciklusOcjene() {
	}

	public ProsliciklusOcjene(ProsliciklusOcjeneId id, byte ocjena, float ects) {
		this.id = id;
		this.ocjena = ocjena;
		this.ects = ects;
	}

	public ProsliciklusOcjeneId getId() {
		return this.id;
	}

	public void setId(ProsliciklusOcjeneId id) {
		this.id = id;
	}

	public byte getOcjena() {
		return this.ocjena;
	}

	public void setOcjena(byte ocjena) {
		this.ocjena = ocjena;
	}

	public float getEcts() {
		return this.ects;
	}

	public void setEcts(float ects) {
		this.ects = ects;
	}

}
