package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProsliciklusOcjeneId generated by hbm2java
 */
public class ProsliciklusOcjeneId implements java.io.Serializable {

	private int osoba;
	private int redniBroj;

	public ProsliciklusOcjeneId() {
	}

	public ProsliciklusOcjeneId(int osoba, int redniBroj) {
		this.osoba = osoba;
		this.redniBroj = redniBroj;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public int getRedniBroj() {
		return this.redniBroj;
	}

	public void setRedniBroj(int redniBroj) {
		this.redniBroj = redniBroj;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProsliciklusOcjeneId))
			return false;
		ProsliciklusOcjeneId castOther = (ProsliciklusOcjeneId) other;

		return (this.getOsoba() == castOther.getOsoba())
				&& (this.getRedniBroj() == castOther.getRedniBroj());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOsoba();
		result = 37 * result + this.getRedniBroj();
		return result;
	}

}
