package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RasporedStavka generated by hbm2java
 */
public class RasporedStavka implements java.io.Serializable {

	private Integer id;
	private int raspored;
	private boolean danUSedmici;
	private int predmet;
	private int labgrupa;
	private int vrijemePocetak;
	private int vrijemeKraj;
	private int sala;
	private String tip;
	private int dupla;
	private boolean isjeckana;
	private Date finiPocetak;
	private Date finiKraj;

	public RasporedStavka() {
	}

	public RasporedStavka(int raspored, boolean danUSedmici, int predmet,
			int labgrupa, int vrijemePocetak, int vrijemeKraj, int sala,
			String tip, int dupla, boolean isjeckana, Date finiPocetak,
			Date finiKraj) {
		this.raspored = raspored;
		this.danUSedmici = danUSedmici;
		this.predmet = predmet;
		this.labgrupa = labgrupa;
		this.vrijemePocetak = vrijemePocetak;
		this.vrijemeKraj = vrijemeKraj;
		this.sala = sala;
		this.tip = tip;
		this.dupla = dupla;
		this.isjeckana = isjeckana;
		this.finiPocetak = finiPocetak;
		this.finiKraj = finiKraj;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getRaspored() {
		return this.raspored;
	}

	public void setRaspored(int raspored) {
		this.raspored = raspored;
	}

	public boolean isDanUSedmici() {
		return this.danUSedmici;
	}

	public void setDanUSedmici(boolean danUSedmici) {
		this.danUSedmici = danUSedmici;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public int getLabgrupa() {
		return this.labgrupa;
	}

	public void setLabgrupa(int labgrupa) {
		this.labgrupa = labgrupa;
	}

	public int getVrijemePocetak() {
		return this.vrijemePocetak;
	}

	public void setVrijemePocetak(int vrijemePocetak) {
		this.vrijemePocetak = vrijemePocetak;
	}

	public int getVrijemeKraj() {
		return this.vrijemeKraj;
	}

	public void setVrijemeKraj(int vrijemeKraj) {
		this.vrijemeKraj = vrijemeKraj;
	}

	public int getSala() {
		return this.sala;
	}

	public void setSala(int sala) {
		this.sala = sala;
	}

	public String getTip() {
		return this.tip;
	}

	public void setTip(String tip) {
		this.tip = tip;
	}

	public int getDupla() {
		return this.dupla;
	}

	public void setDupla(int dupla) {
		this.dupla = dupla;
	}

	public boolean isIsjeckana() {
		return this.isjeckana;
	}

	public void setIsjeckana(boolean isjeckana) {
		this.isjeckana = isjeckana;
	}

	public Date getFiniPocetak() {
		return this.finiPocetak;
	}

	public void setFiniPocetak(Date finiPocetak) {
		this.finiPocetak = finiPocetak;
	}

	public Date getFiniKraj() {
		return this.finiKraj;
	}

	public void setFiniKraj(Date finiKraj) {
		this.finiKraj = finiKraj;
	}

}
