package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * RasporedSala generated by hbm2java
 */
public class RasporedSala implements java.io.Serializable {

	private Integer id;
	private String naziv;
	private Integer kapacitet;
	private String tip;

	public RasporedSala() {
	}

	public RasporedSala(String naziv, String tip) {
		this.naziv = naziv;
		this.tip = tip;
	}

	public RasporedSala(String naziv, Integer kapacitet, String tip) {
		this.naziv = naziv;
		this.kapacitet = kapacitet;
		this.tip = tip;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public Integer getKapacitet() {
		return this.kapacitet;
	}

	public void setKapacitet(Integer kapacitet) {
		this.kapacitet = kapacitet;
	}

	public String getTip() {
		return this.tip;
	}

	public void setTip(String tip) {
		this.tip = tip;
	}

}
