package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Raspored generated by hbm2java
 */
public class Raspored implements java.io.Serializable {

	private Integer id;
	private int studij;
	private int akademskaGodina;
	private int semestar;
	private int privatno;
	private byte aktivan;
	private Date vrijemeKreiranja;

	public Raspored() {
	}

	public Raspored(int studij, int akademskaGodina, int semestar,
			int privatno, byte aktivan, Date vrijemeKreiranja) {
		this.studij = studij;
		this.akademskaGodina = akademskaGodina;
		this.semestar = semestar;
		this.privatno = privatno;
		this.aktivan = aktivan;
		this.vrijemeKreiranja = vrijemeKreiranja;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getStudij() {
		return this.studij;
	}

	public void setStudij(int studij) {
		this.studij = studij;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public int getSemestar() {
		return this.semestar;
	}

	public void setSemestar(int semestar) {
		this.semestar = semestar;
	}

	public int getPrivatno() {
		return this.privatno;
	}

	public void setPrivatno(int privatno) {
		this.privatno = privatno;
	}

	public byte getAktivan() {
		return this.aktivan;
	}

	public void setAktivan(byte aktivan) {
		this.aktivan = aktivan;
	}

	public Date getVrijemeKreiranja() {
		return this.vrijemeKreiranja;
	}

	public void setVrijemeKreiranja(Date vrijemeKreiranja) {
		this.vrijemeKreiranja = vrijemeKreiranja;
	}

}
