package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Rss generated by hbm2java
 */
public class Rss implements java.io.Serializable {

	private String id;
	private int auth;
	private Date access;

	public Rss() {
	}

	public Rss(String id, int auth, Date access) {
		this.id = id;
		this.auth = auth;
		this.access = access;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public int getAuth() {
		return this.auth;
	}

	public void setAuth(int auth) {
		this.auth = auth;
	}

	public Date getAccess() {
		return this.access;
	}

	public void setAccess(Date access) {
		this.access = access;
	}

}
