package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Septembar generated by hbm2java
 */
public class Septembar implements java.io.Serializable {

	private SeptembarId id;

	public Septembar() {
	}

	public Septembar(SeptembarId id) {
		this.id = id;
	}

	public SeptembarId getId() {
		return this.id;
	}

	public void setId(SeptembarId id) {
		this.id = id;
	}

}
