package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * SeptembarId generated by hbm2java
 */
public class SeptembarId implements java.io.Serializable {

	private int student;
	private int akademskaGodina;
	private int predmet;

	public SeptembarId() {
	}

	public SeptembarId(int student, int akademskaGodina, int predmet) {
		this.student = student;
		this.akademskaGodina = akademskaGodina;
		this.predmet = predmet;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeptembarId))
			return false;
		SeptembarId castOther = (SeptembarId) other;

		return (this.getStudent() == castOther.getStudent())
				&& (this.getAkademskaGodina() == castOther.getAkademskaGodina())
				&& (this.getPredmet() == castOther.getPredmet());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudent();
		result = 37 * result + this.getAkademskaGodina();
		result = 37 * result + this.getPredmet();
		return result;
	}

}
