package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * SrednjaSkola generated by hbm2java
 */
public class SrednjaSkola implements java.io.Serializable {

	private Integer id;
	private String naziv;
	private int opcina;
	private boolean domaca;
	private String tipskole;

	public SrednjaSkola() {
	}

	public SrednjaSkola(String naziv, int opcina, boolean domaca,
			String tipskole) {
		this.naziv = naziv;
		this.opcina = opcina;
		this.domaca = domaca;
		this.tipskole = tipskole;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public int getOpcina() {
		return this.opcina;
	}

	public void setOpcina(int opcina) {
		this.opcina = opcina;
	}

	public boolean isDomaca() {
		return this.domaca;
	}

	public void setDomaca(boolean domaca) {
		this.domaca = domaca;
	}

	public String getTipskole() {
		return this.tipskole;
	}

	public void setTipskole(String tipskole) {
		this.tipskole = tipskole;
	}

}
