package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * SrednjaOcjene generated by hbm2java
 */
public class SrednjaOcjene implements java.io.Serializable {

	private SrednjaOcjeneId id;

	public SrednjaOcjene() {
	}

	public SrednjaOcjene(SrednjaOcjeneId id) {
		this.id = id;
	}

	public SrednjaOcjeneId getId() {
		return this.id;
	}

	public void setId(SrednjaOcjeneId id) {
		this.id = id;
	}

}
