package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * SrednjaOcjeneId generated by hbm2java
 */
public class SrednjaOcjeneId implements java.io.Serializable {

	private int osoba;
	private byte razred;
	private int redniBroj;
	private byte ocjena;
	private byte tipocjene;

	public SrednjaOcjeneId() {
	}

	public SrednjaOcjeneId(int osoba, byte razred, int redniBroj, byte ocjena,
			byte tipocjene) {
		this.osoba = osoba;
		this.razred = razred;
		this.redniBroj = redniBroj;
		this.ocjena = ocjena;
		this.tipocjene = tipocjene;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public byte getRazred() {
		return this.razred;
	}

	public void setRazred(byte razred) {
		this.razred = razred;
	}

	public int getRedniBroj() {
		return this.redniBroj;
	}

	public void setRedniBroj(int redniBroj) {
		this.redniBroj = redniBroj;
	}

	public byte getOcjena() {
		return this.ocjena;
	}

	public void setOcjena(byte ocjena) {
		this.ocjena = ocjena;
	}

	public byte getTipocjene() {
		return this.tipocjene;
	}

	public void setTipocjene(byte tipocjene) {
		this.tipocjene = tipocjene;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SrednjaOcjeneId))
			return false;
		SrednjaOcjeneId castOther = (SrednjaOcjeneId) other;

		return (this.getOsoba() == castOther.getOsoba())
				&& (this.getRazred() == castOther.getRazred())
				&& (this.getRedniBroj() == castOther.getRedniBroj())
				&& (this.getOcjena() == castOther.getOcjena())
				&& (this.getTipocjene() == castOther.getTipocjene());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOsoba();
		result = 37 * result + this.getRazred();
		result = 37 * result + this.getRedniBroj();
		result = 37 * result + this.getOcjena();
		result = 37 * result + this.getTipocjene();
		return result;
	}

}
