package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Stdin generated by hbm2java
 */
public class Stdin implements java.io.Serializable {

	private Long id;
	private long zadaca;
	private int redniBroj;
	private String ulaz;

	public Stdin() {
	}

	public Stdin(long zadaca, int redniBroj, String ulaz) {
		this.zadaca = zadaca;
		this.redniBroj = redniBroj;
		this.ulaz = ulaz;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getZadaca() {
		return this.zadaca;
	}

	public void setZadaca(long zadaca) {
		this.zadaca = zadaca;
	}

	public int getRedniBroj() {
		return this.redniBroj;
	}

	public void setRedniBroj(int redniBroj) {
		this.redniBroj = redniBroj;
	}

	public String getUlaz() {
		return this.ulaz;
	}

	public void setUlaz(String ulaz) {
		this.ulaz = ulaz;
	}

}
