package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.*;

/**
 * StrucniStepen generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class StrucniStepen implements java.io.Serializable {

	private Integer id;
	private String naziv;
	private String titula;
	@JsonIgnore
	private Set<Osoba> osobas = new HashSet<Osoba>(0);

	public StrucniStepen() {
	}

	public StrucniStepen(String naziv, String titula) {
		this.naziv = naziv;
		this.titula = titula;
	}

	public StrucniStepen(String naziv, String titula, Set<Osoba> osobas) {
		this.naziv = naziv;
		this.titula = titula;
		this.osobas = osobas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public String getTitula() {
		return this.titula;
	}

	public void setTitula(String titula) {
		this.titula = titula;
	}

	public Set<Osoba> getOsobas() {
		return this.osobas;
	}

	public void setOsobas(Set<Osoba> osobas) {
		this.osobas = osobas;
	}

}
