package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * StudentskiModuli generated by hbm2java
 */
public class StudentskiModuli implements java.io.Serializable {

	private StudentskiModuliId id;

	public StudentskiModuli() {
	}

	public StudentskiModuli(StudentskiModuliId id) {
		this.id = id;
	}

	public StudentskiModuliId getId() {
		return this.id;
	}

	public void setId(StudentskiModuliId id) {
		this.id = id;
	}

}
