package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * StudentskiModuliId generated by hbm2java
 */
public class StudentskiModuliId implements java.io.Serializable {

	private int id;
	private int predmet;
	private int akademskaGodina;
	private String guiNaziv;
	private String url;
	private boolean aktivan;
	private boolean noviProzor;

	public StudentskiModuliId() {
	}

	public StudentskiModuliId(int id, int predmet, int akademskaGodina,
			String guiNaziv, String url, boolean aktivan, boolean noviProzor) {
		this.id = id;
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.guiNaziv = guiNaziv;
		this.url = url;
		this.aktivan = aktivan;
		this.noviProzor = noviProzor;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public String getGuiNaziv() {
		return this.guiNaziv;
	}

	public void setGuiNaziv(String guiNaziv) {
		this.guiNaziv = guiNaziv;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public boolean isAktivan() {
		return this.aktivan;
	}

	public void setAktivan(boolean aktivan) {
		this.aktivan = aktivan;
	}

	public boolean isNoviProzor() {
		return this.noviProzor;
	}

	public void setNoviProzor(boolean noviProzor) {
		this.noviProzor = noviProzor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentskiModuliId))
			return false;
		StudentskiModuliId castOther = (StudentskiModuliId) other;

		return (this.getId() == castOther.getId())
				&& (this.getPredmet() == castOther.getPredmet())
				&& (this.getAkademskaGodina() == castOther.getAkademskaGodina())
				&& ((this.getGuiNaziv() == castOther.getGuiNaziv()) || (this
						.getGuiNaziv() != null
						&& castOther.getGuiNaziv() != null && this
						.getGuiNaziv().equals(castOther.getGuiNaziv())))
				&& ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null
						&& castOther.getUrl() != null && this.getUrl().equals(
						castOther.getUrl())))
				&& (this.isAktivan() == castOther.isAktivan())
				&& (this.isNoviProzor() == castOther.isNoviProzor());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getPredmet();
		result = 37 * result + this.getAkademskaGodina();
		result = 37 * result
				+ (getGuiNaziv() == null ? 0 : this.getGuiNaziv().hashCode());
		result = 37 * result
				+ (getUrl() == null ? 0 : this.getUrl().hashCode());
		result = 37 * result + (this.isAktivan() ? 1 : 0);
		result = 37 * result + (this.isNoviProzor() ? 1 : 0);
		return result;
	}

}
