package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * StudentLabgrupa generated by hbm2java
 */
public class StudentLabgrupa implements java.io.Serializable {

	private StudentLabgrupaId id;

	public StudentLabgrupa() {
	}

	public StudentLabgrupa(StudentLabgrupaId id) {
		this.id = id;
	}

	public StudentLabgrupaId getId() {
		return this.id;
	}

	public void setId(StudentLabgrupaId id) {
		this.id = id;
	}

}
