package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * StudentskiModulPredmet generated by hbm2java
 */
public class StudentskiModulPredmet implements java.io.Serializable {

	private StudentskiModulPredmetId id;
	private boolean aktivan;

	public StudentskiModulPredmet() {
	}

	public StudentskiModulPredmet(StudentskiModulPredmetId id, boolean aktivan) {
		this.id = id;
		this.aktivan = aktivan;
	}

	public StudentskiModulPredmetId getId() {
		return this.id;
	}

	public void setId(StudentskiModulPredmetId id) {
		this.id = id;
	}

	public boolean isAktivan() {
		return this.aktivan;
	}

	public void setAktivan(boolean aktivan) {
		this.aktivan = aktivan;
	}

}
