package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * StudentIspitTerminId generated by hbm2java
 */
public class StudentIspitTerminId implements java.io.Serializable {

	private int student;
	private int ispitTermin;

	public StudentIspitTerminId() {
	}

	public StudentIspitTerminId(int student, int ispitTermin) {
		this.student = student;
		this.ispitTermin = ispitTermin;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public int getIspitTermin() {
		return this.ispitTermin;
	}

	public void setIspitTermin(int ispitTermin) {
		this.ispitTermin = ispitTermin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentIspitTerminId))
			return false;
		StudentIspitTerminId castOther = (StudentIspitTerminId) other;

		return (this.getStudent() == castOther.getStudent())
				&& (this.getIspitTermin() == castOther.getIspitTermin());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudent();
		result = 37 * result + this.getIspitTermin();
		return result;
	}

}
