package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * StudentStudijId generated by hbm2java
 */
public class StudentStudijId implements java.io.Serializable {

	private int student;
	private int studij;
	private int semestar;
	private int akademskaGodina;
	private int nacinStudiranja;
	private byte ponovac;
	private Integer odluka;
	private int planStudija;

	public StudentStudijId() {
	}

	public StudentStudijId(int student, int studij, int semestar,
			int akademskaGodina, int nacinStudiranja, byte ponovac,
			int planStudija) {
		this.student = student;
		this.studij = studij;
		this.semestar = semestar;
		this.akademskaGodina = akademskaGodina;
		this.nacinStudiranja = nacinStudiranja;
		this.ponovac = ponovac;
		this.planStudija = planStudija;
	}

	public StudentStudijId(int student, int studij, int semestar,
			int akademskaGodina, int nacinStudiranja, byte ponovac,
			Integer odluka, int planStudija) {
		this.student = student;
		this.studij = studij;
		this.semestar = semestar;
		this.akademskaGodina = akademskaGodina;
		this.nacinStudiranja = nacinStudiranja;
		this.ponovac = ponovac;
		this.odluka = odluka;
		this.planStudija = planStudija;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public int getStudij() {
		return this.studij;
	}

	public void setStudij(int studij) {
		this.studij = studij;
	}

	public int getSemestar() {
		return this.semestar;
	}

	public void setSemestar(int semestar) {
		this.semestar = semestar;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public int getNacinStudiranja() {
		return this.nacinStudiranja;
	}

	public void setNacinStudiranja(int nacinStudiranja) {
		this.nacinStudiranja = nacinStudiranja;
	}

	public byte getPonovac() {
		return this.ponovac;
	}

	public void setPonovac(byte ponovac) {
		this.ponovac = ponovac;
	}

	public Integer getOdluka() {
		return this.odluka;
	}

	public void setOdluka(Integer odluka) {
		this.odluka = odluka;
	}

	public int getPlanStudija() {
		return this.planStudija;
	}

	public void setPlanStudija(int planStudija) {
		this.planStudija = planStudija;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentStudijId))
			return false;
		StudentStudijId castOther = (StudentStudijId) other;

		return (this.getStudent() == castOther.getStudent())
				&& (this.getStudij() == castOther.getStudij())
				&& (this.getSemestar() == castOther.getSemestar())
				&& (this.getAkademskaGodina() == castOther.getAkademskaGodina())
				&& (this.getNacinStudiranja() == castOther.getNacinStudiranja())
				&& (this.getPonovac() == castOther.getPonovac())
				&& ((this.getOdluka() == castOther.getOdluka()) || (this
						.getOdluka() != null && castOther.getOdluka() != null && this
						.getOdluka().equals(castOther.getOdluka())))
				&& (this.getPlanStudija() == castOther.getPlanStudija());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudent();
		result = 37 * result + this.getStudij();
		result = 37 * result + this.getSemestar();
		result = 37 * result + this.getAkademskaGodina();
		result = 37 * result + this.getNacinStudiranja();
		result = 37 * result + this.getPonovac();
		result = 37 * result
				+ (getOdluka() == null ? 0 : this.getOdluka().hashCode());
		result = 37 * result + this.getPlanStudija();
		return result;
	}

}
