package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * StudentIspitTermin generated by hbm2java
 */
public class StudentIspitTermin implements java.io.Serializable {

	private StudentIspitTerminId id;

	public StudentIspitTermin() {
	}

	public StudentIspitTermin(StudentIspitTerminId id) {
		this.id = id;
	}

	public StudentIspitTerminId getId() {
		return this.id;
	}

	public void setId(StudentIspitTerminId id) {
		this.id = id;
	}

}
