package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * StudentskiModulPredmetId generated by hbm2java
 */
public class StudentskiModulPredmetId implements java.io.Serializable {

	private int predmet;
	private int akademskaGodina;
	private int studentskiModul;

	public StudentskiModulPredmetId() {
	}

	public StudentskiModulPredmetId(int predmet, int akademskaGodina,
			int studentskiModul) {
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.studentskiModul = studentskiModul;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public int getStudentskiModul() {
		return this.studentskiModul;
	}

	public void setStudentskiModul(int studentskiModul) {
		this.studentskiModul = studentskiModul;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentskiModulPredmetId))
			return false;
		StudentskiModulPredmetId castOther = (StudentskiModulPredmetId) other;

		return (this.getPredmet() == castOther.getPredmet())
				&& (this.getAkademskaGodina() == castOther.getAkademskaGodina())
				&& (this.getStudentskiModul() == castOther.getStudentskiModul());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPredmet();
		result = 37 * result + this.getAkademskaGodina();
		result = 37 * result + this.getStudentskiModul();
		return result;
	}

}
