package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * StudentStudij generated by hbm2java
 */
public class StudentStudij implements java.io.Serializable {

	private StudentStudijId id;

	public StudentStudij() {
	}

	public StudentStudij(StudentStudijId id) {
		this.id = id;
	}

	public StudentStudijId getId() {
		return this.id;
	}

	public void setId(StudentStudijId id) {
		this.id = id;
	}

}
