package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * StudentLabgrupaId generated by hbm2java
 */
public class StudentLabgrupaId implements java.io.Serializable {

	private int student;
	private int labgrupa;

	public StudentLabgrupaId() {
	}

	public StudentLabgrupaId(int student, int labgrupa) {
		this.student = student;
		this.labgrupa = labgrupa;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public int getLabgrupa() {
		return this.labgrupa;
	}

	public void setLabgrupa(int labgrupa) {
		this.labgrupa = labgrupa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentLabgrupaId))
			return false;
		StudentLabgrupaId castOther = (StudentLabgrupaId) other;

		return (this.getStudent() == castOther.getStudent())
				&& (this.getLabgrupa() == castOther.getLabgrupa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudent();
		result = 37 * result + this.getLabgrupa();
		return result;
	}

}
