package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * StudentProjekat generated by hbm2java
 */
public class StudentProjekat implements java.io.Serializable {

	private StudentProjekatId id;

	public StudentProjekat() {
	}

	public StudentProjekat(StudentProjekatId id) {
		this.id = id;
	}

	public StudentProjekatId getId() {
		return this.id;
	}

	public void setId(StudentProjekatId id) {
		this.id = id;
	}

}
