package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * StudentskiModul generated by hbm2java
 */
public class StudentskiModul implements java.io.Serializable {

	private int id;
	private String modul;
	private String guiNaziv;
	private boolean noviProzor;

	public StudentskiModul() {
	}

	public StudentskiModul(int id, String modul, String guiNaziv,
			boolean noviProzor) {
		this.id = id;
		this.modul = modul;
		this.guiNaziv = guiNaziv;
		this.noviProzor = noviProzor;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getModul() {
		return this.modul;
	}

	public void setModul(String modul) {
		this.modul = modul;
	}

	public String getGuiNaziv() {
		return this.guiNaziv;
	}

	public void setGuiNaziv(String guiNaziv) {
		this.guiNaziv = guiNaziv;
	}

	public boolean isNoviProzor() {
		return this.noviProzor;
	}

	public void setNoviProzor(boolean noviProzor) {
		this.noviProzor = noviProzor;
	}

}
