package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * StudentProjekatId generated by hbm2java
 */
public class StudentProjekatId implements java.io.Serializable {

	private int student;
	private int projekat;

	public StudentProjekatId() {
	}

	public StudentProjekatId(int student, int projekat) {
		this.student = student;
		this.projekat = projekat;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public int getProjekat() {
		return this.projekat;
	}

	public void setProjekat(int projekat) {
		this.projekat = projekat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentProjekatId))
			return false;
		StudentProjekatId castOther = (StudentProjekatId) other;

		return (this.getStudent() == castOther.getStudent())
				&& (this.getProjekat() == castOther.getProjekat());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudent();
		result = 37 * result + this.getProjekat();
		return result;
	}

}
