package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * StudentPredmet generated by hbm2java
 */
public class StudentPredmet implements java.io.Serializable {

	private StudentPredmetId id;

	public StudentPredmet() {
	}

	public StudentPredmet(StudentPredmetId id) {
		this.id = id;
	}

	public StudentPredmetId getId() {
		return this.id;
	}

	public void setId(StudentPredmetId id) {
		this.id = id;
	}

}
