package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * TemaZaZadacu2 generated by hbm2java
 */
public class TemaZaZadacu2 implements java.io.Serializable {

	private Integer id;
	private String naslov;
	private String tekst;
	private int osoba;
	private boolean grupa;
	private int zadaca;
	private byte sakrivena;

	public TemaZaZadacu2() {
	}

	public TemaZaZadacu2(String naslov, String tekst, int osoba, boolean grupa,
			int zadaca, byte sakrivena) {
		this.naslov = naslov;
		this.tekst = tekst;
		this.osoba = osoba;
		this.grupa = grupa;
		this.zadaca = zadaca;
		this.sakrivena = sakrivena;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNaslov() {
		return this.naslov;
	}

	public void setNaslov(String naslov) {
		this.naslov = naslov;
	}

	public String getTekst() {
		return this.tekst;
	}

	public void setTekst(String tekst) {
		this.tekst = tekst;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public boolean isGrupa() {
		return this.grupa;
	}

	public void setGrupa(boolean grupa) {
		this.grupa = grupa;
	}

	public int getZadaca() {
		return this.zadaca;
	}

	public void setZadaca(int zadaca) {
		this.zadaca = zadaca;
	}

	public byte getSakrivena() {
		return this.sakrivena;
	}

	public void setSakrivena(byte sakrivena) {
		this.sakrivena = sakrivena;
	}

}
