package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TemaZaZadacu generated by hbm2java
 */
public class TemaZaZadacu implements java.io.Serializable {

	private TemaZaZadacuId id;
	private String naslov;
	private boolean potvrdjena;
	private Date vrijeme;
	private String komentar;

	public TemaZaZadacu() {
	}

	public TemaZaZadacu(TemaZaZadacuId id, String naslov, boolean potvrdjena,
			Date vrijeme, String komentar) {
		this.id = id;
		this.naslov = naslov;
		this.potvrdjena = potvrdjena;
		this.vrijeme = vrijeme;
		this.komentar = komentar;
	}

	public TemaZaZadacuId getId() {
		return this.id;
	}

	public void setId(TemaZaZadacuId id) {
		this.id = id;
	}

	public String getNaslov() {
		return this.naslov;
	}

	public void setNaslov(String naslov) {
		this.naslov = naslov;
	}

	public boolean isPotvrdjena() {
		return this.potvrdjena;
	}

	public void setPotvrdjena(boolean potvrdjena) {
		this.potvrdjena = potvrdjena;
	}

	public Date getVrijeme() {
		return this.vrijeme;
	}

	public void setVrijeme(Date vrijeme) {
		this.vrijeme = vrijeme;
	}

	public String getKomentar() {
		return this.komentar;
	}

	public void setKomentar(String komentar) {
		this.komentar = komentar;
	}

}
