package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tipkomponente generated by hbm2java
 */
public class Tipkomponente implements java.io.Serializable {

	private int id;
	private String naziv;
	private String opisOpcija;
	private Set<Komponenta> komponentas = new HashSet<Komponenta>(0);

	public Tipkomponente() {
	}

	public Tipkomponente(int id, String naziv, String opisOpcija) {
		this.id = id;
		this.naziv = naziv;
		this.opisOpcija = opisOpcija;
	}

	public Tipkomponente(int id, String naziv, String opisOpcija,
			Set<Komponenta> komponentas) {
		this.id = id;
		this.naziv = naziv;
		this.opisOpcija = opisOpcija;
		this.komponentas = komponentas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public String getOpisOpcija() {
		return this.opisOpcija;
	}

	public void setOpisOpcija(String opisOpcija) {
		this.opisOpcija = opisOpcija;
	}

	public Set<Komponenta> getKomponentas() {
		return this.komponentas;
	}

	public void setKomponentas(Set<Komponenta> komponentas) {
		this.komponentas = komponentas;
	}

}
