package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * TippredmetaKomponenta generated by hbm2java
 */
public class TippredmetaKomponenta implements java.io.Serializable {

	private TippredmetaKomponentaId id;

	public TippredmetaKomponenta() {
	}

	public TippredmetaKomponenta(TippredmetaKomponentaId id) {
		this.id = id;
	}

	public TippredmetaKomponentaId getId() {
		return this.id;
	}

	public void setId(TippredmetaKomponentaId id) {
		this.id = id;
	}

}
