package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * TipstudijaId generated by hbm2java
 */
public class TipstudijaId implements java.io.Serializable {

	private int id;
	private String naziv;
	private byte ciklus;
	private byte trajanje;
	private boolean mogucUpis;
	private int ects;

	public TipstudijaId() {
	}

	public TipstudijaId(int id, String naziv, byte ciklus, byte trajanje,
			boolean mogucUpis, int ects) {
		this.id = id;
		this.naziv = naziv;
		this.ciklus = ciklus;
		this.trajanje = trajanje;
		this.mogucUpis = mogucUpis;
		this.ects = ects;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public byte getCiklus() {
		return this.ciklus;
	}

	public void setCiklus(byte ciklus) {
		this.ciklus = ciklus;
	}

	public byte getTrajanje() {
		return this.trajanje;
	}

	public void setTrajanje(byte trajanje) {
		this.trajanje = trajanje;
	}

	public boolean isMogucUpis() {
		return this.mogucUpis;
	}

	public void setMogucUpis(boolean mogucUpis) {
		this.mogucUpis = mogucUpis;
	}

	public int getEcts() {
		return this.ects;
	}

	public void setEcts(int ects) {
		this.ects = ects;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TipstudijaId))
			return false;
		TipstudijaId castOther = (TipstudijaId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getNaziv() == castOther.getNaziv()) || (this
						.getNaziv() != null && castOther.getNaziv() != null && this
						.getNaziv().equals(castOther.getNaziv())))
				&& (this.getCiklus() == castOther.getCiklus())
				&& (this.getTrajanje() == castOther.getTrajanje())
				&& (this.isMogucUpis() == castOther.isMogucUpis())
				&& (this.getEcts() == castOther.getEcts());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getNaziv() == null ? 0 : this.getNaziv().hashCode());
		result = 37 * result + this.getCiklus();
		result = 37 * result + this.getTrajanje();
		result = 37 * result + (this.isMogucUpis() ? 1 : 0);
		result = 37 * result + this.getEcts();
		return result;
	}

}
