package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tipstudija generated by hbm2java
 */
public class Tipstudija implements java.io.Serializable {

	private TipstudijaId id;

	public Tipstudija() {
	}

	public Tipstudija(TipstudijaId id) {
		this.id = id;
	}

	public TipstudijaId getId() {
		return this.id;
	}

	public void setId(TipstudijaId id) {
		this.id = id;
	}

}
