package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tmpss generated by hbm2java
 */
public class Tmpss implements java.io.Serializable {

	private int student;

	public Tmpss() {
	}

	public Tmpss(int student) {
		this.student = student;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

}
