package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tmptable2 generated by hbm2java
 */
public class Tmptable2 implements java.io.Serializable {

	private Tmptable2Id id;

	public Tmptable2() {
	}

	public Tmptable2(Tmptable2Id id) {
		this.id = id;
	}

	public Tmptable2Id getId() {
		return this.id;
	}

	public void setId(Tmptable2Id id) {
		this.id = id;
	}

}
