package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tmptable generated by hbm2java
 */
public class Tmptable implements java.io.Serializable {

	private TmptableId id;

	public Tmptable() {
	}

	public Tmptable(TmptableId id) {
		this.id = id;
	}

	public TmptableId getId() {
		return this.id;
	}

	public void setId(TmptableId id) {
		this.id = id;
	}

}
