package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * TmptableId generated by hbm2java
 */
public class TmptableId implements java.io.Serializable {

	private int student;
	private int nacinStudiranja;

	public TmptableId() {
	}

	public TmptableId(int student, int nacinStudiranja) {
		this.student = student;
		this.nacinStudiranja = nacinStudiranja;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public int getNacinStudiranja() {
		return this.nacinStudiranja;
	}

	public void setNacinStudiranja(int nacinStudiranja) {
		this.nacinStudiranja = nacinStudiranja;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmptableId))
			return false;
		TmptableId castOther = (TmptableId) other;

		return (this.getStudent() == castOther.getStudent())
				&& (this.getNacinStudiranja() == castOther.getNacinStudiranja());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudent();
		result = 37 * result + this.getNacinStudiranja();
		return result;
	}

}
