package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tmptable4 generated by hbm2java
 */
public class Tmptable4 implements java.io.Serializable {

	private int id;
	private String ime;
	private String prezime;
	private String imeoca;
	private String prezimeoca;
	private String imemajke;
	private String prezimemajke;
	private String spol;
	private String email;
	private String brindexa;
	private String jmbg;
	private String adresa;
	private Integer adresaMjesto;
	private String telefon;
	private String login;
	private String privilegija;
	private String aliases;
	private String emails;
	private boolean trenutnoStudira;

	public Tmptable4() {
	}

	public Tmptable4(int id, String ime, String prezime, String imeoca,
			String prezimeoca, String imemajke, String prezimemajke,
			String spol, String email, String brindexa, String jmbg,
			String adresa, String telefon, String login, String privilegija,
			String aliases, String emails, boolean trenutnoStudira) {
		this.id = id;
		this.ime = ime;
		this.prezime = prezime;
		this.imeoca = imeoca;
		this.prezimeoca = prezimeoca;
		this.imemajke = imemajke;
		this.prezimemajke = prezimemajke;
		this.spol = spol;
		this.email = email;
		this.brindexa = brindexa;
		this.jmbg = jmbg;
		this.adresa = adresa;
		this.telefon = telefon;
		this.login = login;
		this.privilegija = privilegija;
		this.aliases = aliases;
		this.emails = emails;
		this.trenutnoStudira = trenutnoStudira;
	}

	public Tmptable4(int id, String ime, String prezime, String imeoca,
			String prezimeoca, String imemajke, String prezimemajke,
			String spol, String email, String brindexa, String jmbg,
			String adresa, Integer adresaMjesto, String telefon, String login,
			String privilegija, String aliases, String emails,
			boolean trenutnoStudira) {
		this.id = id;
		this.ime = ime;
		this.prezime = prezime;
		this.imeoca = imeoca;
		this.prezimeoca = prezimeoca;
		this.imemajke = imemajke;
		this.prezimemajke = prezimemajke;
		this.spol = spol;
		this.email = email;
		this.brindexa = brindexa;
		this.jmbg = jmbg;
		this.adresa = adresa;
		this.adresaMjesto = adresaMjesto;
		this.telefon = telefon;
		this.login = login;
		this.privilegija = privilegija;
		this.aliases = aliases;
		this.emails = emails;
		this.trenutnoStudira = trenutnoStudira;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getIme() {
		return this.ime;
	}

	public void setIme(String ime) {
		this.ime = ime;
	}

	public String getPrezime() {
		return this.prezime;
	}

	public void setPrezime(String prezime) {
		this.prezime = prezime;
	}

	public String getImeoca() {
		return this.imeoca;
	}

	public void setImeoca(String imeoca) {
		this.imeoca = imeoca;
	}

	public String getPrezimeoca() {
		return this.prezimeoca;
	}

	public void setPrezimeoca(String prezimeoca) {
		this.prezimeoca = prezimeoca;
	}

	public String getImemajke() {
		return this.imemajke;
	}

	public void setImemajke(String imemajke) {
		this.imemajke = imemajke;
	}

	public String getPrezimemajke() {
		return this.prezimemajke;
	}

	public void setPrezimemajke(String prezimemajke) {
		this.prezimemajke = prezimemajke;
	}

	public String getSpol() {
		return this.spol;
	}

	public void setSpol(String spol) {
		this.spol = spol;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getBrindexa() {
		return this.brindexa;
	}

	public void setBrindexa(String brindexa) {
		this.brindexa = brindexa;
	}

	public String getJmbg() {
		return this.jmbg;
	}

	public void setJmbg(String jmbg) {
		this.jmbg = jmbg;
	}

	public String getAdresa() {
		return this.adresa;
	}

	public void setAdresa(String adresa) {
		this.adresa = adresa;
	}

	public Integer getAdresaMjesto() {
		return this.adresaMjesto;
	}

	public void setAdresaMjesto(Integer adresaMjesto) {
		this.adresaMjesto = adresaMjesto;
	}

	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPrivilegija() {
		return this.privilegija;
	}

	public void setPrivilegija(String privilegija) {
		this.privilegija = privilegija;
	}

	public String getAliases() {
		return this.aliases;
	}

	public void setAliases(String aliases) {
		this.aliases = aliases;
	}

	public String getEmails() {
		return this.emails;
	}

	public void setEmails(String emails) {
		this.emails = emails;
	}

	public boolean isTrenutnoStudira() {
		return this.trenutnoStudira;
	}

	public void setTrenutnoStudira(boolean trenutnoStudira) {
		this.trenutnoStudira = trenutnoStudira;
	}

}
