package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tmptable3 generated by hbm2java
 */
public class Tmptable3 implements java.io.Serializable {

	private int zamgerid;

	public Tmptable3() {
	}

	public Tmptable3(int zamgerid) {
		this.zamgerid = zamgerid;
	}

	public int getZamgerid() {
		return this.zamgerid;
	}

	public void setZamgerid(int zamgerid) {
		this.zamgerid = zamgerid;
	}

}
