package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tmptable2Id generated by hbm2java
 */
public class Tmptable2Id implements java.io.Serializable {

	private int student;
	private int studij;
	private int semestar;
	private int akademskaGodina;
	private int nacinStudiranja;
	private byte ponovac;
	private int odluka;

	public Tmptable2Id() {
	}

	public Tmptable2Id(int student, int studij, int semestar,
			int akademskaGodina, int nacinStudiranja, byte ponovac, int odluka) {
		this.student = student;
		this.studij = studij;
		this.semestar = semestar;
		this.akademskaGodina = akademskaGodina;
		this.nacinStudiranja = nacinStudiranja;
		this.ponovac = ponovac;
		this.odluka = odluka;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public int getStudij() {
		return this.studij;
	}

	public void setStudij(int studij) {
		this.studij = studij;
	}

	public int getSemestar() {
		return this.semestar;
	}

	public void setSemestar(int semestar) {
		this.semestar = semestar;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public int getNacinStudiranja() {
		return this.nacinStudiranja;
	}

	public void setNacinStudiranja(int nacinStudiranja) {
		this.nacinStudiranja = nacinStudiranja;
	}

	public byte getPonovac() {
		return this.ponovac;
	}

	public void setPonovac(byte ponovac) {
		this.ponovac = ponovac;
	}

	public int getOdluka() {
		return this.odluka;
	}

	public void setOdluka(int odluka) {
		this.odluka = odluka;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Tmptable2Id))
			return false;
		Tmptable2Id castOther = (Tmptable2Id) other;

		return (this.getStudent() == castOther.getStudent())
				&& (this.getStudij() == castOther.getStudij())
				&& (this.getSemestar() == castOther.getSemestar())
				&& (this.getAkademskaGodina() == castOther.getAkademskaGodina())
				&& (this.getNacinStudiranja() == castOther.getNacinStudiranja())
				&& (this.getPonovac() == castOther.getPonovac())
				&& (this.getOdluka() == castOther.getOdluka());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudent();
		result = 37 * result + this.getStudij();
		result = 37 * result + this.getSemestar();
		result = 37 * result + this.getAkademskaGodina();
		result = 37 * result + this.getNacinStudiranja();
		result = 37 * result + this.getPonovac();
		result = 37 * result + this.getOdluka();
		return result;
	}

}
