package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * UgovoroucenjuKapacitetId generated by hbm2java
 */
public class UgovoroucenjuKapacitetId implements java.io.Serializable {

	private int predmet;
	private int akademskaGodina;
	private int kapacitet;
	private int kapacitetEkstra;

	public UgovoroucenjuKapacitetId() {
	}

	public UgovoroucenjuKapacitetId(int predmet, int akademskaGodina,
			int kapacitet, int kapacitetEkstra) {
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.kapacitet = kapacitet;
		this.kapacitetEkstra = kapacitetEkstra;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public int getKapacitet() {
		return this.kapacitet;
	}

	public void setKapacitet(int kapacitet) {
		this.kapacitet = kapacitet;
	}

	public int getKapacitetEkstra() {
		return this.kapacitetEkstra;
	}

	public void setKapacitetEkstra(int kapacitetEkstra) {
		this.kapacitetEkstra = kapacitetEkstra;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UgovoroucenjuKapacitetId))
			return false;
		UgovoroucenjuKapacitetId castOther = (UgovoroucenjuKapacitetId) other;

		return (this.getPredmet() == castOther.getPredmet())
				&& (this.getAkademskaGodina() == castOther.getAkademskaGodina())
				&& (this.getKapacitet() == castOther.getKapacitet())
				&& (this.getKapacitetEkstra() == castOther.getKapacitetEkstra());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPredmet();
		result = 37 * result + this.getAkademskaGodina();
		result = 37 * result + this.getKapacitet();
		result = 37 * result + this.getKapacitetEkstra();
		return result;
	}

}
