package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * UgovoroucenjuIzborni generated by hbm2java
 */
public class UgovoroucenjuIzborni implements java.io.Serializable {

	private UgovoroucenjuIzborniId id;

	public UgovoroucenjuIzborni() {
	}

	public UgovoroucenjuIzborni(UgovoroucenjuIzborniId id) {
		this.id = id;
	}

	public UgovoroucenjuIzborniId getId() {
		return this.id;
	}

	public void setId(UgovoroucenjuIzborniId id) {
		this.id = id;
	}

}
