package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * UgovoroucenjuKapacitet generated by hbm2java
 */
public class UgovoroucenjuKapacitet implements java.io.Serializable {

	private UgovoroucenjuKapacitetId id;

	public UgovoroucenjuKapacitet() {
	}

	public UgovoroucenjuKapacitet(UgovoroucenjuKapacitetId id) {
		this.id = id;
	}

	public UgovoroucenjuKapacitetId getId() {
		return this.id;
	}

	public void setId(UgovoroucenjuKapacitetId id) {
		this.id = id;
	}

}
