package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * UpisKriterij generated by hbm2java
 */
public class UpisKriterij implements java.io.Serializable {

	private UpisKriterijId id;
	private float donjaGranica;
	private float gornjaGranica;
	private int kandidatiStrani;
	private int kandidatiSamiPlacaju;
	private int kandidatiKantonPlaca;
	private int kandidatiVanredni;
	private int prijemniMax;

	public UpisKriterij() {
	}

	public UpisKriterij(UpisKriterijId id, float donjaGranica,
			float gornjaGranica, int kandidatiStrani, int kandidatiSamiPlacaju,
			int kandidatiKantonPlaca, int kandidatiVanredni, int prijemniMax) {
		this.id = id;
		this.donjaGranica = donjaGranica;
		this.gornjaGranica = gornjaGranica;
		this.kandidatiStrani = kandidatiStrani;
		this.kandidatiSamiPlacaju = kandidatiSamiPlacaju;
		this.kandidatiKantonPlaca = kandidatiKantonPlaca;
		this.kandidatiVanredni = kandidatiVanredni;
		this.prijemniMax = prijemniMax;
	}

	public UpisKriterijId getId() {
		return this.id;
	}

	public void setId(UpisKriterijId id) {
		this.id = id;
	}

	public float getDonjaGranica() {
		return this.donjaGranica;
	}

	public void setDonjaGranica(float donjaGranica) {
		this.donjaGranica = donjaGranica;
	}

	public float getGornjaGranica() {
		return this.gornjaGranica;
	}

	public void setGornjaGranica(float gornjaGranica) {
		this.gornjaGranica = gornjaGranica;
	}

	public int getKandidatiStrani() {
		return this.kandidatiStrani;
	}

	public void setKandidatiStrani(int kandidatiStrani) {
		this.kandidatiStrani = kandidatiStrani;
	}

	public int getKandidatiSamiPlacaju() {
		return this.kandidatiSamiPlacaju;
	}

	public void setKandidatiSamiPlacaju(int kandidatiSamiPlacaju) {
		this.kandidatiSamiPlacaju = kandidatiSamiPlacaju;
	}

	public int getKandidatiKantonPlaca() {
		return this.kandidatiKantonPlaca;
	}

	public void setKandidatiKantonPlaca(int kandidatiKantonPlaca) {
		this.kandidatiKantonPlaca = kandidatiKantonPlaca;
	}

	public int getKandidatiVanredni() {
		return this.kandidatiVanredni;
	}

	public void setKandidatiVanredni(int kandidatiVanredni) {
		this.kandidatiVanredni = kandidatiVanredni;
	}

	public int getPrijemniMax() {
		return this.prijemniMax;
	}

	public void setPrijemniMax(int prijemniMax) {
		this.prijemniMax = prijemniMax;
	}

}
