package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * UspjehUSrednjoj generated by hbm2java
 */
public class UspjehUSrednjoj implements java.io.Serializable {

	private int osoba;
	private int srednjaSkola;
	private int godina;
	private double opciUspjeh;
	private double kljucniPredmeti;
	private double dodatniBodovi;
	private boolean ucenikGeneracije;

	public UspjehUSrednjoj() {
	}

	public UspjehUSrednjoj(int osoba, int srednjaSkola, int godina,
			double opciUspjeh, double kljucniPredmeti, double dodatniBodovi,
			boolean ucenikGeneracije) {
		this.osoba = osoba;
		this.srednjaSkola = srednjaSkola;
		this.godina = godina;
		this.opciUspjeh = opciUspjeh;
		this.kljucniPredmeti = kljucniPredmeti;
		this.dodatniBodovi = dodatniBodovi;
		this.ucenikGeneracije = ucenikGeneracije;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public int getSrednjaSkola() {
		return this.srednjaSkola;
	}

	public void setSrednjaSkola(int srednjaSkola) {
		this.srednjaSkola = srednjaSkola;
	}

	public int getGodina() {
		return this.godina;
	}

	public void setGodina(int godina) {
		this.godina = godina;
	}

	public double getOpciUspjeh() {
		return this.opciUspjeh;
	}

	public void setOpciUspjeh(double opciUspjeh) {
		this.opciUspjeh = opciUspjeh;
	}

	public double getKljucniPredmeti() {
		return this.kljucniPredmeti;
	}

	public void setKljucniPredmeti(double kljucniPredmeti) {
		this.kljucniPredmeti = kljucniPredmeti;
	}

	public double getDodatniBodovi() {
		return this.dodatniBodovi;
	}

	public void setDodatniBodovi(double dodatniBodovi) {
		this.dodatniBodovi = dodatniBodovi;
	}

	public boolean isUcenikGeneracije() {
		return this.ucenikGeneracije;
	}

	public void setUcenikGeneracije(boolean ucenikGeneracije) {
		this.ucenikGeneracije = ucenikGeneracije;
	}

}
