package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * WebideProjekti generated by hbm2java
 */
public class WebideProjekti implements java.io.Serializable {

	private Integer id;
	private String naziv;
	private int vlasnik;
	private int programskijezik;

	public WebideProjekti() {
	}

	public WebideProjekti(String naziv, int vlasnik, int programskijezik) {
		this.naziv = naziv;
		this.vlasnik = vlasnik;
		this.programskijezik = programskijezik;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public int getVlasnik() {
		return this.vlasnik;
	}

	public void setVlasnik(int vlasnik) {
		this.vlasnik = vlasnik;
	}

	public int getProgramskijezik() {
		return this.programskijezik;
	}

	public void setProgramskijezik(int programskijezik) {
		this.programskijezik = programskijezik;
	}

}
