package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Workpackage generated by hbm2java
 */
public class Workpackage implements java.io.Serializable {

	private Integer id;
	private Date kreiran;
	private boolean zavrsen;

	public Workpackage() {
	}

	public Workpackage(Date kreiran, boolean zavrsen) {
		this.kreiran = kreiran;
		this.zavrsen = zavrsen;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getKreiran() {
		return this.kreiran;
	}

	public void setKreiran(Date kreiran) {
		this.kreiran = kreiran;
	}

	public boolean isZavrsen() {
		return this.zavrsen;
	}

	public void setZavrsen(boolean zavrsen) {
		this.zavrsen = zavrsen;
	}

}
