package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Workpackage generated by hbm2java
 */
public class WsOauthRequest implements java.io.Serializable {

	private Integer id;
	private String code;
	private Osoba osoba;

	public WsOauthRequest() {
	}

	public WsOauthRequest(Osoba osoba, String code) {
		this.osoba = osoba;
		this.code = code;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Osoba getOsoba() {
		return this.osoba;
	}

	public void setOsoba(Osoba osoba) {
		this.osoba = osoba;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
