package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Workpackage generated by hbm2java
 */
public class WsSession implements java.io.Serializable {

	private Integer id;
	private Osoba osoba;
	private String token;

	public WsSession() {
	}

	public WsSession(Osoba osoba, String token) {
		this.osoba = osoba;
		this.token = token;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Osoba getOsoba() {
		return this.osoba;
	}

	public void setOsoba(Osoba osoba) {
		this.osoba = osoba;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
