package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Zadatakdiff generated by hbm2java
 */
public class Zadatakdiff implements java.io.Serializable {

	private long zadatak;
	private String diff;

	public Zadatakdiff() {
	}

	public Zadatakdiff(long zadatak, String diff) {
		this.zadatak = zadatak;
		this.diff = diff;
	}

	public long getZadatak() {
		return this.zadatak;
	}

	public void setZadatak(long zadatak) {
		this.zadatak = zadatak;
	}

	public String getDiff() {
		return this.diff;
	}

	public void setDiff(String diff) {
		this.diff = diff;
	}

}
