package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Zadatak generated by hbm2java
 */
public class Zadatak implements java.io.Serializable {

	private Long id;
	private int zadaca;
	private int redniBroj;
	private int student;
	private byte status;
	private float bodova;
	private String izvjestajSkripte;
	private Date vrijeme;
	private String komentar;
	private String filename;
	private int userid;

	public Zadatak() {
	}

	public Zadatak(int zadaca, int redniBroj, int student, byte status,
			float bodova, String izvjestajSkripte, String komentar,
			String filename, int userid) {
		this.zadaca = zadaca;
		this.redniBroj = redniBroj;
		this.student = student;
		this.status = status;
		this.bodova = bodova;
		this.izvjestajSkripte = izvjestajSkripte;
		this.komentar = komentar;
		this.filename = filename;
		this.userid = userid;
	}

	public Zadatak(int zadaca, int redniBroj, int student, byte status,
			float bodova, String izvjestajSkripte, Date vrijeme,
			String komentar, String filename, int userid) {
		this.zadaca = zadaca;
		this.redniBroj = redniBroj;
		this.student = student;
		this.status = status;
		this.bodova = bodova;
		this.izvjestajSkripte = izvjestajSkripte;
		this.vrijeme = vrijeme;
		this.komentar = komentar;
		this.filename = filename;
		this.userid = userid;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getZadaca() {
		return this.zadaca;
	}

	public void setZadaca(int zadaca) {
		this.zadaca = zadaca;
	}

	public int getRedniBroj() {
		return this.redniBroj;
	}

	public void setRedniBroj(int redniBroj) {
		this.redniBroj = redniBroj;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public float getBodova() {
		return this.bodova;
	}

	public void setBodova(float bodova) {
		this.bodova = bodova;
	}

	public String getIzvjestajSkripte() {
		return this.izvjestajSkripte;
	}

	public void setIzvjestajSkripte(String izvjestajSkripte) {
		this.izvjestajSkripte = izvjestajSkripte;
	}

	public Date getVrijeme() {
		return this.vrijeme;
	}

	public void setVrijeme(Date vrijeme) {
		this.vrijeme = vrijeme;
	}

	public String getKomentar() {
		return this.komentar;
	}

	public void setKomentar(String komentar) {
		this.komentar = komentar;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

}
