package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Zadaca generated by hbm2java
 */
public class Zadaca implements java.io.Serializable {

	private Integer id;
	private String naziv;
	private int predmet;
	private int akademskaGodina;
	private byte zadataka;
	private float bodova;
	private Date rok;
	private boolean aktivna;
	private int programskijezik;
	private boolean automatskoTestiranje;
	private boolean attachment;
	private String dozvoljeneEkstenzije;
	private String postavkaZadace;
	private int komponenta;
	private Date vrijemeobjave;
	private Set<Autotest> autotests = new HashSet<Autotest>(0);
	private Set<AutotestReplace> autotestReplaces = new HashSet<AutotestReplace>(
			0);

	public Zadaca() {
	}

	public Zadaca(String naziv, int predmet, int akademskaGodina,
			byte zadataka, float bodova, Date rok, boolean aktivna,
			int programskijezik, boolean automatskoTestiranje,
			boolean attachment, int komponenta, Date vrijemeobjave) {
		this.naziv = naziv;
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.zadataka = zadataka;
		this.bodova = bodova;
		this.rok = rok;
		this.aktivna = aktivna;
		this.programskijezik = programskijezik;
		this.automatskoTestiranje = automatskoTestiranje;
		this.attachment = attachment;
		this.komponenta = komponenta;
		this.vrijemeobjave = vrijemeobjave;
	}

	public Zadaca(String naziv, int predmet, int akademskaGodina,
			byte zadataka, float bodova, Date rok, boolean aktivna,
			int programskijezik, boolean automatskoTestiranje,
			boolean attachment, String dozvoljeneEkstenzije,
			String postavkaZadace, int komponenta, Date vrijemeobjave,
			Set<Autotest> autotests, Set<AutotestReplace> autotestReplaces) {
		this.naziv = naziv;
		this.predmet = predmet;
		this.akademskaGodina = akademskaGodina;
		this.zadataka = zadataka;
		this.bodova = bodova;
		this.rok = rok;
		this.aktivna = aktivna;
		this.programskijezik = programskijezik;
		this.automatskoTestiranje = automatskoTestiranje;
		this.attachment = attachment;
		this.dozvoljeneEkstenzije = dozvoljeneEkstenzije;
		this.postavkaZadace = postavkaZadace;
		this.komponenta = komponenta;
		this.vrijemeobjave = vrijemeobjave;
		this.autotests = autotests;
		this.autotestReplaces = autotestReplaces;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public int getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(int akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public byte getZadataka() {
		return this.zadataka;
	}

	public void setZadataka(byte zadataka) {
		this.zadataka = zadataka;
	}

	public float getBodova() {
		return this.bodova;
	}

	public void setBodova(float bodova) {
		this.bodova = bodova;
	}

	public Date getRok() {
		return this.rok;
	}

	public void setRok(Date rok) {
		this.rok = rok;
	}

	public boolean isAktivna() {
		return this.aktivna;
	}

	public void setAktivna(boolean aktivna) {
		this.aktivna = aktivna;
	}

	public int getProgramskijezik() {
		return this.programskijezik;
	}

	public void setProgramskijezik(int programskijezik) {
		this.programskijezik = programskijezik;
	}

	public boolean isAutomatskoTestiranje() {
		return this.automatskoTestiranje;
	}

	public void setAutomatskoTestiranje(boolean automatskoTestiranje) {
		this.automatskoTestiranje = automatskoTestiranje;
	}

	public boolean isAttachment() {
		return this.attachment;
	}

	public void setAttachment(boolean attachment) {
		this.attachment = attachment;
	}

	public String getDozvoljeneEkstenzije() {
		return this.dozvoljeneEkstenzije;
	}

	public void setDozvoljeneEkstenzije(String dozvoljeneEkstenzije) {
		this.dozvoljeneEkstenzije = dozvoljeneEkstenzije;
	}

	public String getPostavkaZadace() {
		return this.postavkaZadace;
	}

	public void setPostavkaZadace(String postavkaZadace) {
		this.postavkaZadace = postavkaZadace;
	}

	public int getKomponenta() {
		return this.komponenta;
	}

	public void setKomponenta(int komponenta) {
		this.komponenta = komponenta;
	}

	public Date getVrijemeobjave() {
		return this.vrijemeobjave;
	}

	public void setVrijemeobjave(Date vrijemeobjave) {
		this.vrijemeobjave = vrijemeobjave;
	}

	public Set<Autotest> getAutotests() {
		return this.autotests;
	}

	public void setAutotests(Set<Autotest> autotests) {
		this.autotests = autotests;
	}

	public Set<AutotestReplace> getAutotestReplaces() {
		return this.autotestReplaces;
	}

	public void setAutotestReplaces(Set<AutotestReplace> autotestReplaces) {
		this.autotestReplaces = autotestReplaces;
	}

}
