package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Zavrsni generated by hbm2java
 */
public class Zavrsni implements java.io.Serializable {

	private Integer id;
	private String naslov;
	private String podnaslov;
	private int predmet;
	private int radNaPredmetu;
	private String akademskaGodina;
	private String kratkiPregled;
	private String literatura;
	private String sazetak;
	private String summary;
	private int mentor;
	private int student;
	private byte kandidatPotvrdjen;
	private String biljeska;
	private int predsjednikKomisije;
	private int clanKomisije;
	private Date terminOdbrane;
	private String brojDiplome;
	private byte temaOdobrena;
	private String sala;
	private int odluka;

	public Zavrsni() {
	}

	public Zavrsni(String naslov, String podnaslov, int predmet,
			int radNaPredmetu, String akademskaGodina, String kratkiPregled,
			String literatura, String sazetak, String summary, int mentor,
			int student, byte kandidatPotvrdjen, String biljeska,
			int predsjednikKomisije, int clanKomisije, Date terminOdbrane,
			String brojDiplome, byte temaOdobrena, String sala, int odluka) {
		this.naslov = naslov;
		this.podnaslov = podnaslov;
		this.predmet = predmet;
		this.radNaPredmetu = radNaPredmetu;
		this.akademskaGodina = akademskaGodina;
		this.kratkiPregled = kratkiPregled;
		this.literatura = literatura;
		this.sazetak = sazetak;
		this.summary = summary;
		this.mentor = mentor;
		this.student = student;
		this.kandidatPotvrdjen = kandidatPotvrdjen;
		this.biljeska = biljeska;
		this.predsjednikKomisije = predsjednikKomisije;
		this.clanKomisije = clanKomisije;
		this.terminOdbrane = terminOdbrane;
		this.brojDiplome = brojDiplome;
		this.temaOdobrena = temaOdobrena;
		this.sala = sala;
		this.odluka = odluka;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNaslov() {
		return this.naslov;
	}

	public void setNaslov(String naslov) {
		this.naslov = naslov;
	}

	public String getPodnaslov() {
		return this.podnaslov;
	}

	public void setPodnaslov(String podnaslov) {
		this.podnaslov = podnaslov;
	}

	public int getPredmet() {
		return this.predmet;
	}

	public void setPredmet(int predmet) {
		this.predmet = predmet;
	}

	public int getRadNaPredmetu() {
		return this.radNaPredmetu;
	}

	public void setRadNaPredmetu(int radNaPredmetu) {
		this.radNaPredmetu = radNaPredmetu;
	}

	public String getAkademskaGodina() {
		return this.akademskaGodina;
	}

	public void setAkademskaGodina(String akademskaGodina) {
		this.akademskaGodina = akademskaGodina;
	}

	public String getKratkiPregled() {
		return this.kratkiPregled;
	}

	public void setKratkiPregled(String kratkiPregled) {
		this.kratkiPregled = kratkiPregled;
	}

	public String getLiteratura() {
		return this.literatura;
	}

	public void setLiteratura(String literatura) {
		this.literatura = literatura;
	}

	public String getSazetak() {
		return this.sazetak;
	}

	public void setSazetak(String sazetak) {
		this.sazetak = sazetak;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public int getMentor() {
		return this.mentor;
	}

	public void setMentor(int mentor) {
		this.mentor = mentor;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public byte getKandidatPotvrdjen() {
		return this.kandidatPotvrdjen;
	}

	public void setKandidatPotvrdjen(byte kandidatPotvrdjen) {
		this.kandidatPotvrdjen = kandidatPotvrdjen;
	}

	public String getBiljeska() {
		return this.biljeska;
	}

	public void setBiljeska(String biljeska) {
		this.biljeska = biljeska;
	}

	public int getPredsjednikKomisije() {
		return this.predsjednikKomisije;
	}

	public void setPredsjednikKomisije(int predsjednikKomisije) {
		this.predsjednikKomisije = predsjednikKomisije;
	}

	public int getClanKomisije() {
		return this.clanKomisije;
	}

	public void setClanKomisije(int clanKomisije) {
		this.clanKomisije = clanKomisije;
	}

	public Date getTerminOdbrane() {
		return this.terminOdbrane;
	}

	public void setTerminOdbrane(Date terminOdbrane) {
		this.terminOdbrane = terminOdbrane;
	}

	public String getBrojDiplome() {
		return this.brojDiplome;
	}

	public void setBrojDiplome(String brojDiplome) {
		this.brojDiplome = brojDiplome;
	}

	public byte getTemaOdobrena() {
		return this.temaOdobrena;
	}

	public void setTemaOdobrena(byte temaOdobrena) {
		this.temaOdobrena = temaOdobrena;
	}

	public String getSala() {
		return this.sala;
	}

	public void setSala(String sala) {
		this.sala = sala;
	}

	public int getOdluka() {
		return this.odluka;
	}

	public void setOdluka(int odluka) {
		this.odluka = odluka;
	}

}
