package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * ZavrsniBbPostText generated by hbm2java
 */
public class ZavrsniBbPostText implements java.io.Serializable {

	private int post;
	private String tekst;

	public ZavrsniBbPostText() {
	}

	public ZavrsniBbPostText(int post, String tekst) {
		this.post = post;
		this.tekst = tekst;
	}

	public int getPost() {
		return this.post;
	}

	public void setPost(int post) {
		this.post = post;
	}

	public String getTekst() {
		return this.tekst;
	}

	public void setTekst(String tekst) {
		this.tekst = tekst;
	}

}
