package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ZavrsniBbPost generated by hbm2java
 */
public class ZavrsniBbPost implements java.io.Serializable {

	private int id;
	private String naslov;
	private Date vrijeme;
	private int osoba;
	private int tema;

	public ZavrsniBbPost() {
	}

	public ZavrsniBbPost(int id, String naslov, Date vrijeme, int osoba,
			int tema) {
		this.id = id;
		this.naslov = naslov;
		this.vrijeme = vrijeme;
		this.osoba = osoba;
		this.tema = tema;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNaslov() {
		return this.naslov;
	}

	public void setNaslov(String naslov) {
		this.naslov = naslov;
	}

	public Date getVrijeme() {
		return this.vrijeme;
	}

	public void setVrijeme(Date vrijeme) {
		this.vrijeme = vrijeme;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public int getTema() {
		return this.tema;
	}

	public void setTema(int tema) {
		this.tema = tema;
	}

}
