package ba.unsa.etf.zamger.beans;

// Generated May 20, 2015 3:15:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ZavrsniFile generated by hbm2java
 */
public class ZavrsniFile implements java.io.Serializable {

	private int id;
	private String filename;
	private Date vrijeme;
	private byte revizija;
	private int osoba;
	private int zavrsni;
	private int file;

	public ZavrsniFile() {
	}

	public ZavrsniFile(int id, String filename, Date vrijeme, byte revizija,
			int osoba, int zavrsni, int file) {
		this.id = id;
		this.filename = filename;
		this.vrijeme = vrijeme;
		this.revizija = revizija;
		this.osoba = osoba;
		this.zavrsni = zavrsni;
		this.file = file;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public Date getVrijeme() {
		return this.vrijeme;
	}

	public void setVrijeme(Date vrijeme) {
		this.vrijeme = vrijeme;
	}

	public byte getRevizija() {
		return this.revizija;
	}

	public void setRevizija(byte revizija) {
		this.revizija = revizija;
	}

	public int getOsoba() {
		return this.osoba;
	}

	public void setOsoba(int osoba) {
		this.osoba = osoba;
	}

	public int getZavrsni() {
		return this.zavrsni;
	}

	public void setZavrsni(int zavrsni) {
		this.zavrsni = zavrsni;
	}

	public int getFile() {
		return this.file;
	}

	public void setFile(int file) {
		this.file = file;
	}

}
